### ISSUE TITLE
Installation timeout caused by logging component

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#10419] opened 2021-01-21 21:33 UTC
**Description**

The installation failed because of waiting for logging component to be ready. Logging was installed in 45 minutes. 

**Expected result**

Logging is installed in a reasonable time.

**Actual result**

Kyma installed in 65 minutes.

**Steps to reproduce**

The failure was observed in evaluation profile pipeline: 
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1352286203314966528
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1352437199626309632/build-log.txt

The installer log:
[slow-loggingg.txt](https://github.com/kyma-project/kyma/files/5852273/slow-loggingg.txt)

**Comment by a-thaler** [comment] 2021-01-22 08:00
As far as I see it is the one-node plan on azure with evaluation profile and azure event hub.
In the node description you see a lot of SystemOOM printed so I guess at least one pod cannot come up because of limited memory, we will need to reproduce it.

**Comment by a-thaler** [comment] 2021-01-27 19:40
We cannot reproduce it, please re-open if it happens again. I guess it was hitting logging by accident, in real there was some SystemOOM happening.

**Comment by pbochynski** [comment] 2021-01-28 08:30
The pipeline is red since yesterday. Most of the time installation stucks on logging:
https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/kyma-integration-production-gardener-azure

**Comment by a-thaler** [comment] 2021-01-28 20:38
Fixed by https://github.com/kyma-project/kyma/pull/10469

**Comment by pbochynski** [comment] 2021-01-29 13:13
And again :)
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1355094752529223680
Installer logs: https://cloudlogging.app.goo.gl/K2JaSKrEBYAdokk58

**Comment by pbochynski** [comment] 2021-02-11 08:12
https://prow.k8s.io/view/gs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1359624734450388992

**Comment by a-thaler** [comment] 2021-02-15 14:32
Whenever the logging was hanging, there was a lot of System OOMs involved not being specific about the victim processes. It turned out that the log-ui used a too minimalistic memory limit. That got fixed in https://github.com/kyma-project/kyma/pull/10576.

**Closed by a-thaler** 2021-02-15 14:32 UTC
Labels: area/logging, bug, test-failing
