### ISSUE TITLE
Intermittent 404 

### ISSUE THREAD

**Issue by wwosik** [kyma-project/kyma#10544] opened 2021-02-08 13:50 UTC
When calling a service deployed to a managed kyma instance, 404 is randomly returned with info:

 {"error":{"code":404,"status":"Not Found","request":"e8798e76-dd02-4620-bbed-5bb0ee050932","message":"The requested resource could not be found"}}

This is both for POST and GET requests. A retry (F5) shows the page, however, sometimes more than one retry is needed. 

Note that in case of such 404 no log entry is available which suggests the request is lost already at the API gateway level.

**Comment by strekm** [comment] 2021-02-10 09:07
hello @wwosik, thanks for reporting. is your service exposed with APIRule? Where do you see that 404 error? If possible please provide steps to reproduce and info about kyma version.

**Comment by wwosik** [comment] 2021-02-10 09:43
It is exposed with an API rule. One of the cases is an nginx container with a range of static files. No logic that could go awry. The main file is index.html which references a range of .js files. And those .js files randomly error out - sometimes they are returned, sometimes not. Sometimes even index.html itself fails to load.

Unfortunately, unlike a programmatic backend call that can be re-tried, the browser does not retry a download of an individual missing file.

**Comment by mado0803** [comment] 2021-02-10 14:06
This is related to https://github.com/kyma-project/kyma/issues/10571 which was found as root cause.

**Comment by Tomasz-Smelcerz-SAP** [comment] 2021-02-11 10:37
Closing in favor of #10571

**Closed by Tomasz-Smelcerz-SAP** 2021-02-11 10:37 UTC
Labels: area/api-gateway
