### ISSUE TITLE
kyma-integration-k3d fails regularly

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#13563] opened 2022-03-07 11:26 UTC
**Description**
The job [kyma-integration-k3d](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-integration-k3d) fails regularly to connect Commerce Mock to Kyma:

```
  1) Executing Standard Testsuite:
       CommerceMock Tests:
         CommerceMock test fixture should be ready:
     Error: Error during establishing connection from Commerce Mock to Kyma connector service
500: Internal Server Error: {"error":"Error: connect ECONNREFUSED 127.0.0.1:443"}
      at convertAxiosError (utils/index.js:109:10)
      at connectCommerceMock (test/fixtures/commerce-mock/index.js:538:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async connectMockLocal (test/fixtures/commerce-mock/index.js:500:3)
      at async ensureCommerceMockLocalTestFixture (test/fixtures/commerce-mock/index.js:649:3)
      at async Context.<anonymous> (test/1-commerce-mock.js:51:7)
```

Examples:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d/1500684066305871872/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d/1500623667783012352/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d/1500276376077340672/build-log.txt

**Comment by a-thaler** [comment] 2022-03-07 12:53
Looks like a call from the mock to the kyma connector service failed with a 500 as part of the connection establishing flow. With that any follow-up call will fail with for example `Cannot send legacy event, the response from event gateway: { error: 'Not connected to a kyma cluster, please re-connect' }`

So something might have changed in the kyma connector service?

**Comment by franpog859** [comment] 2022-03-08 07:22
The last change to Connector Service was over a month ago and it was just some library bump for security purposes. The one prior to this one was about five months ago. For how long do you observe the regular failures? Looking at the job's history I cannot see any regularity 😅

**Comment by pbochynski** [comment] 2022-03-08 07:55
The job started to fail around February 12 (when I went on vacation). Before it was 100% green. Maybe it is a timing issue. There is only 30 sec timeout. Maybe the connector service is not ready yet. BTW timeouts handling is weird. Here you have 30 sec timeout:
https://github.com/kyma-project/kyma/blob/08b347c121eb91532f3c070aaa04ac8f86948270/tests/fast-integration/test/fixtures/commerce-mock/index.js#L532
But this function is called from here 10 times with 3 sec timeout:
https://github.com/kyma-project/kyma/blob/08b347c121eb91532f3c070aaa04ac8f86948270/tests/fast-integration/test/fixtures/commerce-mock/index.js#L649

**Comment by franpog859** [comment] 2022-03-08 08:14
It may be. Not sure why it just started to happen as there were no changes in the Connector Service though. Did anything change on the Commerce Mock side, @a-thaler ?

Anyway, there is a PR for unifying the intervals with the nested timeouts, you mentioned, @pbochynski - https://github.com/kyma-project/kyma/pull/13569

**Comment by franpog859** [comment] 2022-03-09 10:56
[The PR](https://github.com/kyma-project/kyma/pull/13569) is merged. I'm closing the issue. Let's observe the job and reopen this issue if the error still exists

**Comment by janmedrek** [comment] 2022-03-10 08:43
Two fails from yesterday with this error, unfortunately:
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d/1501665434686984192
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d/1501650334798319616

**Comment by mvshao** [comment] 2022-03-14 21:48
I tested `kyma-integration-k3d` on pipelines using the pjtester. For 15 runs, only one failed due to a problem with creating k3d node. [Here it is](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/mvshao_test_of_prowjob_kyma-integration-k3d) the link to all the test jobs.
I also created a PR containing a version update of the commerce-mock in Kyma resources.

**Comment by mvshao** [comment] 2022-03-18 10:08
Currently, the `kyma-integration-k3d` job has set the `DEBUG=true` environmental variable, but after that change, I still can't see more detailed logs from Varkes / commerce-mock. At this time without proper logging, I am not able to test and track this error. In the previous comment, I mentioned a PR that contains the version update of commerce-mock. 
I think we need also to consider the current stability of Prow jobs, perhaps this is our issue.

If anyone has got a breakthrough idea I am open to discussion 😃

**Comment by mvshao** [comment] 2022-03-21 08:40
In the past few days, I didn't observe any failure of this job regarding commerce mock / connector service error. I'm closing the issue. Let's observe the job and reopen this issue again.

**Comment by pbochynski** [comment] 2022-03-23 10:24
It happened yesterday 3 times:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d/1506346355537219584/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d/1506195358814834688/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d/1506044471928688640/build-log.txt

**Comment by janmedrek** [comment] 2022-03-24 09:49
The solution, for now, would be to add an additional step before the Commerce Mock connects - the test should check whether the Connector Service and its sidecar are deployed. Only after that is done and the service is up and running the test should proceed.

The things to check:
- Deployment
- Pods
- Sidecar
- Service
- Virtual Service
- Gateway

**Comment by pbochynski** [comment] 2022-03-30 09:18
It is failing really often (more than 50% of executions). Sample failures from today:
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d/1509079383694905344
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d/1509049184202788864
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d/1509034084549005312
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d/1508988785566683136

We need immediate actions!

**Comment by koala7659** [comment] 2022-04-01 08:27
We have agreement to solve #13718 first. Removing these unnecessary components and their testing jobs should improve results a lot.

**Comment by jakobmoellersap** [comment] 2022-04-08 15:29
Other Test Fixture Issue (most likely same root cause) tracked in https://github.com/kyma-project/kyma/issues/13873 showing that it also affects `pre-main-control-plane-reconciler-e2e`

**Closed** 2022-04-21 08:44 UTC
Labels: kind/bug, kind/failing-test
