### ISSUE TITLE
pre-main-kyma-skr-eventing is flaky

### ISSUE THREAD

**Issue by FriedrichWilken** [kyma-project/kyma#13976] opened 2022-04-14 07:20 UTC
The prow job [pre-main-kyma-skr-eventing](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-skr-eventing) is flaky. It sometimes [fails](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/13975/pre-main-kyma-skr-eventing/1514250358489092096) with

```
Eventing tests cleanup
Cleaning compass resources
    1) Cleaning: Test resources should be deleted
  0 passing (67ms)
  1 failing
  1) Eventing tests cleanup
       Cleaning: Test resources should be deleted:
     HttpError: HTTP request failed
      at Request._callback (node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:[154](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/13975/pre-main-kyma-skr-eventing/1514250358489092096#1:build-log.txt%3A154)29:36)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at endReadableNT (internal/streams/readable.js:1334:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by mfaizanse** [comment] 2022-04-28 12:53
The  [job run logs](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/13975/pre-main-kyma-skr-eventing/1514250358489092096/build-log.txt) (from where you have reported this error `Cleaning: Test resources should be deleted:`), shows that it failed to provision the SKR cluster and in-return it failed to cleanup.

**Comment by mfaizanse** [comment] 2022-04-28 13:15
Currently the job is failing due to:
```
SKR eventing test
       Provision SKR with ID f7ce2ab6-713f-46b5-82cd-f7d0b6409e05:
     Error: error while provisioning SKR: Error: Error when requesting bearer token from https://oauth2.cp.dev.kyma.cloud.sap/oauth2/token: 503 Service Unavailable
```

**Comment by mfaizanse** [comment] 2022-05-04 09:26
Issue in KEB has been addressed in: https://github.com/kyma-project/control-plane/pull/1655
Fix for fast-integration tests: https://github.com/kyma-project/kyma/pull/14130

**Comment by mfaizanse** [comment] 2022-05-06 13:26
Now failing with error:
```
1) Eventing tests
       with Nats backend
         Testing dashboard: Requests to publisher proxy:
     Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/eventing-test/eventing-test.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

**Comment by mfaizanse** [comment] 2022-05-06 13:26
PR: https://github.com/kyma-project/kyma/pull/14122

**Comment by mfaizanse** [comment] 2022-05-06 13:55
PR: https://github.com/kyma-project/kyma/pull/14229

**Comment by mfaizanse** [comment] 2022-05-09 07:48
Total runs: 2
Green: 2
Red: 0

**Comment by mfaizanse** [comment] 2022-05-10 11:57
Blocked By: https://github.com/kyma-project/kyma/pull/14116.

**Comment by mfaizanse** [comment] 2022-05-23 08:57
Grafana query issue fixed by: https://github.com/kyma-project/kyma/pull/14282

**Comment by mfaizanse** [comment] 2022-05-27 08:23
Currently, the provisioning stage is timing out because of KEB, investigate the issue, also check if we need to update the `overrides` version [here](https://github.com/kyma-project/kyma/blob/5385f03e6e5e2d38aa8ce4951fac7dbc85c03e40/tests/fast-integration/eventing-test/prow/config/skr_config.json#L2)?

**Comment by raypinto** [comment] 2022-06-07 13:07
The provisioning issue was fixed by updating the `overrides` version. This issue is currently blocked by the following error:
```
Error: Error when updating label definition with key scenarios: Error: Error calling Director API: 422 Unprocessable Entity
```
which is a known issue. We will revisit this once the issue is resolved.

**Comment by raypinto** [comment] 2022-06-09 08:21
[The pipeline](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-skr-eventing) is almost green now! Sometimes there are issues with provisioning, where its takes longer to provision an skr instance and times out.

**Closed by raypinto** 2022-06-09 08:21 UTC
Labels: area/eventing
