### ISSUE TITLE
Upgrade pipeline outdated and failing

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#13783] opened 2022-03-30 11:19 UTC
**Description**

The job [kyma-upgrade-gardener-kyma-to-kyma2](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2) is failing regularly and it tests upgrade from Kyma 1.24 -> 2.0. As the migration from 1.24 to 2.0 is already done we should focus on upgrades from 2.0->2.1 and 2.1->main.
Additionally we have a lot of errors to create gardener cluster:
```
2022/03/[29](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1508866730192015360#1:build-log.txt%3A29) 18:00:53 UTC [INFO] ### Provisioning Gardener cluster
2022/03/29 18:00:53 UTC [INFO] Provision cluster: "grd7g0hqt"
- Validating flags
X Provisioning Gardener(Azure) cluster
Error: unable to provision gardener cluster: shoots.core.gardener.cloud "grd7g0hqt" already exists
2022/03/29 18:[30](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1508866730192015360#1:build-log.txt%3A30):54 UTC [INFO] cluster provisioning failed, trying provision new cluster
2022/03/29 18:30:54 UTC [INFO] cleaning damaged cluster first
2022/03/29 18:30:54 UTC [INFO] Deprovision cluster: grd7g0hqt
shoot.core.gardener.cloud/grd7g0hqt annotated
shoot.core.gardener.cloud "grd7g0hqt" deleted
2022/03/29 18:30:54 UTC [INFO] building new cluster name
2022/03/29 18:30:54 UTC [ERROR] AN ERROR OCCURED! Take a look at preceding log entries.
2022/03/29 18:30:54 UTC [INFO] Cleanup
```

**Comment by Sawthis** [comment] 2022-03-31 10:23
Isn't it duplicate of: https://github.com/kyma-project/test-infra/issues/5167 ?

**Comment by varbanv** [comment] 2022-04-28 08:34
Implemented an automated test for latest two versions.

**Closed by varbanv** 2022-04-28 08:34 UTC
Labels: kind/bug, kind/failing-test, release blocker
