### ISSUE TITLE
[CBS] APIRules query fails with under very specific conditions

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/kyma#7988] opened 2020-04-09 13:02 UTC
Query
```
APIRules(namespace: "<any-namespace>", serviceName: "<any-service>") {
  ...
}
```
sometimes (when count of returned rules would be >= 3) returns
```
{
  "errors": [
    {
      "message": "internal system error",
      "path": [
        "APIRules"
      ]
    }
  ],
  "data": null
}
```
while the same query without `serviceName` parameter always works properly.

**Troubleshooting**

Results can be filtered on recipient side, hurting performance.

**Comment by kwiatekus** [comment] 2020-05-08 09:49
Cannot reproduce anymore.
Lets adjust the query in service details code and close

**Comment by kwiatekus** [comment] 2020-05-08 13:05
Still valid.
When fetching API Rules per service (in this [PR](https://github.com/kyma-project/console/pull/1782) ), cbs logs memory dereference error:
```
runtime error: invalid memory address or nil pointer dereference

goroutine 122937 [running]:
runtime/debug.Stack(0x1, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/kyma-project/kyma/components/console-backend-service/vendor/github.com/99designs/gqlgen/graphql.DefaultRecover(0x1c738e0, 0xc0004d4a20, 0x180ea20, 0x2ece0b0, 0x203000, 0x203000)
	/go/src/github.com/kyma-project/kyma/components/console-backend-service/vendor/github.com/99designs/gqlgen/graphql/recovery.go:16 +0xa7
github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema.(*executionContext).FieldMiddleware.func1(0xc0015f8e20, 0x1c738e0, 0xc0004d4a20, 0xc0058ade68)
	/go/src/github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema/schema_gen.go:37219 +0x78
panic(0x180ea20, 0x2ece0b0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/kyma-project/kyma/components/console-backend-service/internal/domain/apigateway.(*Service).List(0xc0010d9060, 0xc003e69710, 0x7, 0xc0015f8fe0, 0x0, 0xc0006d9a30, 0x40b84f, 0xc0002a0350, 0x8, 0x8)
	/go/src/github.com/kyma-project/kyma/components/console-backend-service/internal/domain/apigateway/service.go:43 +0x167
github.com/kyma-project/kyma/components/console-backend-service/internal/domain/apigateway.(*apiRuleResolver).APIRulesQuery(0xc0010d9080, 0x1c738e0, 0xc0004d4a20, 0xc003e69710, 0x7, 0xc0015f8fe0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/kyma-project/kyma/components/console-backend-service/internal/domain/apigateway/resolver.go:52 +0x7c
github.com/kyma-project/kyma/components/console-backend-service/internal/domain.(*queryResolver).APIRules(0xc0002a0350, 0x1c738e0, 0xc0004d4a20, 0xc003e69710, 0x7, 0xc0015f8fe0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/kyma-project/kyma/components/console-backend-service/internal/domain/root_resolver.go:616 +0x8c
github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema.(*executionContext)._Query_APIRules.func2(0x1c738e0, 0xc0004d4a20, 0xc002106320, 0x1, 0xc004710cb0, 0x6c)
	/go/src/github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema/schema_gen.go:25330 +0x1ed
github.com/kyma-project/kyma/components/console-backend-service/internal/authz.NewRBACDirective.func1(0x1c738e0, 0xc0004d4a20, 0x0, 0x0, 0xc0033643a0, 0x1ae8da3, 0x4, 0xc0015f9060, 0xc0015f9070, 0xc0015f9090, ...)
	/go/src/github.com/kyma-project/kyma/components/console-backend-service/internal/authz/rbac.go:40 +0x3aa
github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema.(*executionContext).FieldMiddleware.func2(0x1c738e0, 0xc0004d4a20, 0x30, 0x1931040, 0xc0015f9001, 0xc0004d4b40)
	/go/src/github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema/schema_gen.go:37236 +0x186
github.com/kyma-project/kyma/components/console-backend-service/vendor/github.com/99designs/gqlgen/graphql.DefaultResolverMiddleware(0x1c738e0, 0xc0004d4a20, 0xc0004d4b40, 0x0, 0xc0004d4a20, 0xc000716e68, 0xc000716e28)
	/go/src/github.com/kyma-project/kyma/components/console-backend-service/vendor/github.com/99designs/gqlgen/graphql/context.go:41 +0x3a
github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema.(*executionContext).FieldMiddleware(0xc0015f8e20, 0x1c738e0, 0xc0004d4a20, 0x0, 0x0, 0xc0033643a0, 0x0, 0x0)
	/go/src/github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema/schema_gen.go:37241 +0x2c0
github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema.(*executionContext)._Query_APIRules(0xc0015f8e20, 0x1c738e0, 0xc0004d48d0, 0xc000ddf000, 0xc00313f740, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema/schema_gen.go:25328 +0x32e
github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema.(*executionContext)._Query.func19(0xc0015f8e20, 0xc0015f8f20, 0xc0004d4900, 0xc003e6973b, 0xc003e69740, 0x0, 0xc000ddf000, 0xc00313f740, 0x4, 0x4)
	/go/src/github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema/schema_gen.go:24073 +0x79
created by github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema.(*executionContext)._Query
	/go/src/github.com/kyma-project/kyma/components/console-backend-service/internal/gqlschema/schema_gen.go:24072 +0xc38
```

**Comment by magicmatatjahu** [comment] 2020-07-09 06:53
Fixed by https://github.com/kyma-project/kyma/pull/8900

**Closed by magicmatatjahu** 2020-07-09 06:53 UTC
Labels: area/console, bug
