### ISSUE TITLE
Extend gardener integration suite with upgrade tests

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/kyma#8308] opened 2020-04-30 05:22 UTC
**Description**
ATM kyma gardener integration test suite does not include upgrade test.

**Reasons**
To automate verification process of kyma running on gardener.
 

**Attachments**

**Comment by a-thaler** [comment] 2020-05-08 13:17
Duplicate of https://github.com/kyma-project/test-infra/issues/1977

**Closed by a-thaler** 2020-05-08 13:17 UTC
Labels: area/quality, duplicate, enhancement
