### ISSUE TITLE
Support Metadata service REST API in the API-gateway

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#4240] opened 2019-05-28 07:56 UTC
**Description**
We need to support Metadata API for some time.

**AC**
- [ ] Metadata REST API is supported on comapass gateway, and internally calls our new graphQL API
- [x] Add diagram how the request forwarding from REST API to GraphQL layer works @crabtree PR: kyma-incubator/compass#42
- [x] Copy existing models from application-registry kyma component @crabtree PR: kyma-incubator/compass#88
- [ ] Implementation on gateway side for REST and proxying to GraphQL

OpenAPI spec:  https://github.com/kyma-project/kyma/blob/master/components/application-registry/docs/api/api.yaml

**Comment by pkosiec** [comment] 2020-01-14 12:48
Closing it as a duplicate of https://github.com/kyma-incubator/compass/issues/620

**Closed by pkosiec** 2020-01-14 12:48 UTC
Labels: area/application-connector, enhancement
