### ISSUE TITLE
Function pod does not receive specified labels from Function definition

### ISSUE THREAD

**Issue by ArthurPerry** [kyma-project/kyma#9515] opened 2020-09-23 15:52 UTC
**Description**

Kyma version 1.15.1
Running in SAP Cloud Platform, Kyma runtime

I specify a label when creating a Function via the Kyma console. i.e. `app=mylambda`.  When the function is deployed, the label is applied to the `build` pod, but not to the runtime pod.  

Therefore I can't use the label to, for example, view logs for any pod related to the function:
`kubectl logs -n mynamespace -l app=mylambda`

**Expected result**

I expect the label specified in the console to be applied to any pod generated for the function, be it a build job, pod, replica, etc.

**Actual result**

The label is only applied to the build Job.

**Steps to reproduce**

Create function via Kyma console
Specify a label i.e. `app=mylambda`

**Troubleshooting**

checked on multiple functions.

**Comment by aerfio** [comment] 2020-09-24 09:37
Hi @ArthurPerry, unfortunately it's one of those weird situations when I need to tell you _it's not a bug, it's a feature_ 😆 . 
Unfortunately due to some problems we had with servicebindingusage CR in Kyma internally we had to disable automatic propagation of labels for function pods, and we implemented mechanism to propagate them programatically -> see https://kyma-project.io/docs/components/serverless#custom-resource-function-custom-resource-properties `spec.labels`. Currently there's no way to set those values from UI, as they are used internally and we'd like to prevent users from accidently unbinding SBU's, but you can set those via kubectl. If you think this is really important issue please comment, maybe we'd need to rethink that approach

**Comment by aerfio** [comment] 2020-10-05 08:51
I'll close this for now, feel free to reopen it anytime to discuss it further

**Comment by majakurcius** [comment] 2020-11-02 13:28
Hi! 
My two cents:

I know this functionality where the Pod with the Function got the **app** (or then the **function**) label worked before the rework of Serverless. 
The documentation was updated in [this commit](https://github.com/kyma-project/kyma/commit/1d1a31d449411f8658e3f980aefa35d6860013d2#diff-e1c36539f2209da28c147b1071e2d06f03523a4e37a3363d965ebbe7bde7ea5d) as part of the rework, but it didn't take into account the changes to labeling.

We used this functionality in the [tutorial on triggering a Function (then lambda) with events](https://kyma-project.io/docs/1.15/components/application-connector#tutorials-trigger-a-function-with-events) (previously [this one](https://github.com/kyma-project/kyma/blob/release-1.11/docs/application-connector/08-05-trigger-lambda-with-event.md).

In the tutorial, we used the label `function={LAMBDA_NAME}`, which was modified in the commit mentioned above to `app={FUNCTION_NAME}`, to fetch the Function's logs (step 8) with this command: 
```bash
kubectl -n $NAMESPACE logs "$(kubectl -n $NAMESPACE get po -l function=my-events-lambda -o jsonpath='{.items[0].metadata.name}')" -c my-events-lambda | grep -E "Response acquired successfully! Uuid: [a-f0-9-]+"
```

This no longer works.

Right now the situation is that when you create a Function:
- two Pods are created, let’s say `my-function-build-axcnr-83kec` (which builds the Docker image of the Function) and `my-function-km98n-3bfbb89b97-qhd54` (which contains and executes the Function image)
- both Pods get the `serverless.kyma-project.io/function-name=my-function` label
- it's the `my-function-build-axcnr-83kec` Pod that gets the `app=my-function` label now (and not the Pod that actually contains the image and the Function's logs)

You can't use the `serverless.kyma-project.io/function-name={MY_FUNCTION_NAME}` label to fetch the logs because the Pods' containers don't match. 

The workaround is to use negation, like this: 
```bash
kubectl -n $NAMESPACE logs "$(kubectl -n $NAMESPACE get po -l app!={MY_FUNCTION_NAME},serverless.kyma-project.io/function-name={MY_FUNCTION_NAME} -o jsonpath='{.items[0].metadata.name}')" -c function | grep -E "Response acquired successfully! Uuid: [a-f0-9-]+"
```

However, it's a bit hacky and it only HAPPENS to work, but there's no contract for it.

**Comment by kwiatekus** [comment] 2021-01-29 11:03
Currently function pod has labels that are managed via service binding mechanism.
We see the point, but unfortunately we cannot change it in the current setup as this would impose breaking changes.
We plan to refactor function controller and label management will be one of the things we want to improve.

Please  take a look at the workaround proposed by @majakurcius 
Closing

**Closed by kwiatekus** 2021-01-29 11:03 UTC
Labels: area/serverless, bug
