### ISSUE TITLE
test-core-core-console-backend-service fails

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#3508] opened 2019-04-02 12:22 UTC
**Description**
test-core-core-console-backend-service keeps failing

Following runs are:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1113029419691151360

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by sayanh** [comment] 2019-04-02 12:26
Occurred once. Closing it for now and will monitor.

**Comment by sayanh** [comment] 2019-04-02 15:03
Reopening:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1113064905797275648

**Comment by mmitoraj** [comment] 2019-04-03 08:09
I'm closing this issue as this is a duplicate of #3201.

**Closed by mmitoraj** 2019-04-03 08:09 UTC
Labels: test-failing
