### ISSUE TITLE
post-master-kyma-gke-upgrade jobs are failing consistently 

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#6031] opened 2019-10-16 10:56 UTC
post-master-kyma-gke-upgrade jobs have been failing consistently, due to different error:

1st Error:
```
{“level”:“info”,“log”:{“message”:“[CreateResources: LambdaFunctionUpgradeTest] Starting execution”,“taskID”:“9fb01d19-6a4c-4390-96e2-2e4b92e114d7”,“time”:“2019-10-16T09:34:22.324Z”}}
{“level”:“info”,“log”:{“message”:“FunctionUpgradeTest creating resources”,“taskID”:“9fb01d19-6a4c-4390-96e2-2e4b92e114d7",“time”:“2019-10-16T09:34:22.33Z”}}
{“level”:“error”,“log”:{“message”:“[CreateResources: LambdaFunctionUpgradeTest] End with error [start time: Wed, 16 Oct 2019 09:34:22 UTC, duration: 57.161523ms]: could not create api.: Api.gateway.kyma-project.io \“hello\” is invalid: []: Invalid value: map[string]interface {}{\“kind\“:\“Api\“, \“apiVersion\“:\“gateway.kyma-project.io/v1alpha2\“, \“metadata\“:map[string]interface {}{\“name\“:\“hello\“, \“creationTimestamp\“:\“2019-10-16T09:34:22Z\“, \“namespace\“:\“lambdafunctionupgradetest\“, \“generation\“:1, \“uid\“:\“22a189a4-eff8-11e9-a0c6-42010aa40293\“}, \“spec\“:map[string]interface {}{\“authenticationEnabled\“:false, \“authentication\“:[]interface {}{}, \“service\“:map[string]interface {}{\“name\“:\“hello\“, \“port\“:8080}, \“hostname\“:\“hello-lambdafunctionupgradetest.\“}, \“status\“:map[string]interface {}{\“authenticationStatus\“:map[string]interface {}{\“resource\“:map[string]interface {}{}, \“code\“:0}, \“virtualServiceStatus\“:map[string]interface {}{\“resource\“:map[string]interface {}{}, \“code\“:0}}}: validation failure list:\nspec.hostname in body should match ‘^([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]{0,62}[A-Za-z0-9])(\\.gke-upgrade-commit-a8ed2afb-1w73lt1aax\\.a\\.build\\.kyma-project\\.io)?$’“,”taskID”:“9fb01d19-6a4c-4390-96e2-2e4b92e114d7”,“time”:“2019-10-16T09:34:22.387Z”}}
```

2nd Error
```
----------
service-catalog:
 Helm upgrade error: rpc error: code = Unknown desc = Job failed: BackoffLimitExceeded
service-catalog:
 Helm upgrade error: rpc error: code = Unknown desc = persistentvolumeclaims “service-catalog-catalog-migration-storage” already exists
```

Both the errors were encountered in different jobs

**Comment by adamwalach** [comment] 2019-10-16 11:12
As for the second error - this is caused by interruption of migration process.
When the upgrade process is triggered again the PVC (which in prod environment could potentially contain important data so we can't just remove it) can't be created again.
We created [PR](https://github.com/kubernetes-sigs/service-catalog/pull/2730) to service-catalog to make the migration process more failure-resistant. 
We suspect that the core issue is api-server not responding correctly. Retrying requests on failure should fix that.

**Comment by sayanh** [comment] 2019-10-16 14:51
For `FunctionUpgradeTest` failure in https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1184395164831977473/build-log.txt
My observations are follows:
- This test depends on domain which comes from the `core` release variables in `global.ingress.domainName`. This was empty here.
- I see `ApiControllerUpgradeTest` is failing as well which can be due to the same reason.

**Comment by adamwalach** [comment] 2019-10-18 08:24
We merged fix for the second issue  https://github.com/kubernetes-sigs/service-catalog/pull/2730

**Closed** 2019-10-22 12:13 UTC
Labels: area/serverless, area/service-catalog, priority/critical, test-failing
