### ISSUE TITLE
Service Catalog does not retry failed provisioning

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#7288] opened 2020-02-20 21:07 UTC
**Description**

This is the code line where the provisioning of the ServiceInstance fails: https://github.com/kyma-project/kyma/blob/2bed6bcf03b35e024d73d1a4c2534935faeeebfe/components/application-broker/internal/broker/provision.go#L240

**How to reproduce:**
Before creating the ServiceInstance: <- cluster is in this state atm
```bash
kubectl scale --replicas=0 -n kyma-system deployment event-sources-controller-manager
kubectl delete channels.messaging.knative.dev -n kyma-integration nachtmaar
```

**After creating the ServiceInstance and the first provision request fails:**
```bash
kubectl scale --replicas=1 -n kyma-system deployment event-sources-controller-manager
kubectl get channels.messaging.knative.dev -n kyma-integration nachtmaar # check channel has been recreated
```

As discussed in the call: I see this message in service catalog `Not processing event because status showed there is no work to do`

**Comment by nachtmaar** [comment] 2020-02-21 15:34
Related to this issue: https://github.com/kyma-project/kyma/issues/7193

**Comment by ksputo** [comment] 2020-03-18 23:29
To sum up the investigation:
- service catalog's behaviour is like this by design, not a bug - see [service-catalog/PR-2520](https://github.com/kubernetes-sigs/service-catalog/pull/2520)
- Platform (service catalog) performs [Orphan Mitigation](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#orphan-mitigation) (which is basically cleaning up all the resources from the failed provisioning process) when it gets `status: failed` in response from polling for last operation. 
- It should be broker who performs retries after failed provisioning, not the platform, which was also mentioned [here](https://github.com/kyma-project/kyma/issues/7193#issuecomment-585229973). In this particular case the retries could be added when asking for kubernetes custom resources.
- The problem with current OSB API contract is that we can't really tell if the provisioning error was permanent or temporary - there is a agreement for covering those issues in OSB API v3 (and probably then changes in service catalog will be introduced)

Some context about the history of service catalog behaviour:
- [30.04.2018 - service catalog performing endless loop of retries when provisioning fails](https://github.com/kubernetes-sigs/service-catalog/issues/2006)
- [09.05.2018 - discussed about exponential delay between every next provisioning retry](https://github.com/kubernetes-sigs/service-catalog/issues/2025)
- [05.12.2018 - agreed on current behaviour, not retrying provisioning when last operation failed](https://github.com/kubernetes-sigs/service-catalog/pull/2520)

Closing for now.

**Closed by ksputo** 2020-03-18 23:29 UTC
Labels: area/service-catalog
