### ISSUE TITLE
Failing to create Remote Environments

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#1652] opened 2018-11-14 09:22 UTC
**Description**
Dear Colleagues,

Remote environments created via the console are not visible in the ui.

Cheers

Andreas

**Expected result**

Remote Environments are visible in the console

**Actual result**

instead only pre-delivered ec-default and hmc-default environments are visible

**Steps to reproduce**

go to remote environments and create environment. 

**Troubleshooting**

```kubectl delete pod -n kyma-system -l app=ui-api```

**Comment by akrausesap** [comment] 2018-11-14 09:29
```kubectl delete pod -n kyma-system -l app=ui-api``` is a workaround

**Comment by Disper** [comment] 2018-11-19 10:14
We couldn't reproduce it. Please decide if it's still actual.

**Comment by Disper** [comment] 2018-11-19 12:44
We couldn't reproduce it. 
@akrausesap Please decide if it's still actual. If it is, could you attach Remote environment CRD?
Any additional tips for reproducing are also welcome.

**Comment by akrausesap** [comment] 2018-11-19 13:00
@Disper: Just go to the UI and create it from there. I have not used a CRD. Let me know if you still can't reproduce like that

**Comment by Szymongib** [comment] 2018-11-19 13:55
@akrausesap We have tried both creating Remote Environment from the UI as well as from the terminal and both methods worked fine. Could you please provide some more information about Kyma version and cluster configuration you used?

**Comment by akrausesap** [comment] 2018-11-19 15:15
@Disper : It is 0.5 rc1. However now I can't get the bug either anymore. However it existed for me and a colleague. Strange

**Comment by Disper** [comment] 2018-11-24 10:36
We're closing it for now as we were not able to reproduce it. 
Please contact us if the problem is occurring.

**Closed by Disper** 2018-11-24 10:36 UTC
Labels: area/application-connector, bug
