### ISSUE TITLE
Natss-streaming does not install on Gardener cluster

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/kyma#6876] opened 2020-01-15 13:30 UTC
**Description**

Natss-streaming does not install on the Gardener clusters. The `natss-streaming-pre-upgrade-job` is failing with the following message:
```
Error from server (Forbidden): statefulsets.apps "nats-streaming" is forbidden: User "system:serviceaccount:natss:nats-streaming-hooks" cannot delete resource "statefulsets" in API group "apps" in the namespace "natss": RBAC: clusterrole.rbac.authorization.k8s.io "kyma-admin" not found
```

The issue occurs in version `1.9.0`.

**Expected result**

Kyma can be installed properly on the Gardener cluster.

**Actual result**

Kyma installation keeps failing on `natss-streaming` component.

**Steps to reproduce**

Install Kyma 1.9.0 on the Gardener cluster.

**Troubleshooting**

**Comment by nachtmaar** [comment] 2020-01-28 13:24
Seems to be the same issue as this: https://github.com/kyma-project/kyma/issues/6950

**Comment by nachtmaar** [comment] 2020-01-29 11:54
@Szymongib is this behaviour reproducable for you?

**Comment by nachtmaar** [comment] 2020-01-30 12:04
Installing latest with `kyma install --source latest` works. Didn't check with 1.9 yet.

**Comment by nachtmaar** [comment] 2020-01-30 12:23
1.9 also works. I used the following commands:

```bash
$ kyma provision gardener -v --target-provider azure --secret tunas-secret --name k65903 --project kymatunas --credentials ~/secrets/gardener/garden-kymatunas/shoot-kubeconfig.yaml --region westeurope -t Standard_D2_v3 --disk-size 35 --disk-type=Standard_LRS --extra vnetcidr=10.250.0.0/19 --nodes 8
$ kyma install --source 1.9.0
```

@Szymongib can you show me a cluster where it failed and how you are able to reproduce it? Otherwise I think it was a temporary problem.

**Comment by Abd4llA** [comment] 2020-02-10 09:16
Closing, seems to be fixed. Can be reopened if it came up again.

**Closed by Abd4llA** 2020-02-10 09:16 UTC
Labels: area/eventing, area/installation, bug
