### ISSUE TITLE
i get a error says  Forbidden port

### ISSUE THREAD

**Issue by lixiaofei123** [kyma-project/kyma#4207] opened 2019-05-24 11:18 UTC
hello, when I try to install kyma loally follow by [this link](https://kyma-project.io/docs/root/kyma/#installation-install-kyma-locally)  ,I get a error says **Forbidden port**  I tried it again several times, but still didn't solve it.What should I do to avoid this problem? I tried to solve this problem using Google, but it didn't give me a good suggestion. What should I do??

**Description**

a aprt of error log

```
Unable to connect to the server: Forbidden port
Keep calm, there are 15 possibilities and so far it is attempt number 12
Unable to connect to the server: Forbidden port
Keep calm, there are 15 possibilities and so far it is attempt number 13
Unable to connect to the server: Forbidden port
Keep calm, there are 15 possibilities and so far it is attempt number 14
Unable to connect to the server: Forbidden port
Keep calm, there are 15 possibilities and so far it is attempt number 15
Unable to connect to the server: Forbidden port
Minikube is up
✅  metrics-server was successfully enabled
Minikube IP address: 192.168.99.122
Adding apiserver.kyma.local console.kyma.local catalog.kyma.local instances.kyma.local brokers.kyma.local dex.kyma.local docs.kyma.local add-ons.kyma.local lambdas-ui.kyma.local console-backend.kyma.local minio.kyma.local jaeger.kyma.local grafana.kyma.local log-ui.kyma.local loki.kyma.local configurations-generator.kyma.local gateway.kyma.local connector-service.kyma.local oauth2.kyma.local oauth2-admin.kyma.local oauth2-login-consent.kyma.local oathkeeper-proxy.kyma.local oathkeeper-api-server.kyma.local kiali.kyma.local to /etc/hosts on Minikube
127.0.0.1 apiserver.kyma.local console.kyma.local catalog.kyma.local instances.kyma.local brokers.kyma.local dex.kyma.local docs.kyma.local add-ons.kyma.local lambdas-ui.kyma.local console-backend.kyma.local minio.kyma.local jaeger.kyma.local grafana.kyma.local log-ui.kyma.local loki.kyma.local configurations-generator.kyma.local gateway.kyma.local connector-service.kyma.local oauth2.kyma.local oauth2-admin.kyma.local oauth2-login-consent.kyma.local oathkeeper-proxy.kyma.local oathkeeper-api-server.kyma.local kiali.kyma.local
[sudo] lixf 的密码： 
Adding apiserver.kyma.local console.kyma.local catalog.kyma.local instances.kyma.local brokers.kyma.local dex.kyma.local docs.kyma.local add-ons.kyma.local lambdas-ui.kyma.local console-backend.kyma.local minio.kyma.local jaeger.kyma.local grafana.kyma.local log-ui.kyma.local loki.kyma.local configurations-generator.kyma.local gateway.kyma.local connector-service.kyma.local oauth2.kyma.local oauth2-admin.kyma.local oauth2-login-consent.kyma.local oathkeeper-proxy.kyma.local oathkeeper-api-server.kyma.local kiali.kyma.local to /etc/hosts on localhost
Domain added to /etc/hosts
fs.inotify.max_user_instances = 524288
fs.inotify.max_user_instances is increased
error: unable to recognize "/home/lixf/kyma/installation/scripts/../resources/default-sa-rbac-role.yaml": Get https://192.168.99.122:8443/api?timeout=32s: Forbidden port
```

**Expected result**

I should install kyma successful

**Actual result**

it says "Forbidden port"

**Steps to reproduce**

and some other information

**kubectl v1.13.0**
**minikube  v1.1.0**
**os Ubuntu 18.04.1 4.18.0-21-generic**

**Comment by Demonsthere** [comment] 2019-05-28 07:34
Hi there, 
It seems something is already present at a port that minikube would like to use. Can you check used ports on your machine? (`lsof`, or `netstat`).
On the other hand, this issue may be caused by using `HTTP/S_PROXY`, are you using it by any chance?

**Comment by tomekpapiernik** [comment] 2019-05-28 07:44
Hey @lixiaofei123 , if you need any help with Kyma you can always talk to us directly on Slack. You can ask questions like this one on our [#installation](https://kyma-community.slack.com/messages/CD2HJ0E78) channel :)

**Comment by lixiaofei123** [comment] 2019-05-31 08:20
@Demonsthere thank! it help me.I using proxy to visit google because i am in china. I delete os-environment https_proxy,and it works!!

**Comment by lixiaofei123** [comment] 2019-05-31 08:27
@tomekpapiernik  I try using slack,but I can't sign it,and this channel ask me to get an invitation from workspace administrator,

**Comment by tomekpapiernik** [comment] 2019-05-31 10:04
@lixiaofei123 thanks for your message! I'm glad you got it working :) I'm closing the issue now.
Please join our Slack workspace through the kyma-project.io website. Click this icon:
![image](https://user-images.githubusercontent.com/29116492/58698750-3511b300-839c-11e9-90f4-d9fa085843d5.png)
See you on Slack!

**Closed** 2019-05-31 10:06 UTC
Labels: area/installation, question
