### ISSUE TITLE
nodejs function runtimes are ignoring all bodyparsers except of raw

### ISSUE THREAD

**Issue by paschdan** [kyma-project/kyma#15768] opened 2022-10-10 15:22 UTC
Hi, i have tested this a little bit and the issue was already present in kubless afaik. 

when the body parsers are used in this order (with the current podyParserOptions), then the raw parser will always win and the other parsers are basically ignored.

we have already implemented against the issue, by parsing `event.extensions.request.body` so a change in those lines will most likely break already defined functions.

basically every request (except of multipart), according to 

https://github.com/kyma-project/kyma/blob/c23dcfd024c9c8d9191885465742d79ea53bc54d/components/function-runtimes/nodejs12/kubeless/kubeless_rt/kubeless.js#L35-L38

will be parsed as raw, because of the ordering here:

https://github.com/kyma-project/kyma/blob/c23dcfd024c9c8d9191885465742d79ea53bc54d/components/function-runtimes/nodejs16/server.js#L64-L66

https://github.com/kyma-project/kyma/blob/c23dcfd024c9c8d9191885465742d79ea53bc54d/components/function-runtimes/nodejs14/kubeless/kubeless_rt/kubeless.js#L40-L42

https://github.com/kyma-project/kyma/blob/c23dcfd024c9c8d9191885465742d79ea53bc54d/components/function-runtimes/nodejs12/kubeless/kubeless_rt/kubeless.js#L39-L41

**Comment by kwiatekus** [comment] 2022-12-06 14:20
@paschdan We have fixed the problem.
It looks like the body parsers were misconfigured - the order doesn't matter that much.

Now, the raw parser will be applied as a fallback.. a specialised parser will be used based on the content-type request header

https://github.com/kyma-project/kyma/pull/16259

The fix will be part of 2.10

**Closed by kwiatekus** 2022-12-06 14:20 UTC
Labels: kind/bug, area/serverless

**Comment by Disper** [comment] 2022-12-16 11:30
Hello @paschdan,
I hope that this issue was resolved according to your expectations. 
When creating future issues, could you follow our issue templates? We had done some small internal post-mortem to understand why it took so long and it happened that we struggled with reproducing this one. 

Having information from sections like `steps to reproduce` of our [Bug Issue Template](https://github.com/kyma-project/kyma/issues/new?assignees=&labels=&template=bug-report.md) will speed up our future investigations so we will be grateful if you will use them in the new issues you'll create.

Cheers,
Michał

**Comment by paschdan** [comment] 2023-03-17 23:50
i think now this is a breaking change:

now it is handling the incoming data correctly (it tries to parse it to the correct format, e.g. data will be json if the incoming request is either a json or a form-data. 

but this will break our current workaround, where we did the following:

```javascript
const jsonData = JSON.parse(event.extensions.request.body);
```

so i think this should be treated as a breaking change then?
