### ISSUE TITLE
Kyma CLI minikube installation fails

### ISSUE THREAD

**Issue by p4p4** [kyma-project/kyma#6221] opened 2019-11-06 08:30 UTC
**Description**
When trying to install kyma in minikube with kyma-cli I get the following error
`error: unable to recognize "STDIN": no matches for kind "Installation" in version "installer.kyma-project.io/v1alpha1"`,

System: Ubuntu 19.04
Minikube: v1.3.1
Kyma CLI version: 1.7.0
Kyma cluster version: 1.7.0

Kubectl version:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Helm version: v2.10.0

**Expected result**

Kyma installation succeeds :-)

**Actual result**

installation fails with error:
```
➜  ~ kyma install                
- Configuration validated
  Installing Kyma in version '1.7.0'. 
- Installation source checked
- Tiller deployed
- Cluster info read
- Installation files loaded
X Deploying Kyma Installer
Error: Executing kubectl 'kubectl apply -f -[map[apiVersion:v1 kind:Namespace metadata:map[labels:map[istio-injection:disabled kyma-project.io/installation:] name:kyma-installer]] map[apiVersion:v1 kind:LimitRange metadata:map[labels:map[kyma-project.io/installation:] name:kyma-default namespace:kyma-installer] spec:map[limits:[map[default:map[memory:96Mi] defaultRequest:map[memory:32Mi] max:map[memory:1024Mi] type:Container]]]] map[apiVersion:apiextensions.k8s.io/v1beta1 kind:CustomResourceDefinition metadata:map[labels:map[kyma-project.io/installation:] name:installations.installer.kyma-project.io] spec:map[group:installer.kyma-project.io names:map[kind:Installation plural:installations shortNames:[installation] singular:installation] scope:Namespaced version:v1alpha1]] map[apiVersion:apiextensions.k8s.io/v1beta1 kind:CustomResourceDefinition metadata:map[labels:map[kyma-project.io/installation:] name:releases.release.kyma-project.io] spec:map[group:release.kyma-project.io names:map[kind:Release plural:releases shortNames:[release] singular:release] scope:Namespaced version:v1alpha1]] map[apiVersion:v1 kind:ServiceAccount metadata:map[name:helm-certs-job-sa namespace:kyma-installer]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:RoleBinding metadata:map[name:helm-certs-rolebinding namespace:kube-system] roleRef:map[apiGroup:rbac.authorization.k8s.io kind:Role name:helm-certs-getter] subjects:[map[kind:ServiceAccount name:helm-certs-job-sa namespace:kyma-installer]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:RoleBinding metadata:map[name:helm-certs-rolebinding namespace:kyma-installer] roleRef:map[apiGroup:rbac.authorization.k8s.io kind:Role name:helm-certs-setter] subjects:[map[kind:ServiceAccount name:helm-certs-job-sa namespace:kyma-installer]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:Role metadata:map[name:helm-certs-getter namespace:kube-system] rules:[map[apiGroups:[] resources:[secrets] verbs:[get list]]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:Role metadata:map[name:helm-certs-setter namespace:kyma-installer] rules:[map[apiGroups:[] resources:[secrets] verbs:[get list create patch]]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:ClusterRole metadata:map[name:all-psp] rules:[map[apiGroups:[extensions] resources:[podsecuritypolicies] verbs:[use]]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:ClusterRoleBinding metadata:map[name:all-psp] roleRef:map[apiGroup:rbac.authorization.k8s.io kind:ClusterRole name:all-psp] subjects:[map[kind:ServiceAccount name:helm-certs-job-sa namespace:kyma-installer]]] map[apiVersion:batch/v1 kind:Job metadata:map[labels:map[kyma-project.io/installation:] name:helm-certs-job namespace:kyma-installer] spec:map[template:map[metadata:map[annotations:map[sidecar.istio.io/inject:“false”] name:helm-certs-job namespace:kyma-installer] spec:map[containers:[map[command:[bash -c WORKING_DIR="/tmp/certs"
mkdir -p "${WORKING_DIR}"

cat <<EOF > "${WORKING_DIR}/openssl.cnf"
[ req ]
#default_bits   = 2048
#default_md   = sha256
#default_keyfile  = privkey.pem
distinguished_name  = req_distinguished_name
attributes    = req_attributes

[ req_distinguished_name ]
countryName     = Country Name (2 letter code)
countryName_min     = 2
countryName_max     = 2
stateOrProvinceName   = State or Province Name (full name)
localityName      = Locality Name (eg, city)
0.organizationName    = Organization Name (eg, company)
organizationalUnitName    = Organizational Unit Name (eg, section)
commonName      = Common Name (eg, fully qualified host name)
commonName_max      = 64
emailAddress      = Email Address
emailAddress_max    = 64

[ req_attributes ]
challengePassword   = A challenge password
challengePassword_min   = 4
challengePassword_max   = 20
[ v3_ca ]
basicConstraints = critical,CA:TRUE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
EOF

echo "---> Get Tiller CA"
if [[ $(kubectl get -n kube-system secret tiller-secret) ]] ; then
  kubectl get -n kube-system secret tiller-secret -o jsonpath="{.data['ca\.crt']}" | base64 --decode > "${WORKING_DIR}/ca.crt"
  kubectl get -n kube-system secret tiller-secret -o jsonpath="{.data['ca\.key']}" | base64 --decode > "${WORKING_DIR}/ca.key"
else
  echo "Secret: tiller-secret does not exists!"
  exit 1
fi

echo "---> Generate Helm key"
openssl genrsa -out "${WORKING_DIR}/helm.key.pem" 4096
openssl req -key "${WORKING_DIR}/helm.key.pem" -new -sha256 -out "${WORKING_DIR}/helm.csr.pem" -subj "/C=PL/ST=Gliwice/L=Gliwice/O=Helm Client/CN=helm-client"
openssl x509 -req -CA "${WORKING_DIR}/ca.crt" -CAkey "${WORKING_DIR}/ca.key" -CAcreateserial -in "${WORKING_DIR}/helm.csr.pem" -out "${WORKING_DIR}/helm.cert.pem" -days 365

echo "---> Create secrets in k8s"
COMBO_YAML=$(cat << EOF
---
apiVersion: v1
data:
  global.helm.ca.crt: "$(base64 "${WORKING_DIR}/ca.crt" | tr -d '\n')"
  global.helm.tls.crt: "$(base64 ${WORKING_DIR}/helm.cert.pem | tr -d '\n')"
  global.helm.tls.key: "$(base64 ${WORKING_DIR}/helm.key.pem | tr -d '\n')"
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    installer: overrides
    kyma-project.io/installation: ""
  name: helm-secret
  namespace: kyma-installer
type: Opaque
EOF
)

echo "${COMBO_YAML}" | kubectl create -f -
] image:eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20190325-ff66a3a name:certhelper]] restartPolicy:OnFailure serviceAccountName:helm-certs-job-sa]]]] map[apiVersion:v1 kind:ServiceAccount metadata:map[labels:map[kyma-project.io/installation:] name:kyma-installer namespace:kyma-installer]] map[apiVersion:extensions/v1beta1 kind:Deployment metadata:map[labels:map[kyma-project.io/installation:] name:kyma-installer namespace:kyma-installer] spec:map[template:map[metadata:map[labels:map[name:kyma-installer]] spec:map[containers:[map[args:[-tillerTLSInsecureSkipVerify=true] image:eu.gcr.io/kyma-project/kyma-installer:1.7.0 imagePullPolicy:IfNotPresent name:kyma-installer-container volumeMounts:[map[mountPath:/etc/certs name:helm-certs readOnly:%!s(bool=true)]]]] serviceAccountName:kyma-installer volumes:[map[name:helm-certs secret:map[items:[map[key:global.helm.tls.crt path:tls.crt] map[key:global.helm.tls.key path:tls.key]] secretName:helm-secret]]]]]]] map[apiVersion:rbac.authorization.k8s.io/v1beta1 kind:ClusterRole metadata:map[labels:map[kyma-project.io/installation:] name:kyma-installer-reader] rules:[map[apiGroups:[*] resources:[*] verbs:[*]]]] map[apiVersion:rbac.authorization.k8s.io/v1beta1 kind:ClusterRoleBinding metadata:map[labels:map[kyma-project.io/installation:] name:kyma-installer] roleRef:map[apiGroup:rbac.authorization.k8s.io kind:ClusterRole name:kyma-installer-reader] subjects:[map[kind:ServiceAccount name:kyma-installer namespace:kyma-installer]]] map[apiVersion:v1 data:map[global.applicationConnectorCa: global.applicationConnectorCaKey:] kind:Secret metadata:map[labels:map[installer:overrides kyma-project.io/installation:] name:application-connector-certificate-overrides namespace:kyma-installer] type:Opaque] map[apiVersion:v1 data:map[global.tlsCrt:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU4RENDQXRpZ0F3SUJBZ0lKQUpBKzlrQzZZZnZlTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURDb3VhM2x0WVM1c2IyTmhiREFlRncweE9EQTNNVGd3T0RNNE1UTmFGdzB5T0RBM01UVXdPRE00TVROYQpNQmN4RlRBVEJnTlZCQU1NRENvdWEzbHRZUzVzYjJOaGJEQ0NBaUl3RFFZSktvWklodmNOQVFFQkJRQURnZ0lQCkFEQ0NBZ29DZ2dJQkFPZ05XbVROOU1ranlrUjdvQ0JGSFVqL01EcWh5bml3NEJITGo4ZTdDTFV5dFdwVHZXTkoKU1FiaFZDK3c5NkhHbU50MHZGUTR4OExUa3NNUmorcVZrdkcwKzBDTE1WQm14UjBVdnpZR09QRVRKREtsNTZkcQppMEM1Y2dnU3dkNjcveWxRZmQxc3FEVVBHM0pVZlNOSFFRWSs1SkUwaUpjZXhCQ3cvS200UXlUQXB0aEwzdEgxCm1ZRFBBQ0hUdVpsbGc2RVN4Z2RKY20rVmg5UkRvbWlON250ZjBZVG1xV1VIZXhZUkUrcTFGY0VhUHg5L2Q5QUwKZWd1WXZHTkduMVA4K1F3ZE5DKzVaMEVGa1EyS3RtalRBR09La2xJUG5NQkZubXhGSEtNZzNTa3RkYzYzSU5TNwpjSDM3dDNjb2l4N09HcDllcnRvSFZ5K2U5KzdiYnI3Z0lhWHNORVZUcjRGWXJIMlNPeHI1MjVRQUpHTys1dllQCkNYSlJJdXFNZWU3ZTg3aDRIU3JFVVdWTnhOdElBR1ZNYlRtV2F6aDJsSEFoazJjZVIzUkRaQzB3NGFOd3NRU1UKZE1yMmFCaUFobmFNSG40YnZIZnd1OHFRcjF5aVRUNG00SkltRkZTNDN2bGNETDZmVUJnNnF0U2p6QjF0WTFjTwp2Mnl1QXQzR1lKSENVMFd4R1ZEQk80T0ZncEc3aE5SRHoyRzVFMXQvRWU2VDUxdys2K295eXhib01pK09kVWdNCnBZOGlzcDdBTWhtdlZFOUdtNUhwQkpBRjYvcmE1WUNnNDh1SWtybkdZbm85eVNKcGhLU0JsMFRML01PNVFRaUoKb0hFNnV5ZkJXQjlZZ1NBdDl0MjJqU3FSWkpSdEtrbHB6bFJIRkROWTRwZlRraXlPSlFXYlM4RXJBZ01CQUFHagpQekE5TUFrR0ExVWRFd1FDTUFBd0N3WURWUjBQQkFRREFnWGdNQ01HQTFVZEVRUWNNQnFDQ210NWJXRXViRzlqCllXeUNEQ291YTNsdFlTNXNiMk5oYkRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQUlYYTlwenlyQ2dzMTRTOHUKZVFZdkorNEFzUE9uT1RGcExkaVl5UkVyNXdyNmJuMXUvMjZxc2FKckpxbkkyRk16SmdEQVRwZEtjbXRHYjBUOQp3S2wrYUJHcFFKcThrUWJwakVGTHhaWDJzaUNrRG82WittaUcrRjRKMHpKa3BKK0JHMS92eGZKbk0zK1ptdXQ5Ck9RV2ZjYTN3UHlhTWRDbGIyZjQwYlRFaFo5Mk9kcWlQMzFMbDlHWExSZmhaNTNsUzF0QWdvUGZoR25NbFY4b2MKWmxuSUROK25wS0Nma2tXUDJZUjlRLy9pa01tM01YRm9RSFppaVJseVZHSGFKZWRLMmNOQzlUYk4xNDFTaWZHZQo3V2FsQVBNcWNOQ3F3YStnN2RFSmR3ZjlRMklJTml0SjlDUVprT1dUZElYY2VHK2lZWWUrQXpmK1NkaHBocVdPCllFcDF6ek40dXI5U2VxU3NSaU9WY0RzVUFSa1M0clgrb0Vzb2hHL1Q5OTcrSDhjR2gzczl6TE84emtwRXZKSmEKS05QT0N5ODhVeEFOV2RRejFLMXRKVVQ2c3hkd0FEcXRJQnNPemhYVjlybDRRNStlZExlcmZPcUtCbUFRMUY5Swo2L1l0ZlNyY0JpeXZEU24wdFJ3OHJLRFVQU1hFNDFldXArOURNeThLVGl6T0RPTXVMSnR2dkJrTEFpNGNYQjVBCjQxMjBEdHdZQXNyNzNZYVl2SW8rWjV2OGZ4TjF3M3IwYS9KOVhZQlg3S3p1OFl4MnNUNWtWM2dNTHFCTXBaa3gKY29FTjNSandDMmV4VHl6dGc1ak1ZN2U4VFJ4OFFTeUxkK0pBd2t1Tm01NlNkcHFHNTE3cktJYkVMNDZzbkd0UgpCYUVOK01GeXNqdDU3ejhKQXJDMzhBMFN5dTQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K global.tlsKey:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRd0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1Mwd2dna3BBZ0VBQW9JQ0FRRG9EVnBremZUSkk4cEUKZTZBZ1JSMUkvekE2b2NwNHNPQVJ5NC9IdXdpMU1yVnFVNzFqU1VrRzRWUXZzUGVoeHBqYmRMeFVPTWZDMDVMRApFWS9xbFpMeHRQdEFpekZRWnNVZEZMODJCamp4RXlReXBlZW5hb3RBdVhJSUVzSGV1LzhwVUgzZGJLZzFEeHR5ClZIMGpSMEVHUHVTUk5JaVhIc1FRc1B5cHVFTWt3S2JZUzk3UjlabUF6d0FoMDdtWlpZT2hFc1lIU1hKdmxZZlUKUTZKb2plNTdYOUdFNXFsbEIzc1dFUlBxdFJYQkdqOGZmM2ZRQzNvTG1MeGpScDlUL1BrTUhUUXZ1V2RCQlpFTgppclpvMHdCamlwSlNENXpBUlo1c1JSeWpJTjBwTFhYT3R5RFV1M0I5KzdkM0tJc2V6aHFmWHE3YUIxY3ZudmZ1CjIyNis0Q0dsN0RSRlU2K0JXS3g5a2pzYStkdVVBQ1JqdnViMkR3bHlVU0xxakhudTN2TzRlQjBxeEZGbFRjVGIKU0FCbFRHMDVsbXM0ZHBSd0laTm5Ia2QwUTJRdE1PR2pjTEVFbEhUSzltZ1lnSVoyakI1K0c3eDM4THZLa0s5YwpvazArSnVDU0poUlV1Tjc1WEF5K24xQVlPcXJVbzh3ZGJXTlhEcjlzcmdMZHhtQ1J3bE5Gc1JsUXdUdURoWUtSCnU0VFVRODlodVJOYmZ4SHVrK2RjUHV2cU1zc1c2REl2am5WSURLV1BJcktld0RJWnIxUlBScHVSNlFTUUJldjYKMnVXQW9PUExpSks1eG1KNlBja2lhWVNrZ1pkRXkvekR1VUVJaWFCeE9yc253VmdmV0lFZ0xmYmR0bzBxa1dTVQpiU3BKYWM1VVJ4UXpXT0tYMDVJc2ppVUZtMHZCS3dJREFRQUJBb0lDQUZDN3ZKUlB0M2QzVlRyb1MvaU9NemNmCldaYzhqT1hhbThwMUtRdlRQWjlWQ2hyNUVXNEdwRHFaa0tHYkR6eWdqTFBsZEZSVkFPTCtteFAwK3o0aFZlTjAKRk9vS3cxaDJ1T042UVdBNVgvdzNyYU5WWnpndThFM1BkeVhwNkx0bWFzcmo3elpuUkVwWmZESVZ4UWZPRllobgp2enZwckEvdnEwVW5YbkJwNUNwWVFIUUdTWHFBMlN3Z1dLcHNNQ2wzVVFsc0w2dC9XU29MT3h1VmdGNmg2clBQCnpXUlFuK1MvYW9wdDNLRU82WWVxYXdXNVltVG1hVXE1aytseU82S0w0OVhjSHpqdlowWU8rcjFjWWtRc0RQbVUKejMxdll4amQzOVZKWWtJNi85Y0Fzdmo5YTVXM3ROYVFDZStTRW56Z05oRDJieHo1NnRKdG0xTGwweXpqYTdEVgp0OW9aQVd6WURMOTVnMDFZWVlQMG51c3A4WWlNOXd0OUtLc2NkcUd3RFN5WHNrWFBrcWFLVjNVcHJYdmhFbFVaCkErMmtjcm9VaDNGbEV4bGpwUmtKVkhOZXJ3NHRLRi9oYTFWRjZPdE10eTVQcXV0N0dGQmIvamtWeUg5cnpueWUKTXQyTWVyTTVPazMwd1NuTThISUdTUXpxYlplekJEZlNaUzRzcWdZZnBIMlhtMEs0SjgrRUowQ2hhMXZVSmVNMAoyZ284d00vaHljdmtqTEgxSmM3OEhpaVBTQ01udkpHemUxc2tWdmtRRFhBSFdldzBTUHpUSTZHYjZCb0Y4aVNECm0wZjR2azNoV3NlUWZBaXVZSnlUeUZXNmRhOGE1K2lpSDN4cVRsUUN1MDN1Nmo0U0l4aThJZlNmd0YwQTBldVAKNGtzalZTZVZyT3ExUnlvNUtpR3hBb0lCQVFEOWZtYnl6aW9QdVhRYzl0QXBxMUpSMzErQzlCdFFzcDg5WkZkSQpQaU5xaTJ3NVlVcTA0OFM2Z3VBb3JGOHNObUI3QjhWa1JlclowQ3hub2NHY0tleWdTYWsvME5qVElndk5weGJwCnBGbkFnRjlmbW1oTEl2SlF2REo2Q0ZidDRCQlZIdkJEWlYyQnZqK0k3NUxkK01jN2RPVDdFek1FRjBXcUdzY2MKTUpyNjRXQi9UMkF5dWR1YXlRT2NobmJFQ25FUmdRcHFlbG54MVBraytqbGNvYUs5QjFYUStVOUgzOHppM0FYNApENUxMY0Nhem9YYWlvS0swckNlNE5Ga2hOVXd0TFV0QXhSTXk2aksyZUZudWczUFRlY3N1WktNMElITktqZ0dCCnpGanZVb2tMcFVFb3BJa3FHM09yc0xmanpHZW9jaVFPUXNEdzlUb3lXL0FSOFhmWkFvSUJBUURxV0s2TThVN3EKUXJPeTYzNnpEZlBaZ2ljeXlsUWVoOFdMclBlbW5NeWdQYzR4eWoybnMrTmVRSnNEUmtPT2tWY250SEFYaTcwWgoyT0NCV3dwZHJuTXlSc3RIMU05bjdFNU5TVHZlZDlkU3YxUzRBb3NzS1hDSmgyUHBjYjV0OE9nL3ZGTlNYUlUyClk2aUorWTdOcDBZNDNxSlJOVnlRemd3YmFzaEpiUVdkVFFoVEVhdEVRS2JsUlZSblhlQWRjOXlhNUpHbkRpaTkKbFQrRWEzdFpvN1dha05oeHJkYjVuTkZ3a0xoNEs3ZkFtT3ZzMVBMQWx0SUZqeURCeDEvY1ZHblpDUDBVQmJqZgpkU2FueXBBdVRuMzd1VUwrcXpPVDlYWEZENllGT0x0NWV4d3RxdnUwSzZCNjcvajFFTlJDRk45RnMzWlV5RFFXClZUaDcybFhWU3NLakFvSUJBUUR6ZE5pdXpTNDhWK0thaHJpNXJGNnRYeGkrRG0vRmV5ZlFzSFBiWUVKbmEyd1AKVjgrR0YxS3p4a28vQmYySjJ0ZWlrWDRVcGNtK1UxNnlVUG8vWDB4eFRRMk55cWpUYmRsa005dWZuVWJOeVB6UQpOdDEvZkJxNVMyWTNLWmREY25SOUsrK1k2dHQ1Wmh4akNhUkdKMDVCWGkwa3JmWExNZ2FvTG51WUtWNVBJUEdxCms3TlNSSW9UQ0llOVpxN2Q3U0ZXckZZeW1UdVZOUFByZlo1bHhwOGphTTRVbTd4MnpReGJ2UERHb3o1YXdHV0wKRThGNncwaEF1UzZValVJazBLbE9vamVxQnh3L1JBcGNrUTNlTXNXbEQwNENTb2tyNFJhWlBmVllrY2ZBWWNaWgpOdWR6ZjBKMC9GU0ZTbjN4L0RoNTROV2NGS1IxUnpBVGVaVUJ4cVZSQW9JQkFRRFlDNmZvVWpOQnJ2ckNFVzkrCkhYZlk1Ni9CbUZ4U3hUTHU0U2h6VncwakViZTltVWljQ2pDc1hQMUwySVJCdEdaWU9YWTVqdDlvSzlSV0RSdVMKWUZqZFdmemduU1lWRmZyZUw0emRQVGlxbGEvQjhMNWptVlNoeGNycmxheE02Uk1FWjFlZGtDa1ZPbTFQdmwzVAo1TW5OZGhySXFWeE1OMWxjRVdiU29vclJpUW9Lb3poMHRQSG9YckZBbG9BZVJ3bHpWeE9jb21ZVzJiaDBHUzdmCjVoaHZoZWUxYmVISnY3UXFoWkU3WUhxSU9iTVBaUWJqWEdnRkxmMnlDRitzM2Jtem1DRFJTN0V6ZVdxSXVDdVMKTlZUYU0rSzZyQlRoN0NLRjZUWlNqQW55SmZoRmRlT1ZKNzlNZDEzYWVJaG0zNTB6UWc3dWZKL2drdkorNUR2TApacC9uQW9JQkFBVlg4WHpFTzdMVk1sbENKZFVUdURTdXNPcDNrQVlFZ2dZNFFRM3FNTlcxRnl5WEM3WjBGOWJFCmtTSEhkalJtU2RUbFZueGN2UW1KTS9WL2tJanpNUHhFT3NCS1BVVkR3N3BhOHdiejlGcTRPOCtJb3lqN1ZXclcKMmExL1FNWXlzSGlpTlBzNy8vWUtvMy9rdkhCWUY2SnNkenkyQkVSTkQ0aTlVOWhDN0RqcGxKR3BSNktMTVBsegpNWFJ3VjVTM2V3cnBXZVcxQW5ONC9EKy9zUGlNQTNnS0swSlBFdGVBV1dndEZHTnNBSkJnaFBoUExxQi9CcDUvCkhOeC96M0w0MWtqRnpqOHNWaHMrVDRZYlhiaGF2R2xxc2h5ZldQbnRhV1VOMG15MjU1RFdQUDhWa24yeFNlV2kKVm1hVW5TSDBTZ2tlUENMRnlra25yQzgxU2pXZkRBMD0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=] kind:ConfigMap metadata:map[labels:map[installer:overrides kyma-project.io/installation:] name:cluster-certificate-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[global.adminPassword: global.domainName:kyma.local global.isLocalEnv:true global.minikubeIP: nginx-ingress.controller.service.loadBalancerIP:] kind:ConfigMap metadata:map[labels:map[installer:overrides kyma-project.io/installation:] name:installation-config-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[gateways.istio-ingressgateway.autoscaleEnabled:false gateways.istio-ingressgateway.loadBalancerIP: gateways.istio-ingressgateway.type:NodePort mixer.loadshedding.mode:disabled mixer.policy.autoscaleEnabled:false mixer.policy.resources.limits.cpu:500m mixer.policy.resources.limits.memory:2048Mi mixer.policy.resources.requests.cpu:300m mixer.policy.resources.requests.memory:512Mi mixer.telemetry.autoscaleEnabled:false mixer.telemetry.resources.limits.cpu:500m mixer.telemetry.resources.limits.memory:2048Mi mixer.telemetry.resources.requests.cpu:300m mixer.telemetry.resources.requests.memory:512Mi pilot.autoscaleEnabled:false pilot.resources.limits.cpu:500m pilot.resources.limits.memory:1024Mi pilot.resources.requests.cpu:250m pilot.resources.requests.memory:512Mi] kind:ConfigMap metadata:map[labels:map[component:istio installer:overrides kyma-project.io/installation:] name:istio-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[etcd-stateful.etcd.resources.limits.memory:256Mi etcd-stateful.replicaCount:1] kind:ConfigMap metadata:map[labels:map[component:service-catalog installer:overrides kyma-project.io/installation:] name:service-catalog-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[global.isDevelopMode:true] kind:ConfigMap metadata:map[labels:map[component:helm-broker installer:overrides kyma-project.io/installation:] name:helm-broker-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[telemetry.enabled:false] kind:ConfigMap metadata:map[labels:map[component:dex installer:overrides kyma-project.io/installation:] name:dex-overrides namespace:kyma-installer]] map[apiVersion:installer.kyma-project.io/v1alpha1 kind:Installation metadata:map[finalizers:[finalizer.installer.kyma-project.io] labels:map[kyma-project.io/installation:] name:kyma-installation] spec:map[components:[map[name:cluster-essentials namespace:kyma-system] map[name:testing namespace:kyma-system] map[name:istio-init namespace:istio-system] map[name:istio namespace:istio-system] map[name:xip-patch namespace:kyma-installer] map[name:istio-kyma-patch namespace:istio-system] map[name:knative-serving-init namespace:knative-serving] map[name:knative-serving namespace:knative-serving] map[name:knative-eventing namespace:knative-eventing] map[name:dex namespace:kyma-system] map[name:ory namespace:kyma-system] map[name:api-gateway namespace:kyma-system] map[name:service-catalog namespace:kyma-system] map[name:service-catalog-addons namespace:kyma-system] map[name:helm-broker namespace:kyma-system] map[name:nats-streaming namespace:natss] map[name:assetstore namespace:kyma-system] map[name:cms namespace:kyma-system] map[name:core namespace:kyma-system] map[name:knative-provisioner-natss namespace:knative-eventing] map[name:event-bus namespace:kyma-system] map[name:application-connector-ingress namespace:kyma-system] map[name:application-connector-helper namespace:kyma-integration] map[name:application-connector namespace:kyma-integration]] url:__URL__ version:__VERSION__]]]' command  with output 'namespace/kyma-installer created
limitrange/kyma-default created
customresourcedefinition.apiextensions.k8s.io/installations.installer.kyma-project.io created
customresourcedefinition.apiextensions.k8s.io/releases.release.kyma-project.io created
serviceaccount/helm-certs-job-sa created
rolebinding.rbac.authorization.k8s.io/helm-certs-rolebinding created
rolebinding.rbac.authorization.k8s.io/helm-certs-rolebinding created
role.rbac.authorization.k8s.io/helm-certs-getter created
role.rbac.authorization.k8s.io/helm-certs-setter created
clusterrole.rbac.authorization.k8s.io/all-psp created
clusterrolebinding.rbac.authorization.k8s.io/all-psp created
job.batch/helm-certs-job created
serviceaccount/kyma-installer created
deployment.extensions/kyma-installer created
clusterrole.rbac.authorization.k8s.io/kyma-installer-reader created
clusterrolebinding.rbac.authorization.k8s.io/kyma-installer created
secret/application-connector-certificate-overrides created
configmap/cluster-certificate-overrides created
configmap/installation-config-overrides created
configmap/istio-overrides created
configmap/service-catalog-overrides created
configmap/helm-broker-overrides created
configmap/dex-overrides created
error: unable to recognize "STDIN": no matches for kind "Installation" in version "installer.kyma-project.io/v1alpha1"
' and error message 'exit status 1' failed


```

**Steps to reproduce**

```
sudo kyma provision minikube
kyma install
```

**Comment by clebs** [comment] 2019-11-08 09:56
Hello @p4p4,

I tried reproducing your issue on a freshly installed Ubuntu 19.04 and unfortunately was not able to reproduce it. I was able to install kyma on minikube.

Some things that I think you could maybe check are:
- Your user has permission to read all necessary files (such as `/tmp/certs`, ~/.kube and ~/.minikube).
- Minikube is using driver "none".
- You are not behind a firewall or VPN that prevents normal network functioning.

**Comment by a-thaler** [comment] 2019-11-22 10:33
@p4p4, please double check the points mentioned by @clebs . Will close the issue for now, feel free to re-open.

**Closed by a-thaler** 2019-11-22 10:33 UTC
Labels: area/cli, bug, question
