### ISSUE TITLE
Deleting deployments should also remove replica sets

### ISSUE THREAD

**Issue by arifC** [kyma-project/kyma#3245] opened 2019-03-19 14:20 UTC
**Description**
Removing a deployment usually results in the replica sets and pods being terminated. This is the behavior when you delete deployments from the kubernetes dashboard or kubectl. However, in the Kyma console only the deployment is deleted.

Version: 0.8.0 on GKE

**Expected result**
I expect the replica sets corresponding to this deployment to be terminated as well.

**Actual result**
Only the deployment itself is deleted.

**Steps to reproduce**
Create a deployment in Kyma and delete it using the Kyma console.

**Troubleshooting**
I had to manually delete the replica sets.

**Comment by hardl** [comment] 2019-03-21 10:26
duplicate of https://github.com/kyma-project/console/issues/704

**Closed by hardl** 2019-03-21 10:26 UTC
