### ISSUE TITLE
Jobs randomly fail on metrics.k8s.io/v1beta1: the server is currently unable to handle the request

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/kyma#7725] opened 2020-03-20 15:56 UTC
**Description**
I've noticed that jobs randomly fail on accessing the API server *custom.metrics.k8s.io/v1beta1, metrics.k8s.io/v1beta1*. The issue occurred during Kyma installation stage of jobs. Mostly on `kyma-aks-nightly` (2 fails over 1 success) and several other jobs.

There are some of the logs that are affected:
```
kyma installation error, description: install component logging
Installation errors until timeout:
----------

cluster-essentials:
  Helm install error: rpc error: code = Unknown desc = Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
logging:
  Helm install error: rpc error: code = Unavailable desc = transport is closing
logging:
  Helm install error: rpc error: code = Unknown desc = a release named logging already exists.
Run: helm ls --all logging; to check the status of the release
Or run: helm del --purge logging; to delete it
----------
```
```
X Waiting for installation to start
cluster-essentials:
 Helm install error: rpc error: code = Unknown desc = Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request [%!s(int64=6)]
```

**Affected jobs**
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-aks-nightly/1240850689752567808
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1240648483606630402
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-aks-nightly/1240192732006191104
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-aks-nightly/1239763528080953344

**Comment by aerfio** [comment] 2020-03-24 12:23
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-aks-nightly/1242300240585822209

**Comment by adamwalach** [comment] 2020-03-25 10:41
In the docs for AKS: https://docs.microsoft.com/en-us/azure/aks/availability-zones#create-an-aks-cluster-across-availability-zones they mention:
```
The AKS control plane components for your cluster are also 
spread across zones in the highest available configuration 
when you define the --zones parameter at cluster creation time.
```
Maybe thats a way to improve performance of the  api-server?

**Comment by aerfio** [comment] 2020-03-26 09:39
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-aks-nightly/1242662627469955075

**Comment by dekiel** [comment] 2020-03-31 08:55
Enabled building aks-nightly with master nodes in three zones. https://github.com/kyma-project/test-infra/pull/2180

**Comment by adamwalach** [comment] 2020-04-15 09:23
It fixed the issue on aks-nightly, but it still fails on other jobs (on PRs):
![Screenshot 2020-04-15 at 11 09 07](https://user-images.githubusercontent.com/8530211/79320156-9cc7e280-7f09-11ea-9eff-ce9af7b8c6a6.png)

Other jobs can't be fixed in the same way - we would have to change type of the cluster to [regional](https://cloud.google.com/kubernetes-engine/docs/concepts/regional-clusters), now they are zonal.
But that would be just masking the core issue - we (helm in this case) cannot properly handle API server failures during installation. 
This issue is caused by poor performance/inaccessibility of API server in the early stage of cluster lifetime.

**Comment by piotrmsc** [comment] 2020-04-20 07:16
https://github.com/helm/helm/issues/6361

Issue was raised in helm and fixed. TL:DR they have modified handling of fetching capabilities that is fetching APIServices from clusters. They allow more statuses that are updated in the meantime of installation. I have a pr with tiller upgrade (was backported to helmv2)

https://github.com/kyma-project/kyma/pull/8065

**Comment by piotrmsc** [comment] 2020-04-23 09:13
PR was merged, additional PR in test infra for upgrade jobs was merged as well. Let's see how it behaves. So far looks good. Please reopen and ping me if you still see those errors.

**Closed by piotrmsc** 2020-04-23 09:13 UTC
Labels: area/installation, test-failing
