### ISSUE TITLE
Problem with Istio during installation

### ISSUE THREAD

**Issue by jasiu001** [kyma-project/kyma#3494] opened 2019-04-02 08:09 UTC
**Description**
During Kyma installation often occurs errors related to istio. In time period between 27.03 to 01.04 on prow in `post-master-kyma-integration` job more than 50% jobs failed from the same reason.

**Error**
```
istio:
Helm install error: rpc error: code = Unknown desc = validation failed: [unable to recognize "": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "handler" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "handler" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "kubernetes" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2"]
core:
Helm install error: rpc error: code = Unknown desc = Job failed: DeadlineExceeded
core:
Helm install error: rpc error: code = Unknown desc = a release named core already exists.
Run: helm ls --all core; to check the status of the release
Or run: helm del --purge core; to delete it
```

**Comment by sjanota** [comment] 2019-04-02 08:37
The error
```
istio:
Helm install error: rpc error: code = Unknown desc = validation failed: [unable to recognize "": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "handler" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "handler" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "kubernetes" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2"]
```
is the first error that occurred during installation. As we see in this log there were other errors later in core. one of them is `Job failed: DeadlineExceeded` which is the cause of installation failure. It means that one of the jobs that are run during core installation took too long to complete.

**Comment by sayanh** [comment] 2019-04-02 12:06
Another runs in here:

https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1113018975685447683
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1113018975685447682
```
istio:
Helm install error: rpc error: code = Unknown desc = validation failed: [unable to recognize "": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "handler" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "handler" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "kubernetes" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2"]
dex:
Helm install error: context deadline exceeded
installer:
Helm error: context deadline exceeded
----------
```

**Comment by pkosiec** [comment] 2019-04-02 13:56
Another ones:

https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/3501/pre-rel09-kyma-integration/1113064024108437504/build-log.txt
https://status.build.kyma-project.io/log?id=1113073964298539008&job=pre-rel09-kyma-integration

**Comment by jasiu001** [comment] 2019-04-04 07:53
Another error today during install Kyma on AKS 
https://status.build.kyma-project.io/log?job=kyma-aks-nightly&id=1113652653373526016

**Comment by Tomasz-Smelcerz-SAP** [comment] 2019-04-04 09:05
@jasiu001 This build failed due to a completely different error! Please don't introduce FUD: The real reason for the failure is some syntac error in charts:  `error converting YAML to JSON: yaml: line 6: did not find expected key`

**Comment by Tomasz-Smelcerz-SAP** [comment] 2019-04-04 09:50
> Another ones:
> 
> https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/3501/pre-rel09-kyma-integration/1113064024108437504/build-log.txt
> https://status.build.kyma-project.io/log?id=1113073964298539008&job=pre-rel09-kyma-integration

@pkosiec In this case it wasn't because of Istio, it was because helm-broker installation timed out. Error in Istio was recovered and reported, but it's not the cause of the failure.

**Comment by Tomasz-Smelcerz-SAP** [comment] 2019-04-04 09:53
> Another runs in here:
> 
> https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1113018975685447683
> https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1113018975685447682

@sayanh This log does not indicate failure due to Istio, but dex. The Istio error was recovered and reported - as we should report errors during installation. But the reason for failure was timeout during dex installation.

**Comment by Tomasz-Smelcerz-SAP** [comment] 2019-04-04 09:56
@jasiu001 This looks like an invalid bug report to me.
All errors during installation are reported by Installer, but not all of them lead to a failure.
This is real reason for failure:
`
core:
Helm install error: rpc error: code = Unknown desc = Job failed: DeadlineExceeded
core:
Helm install error: rpc error: code = Unknown desc = a release named core already exists.
`
One job in core failed (we don't know which one) and then `core` chart was failing on re-installation attempts.
Istio error was recovered and reported as we should report all errors.

**Comment by aszecowka** [comment] 2019-04-04 18:03
2 examples from 4th April that shows that Installer/Istio is unstable:
https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-integration/1113788676564848642/build-log.txt

https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-integration/1113774961530507266/build-log.txt

Next example, from @sayanh : https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-integration/1113018975685447682/build-log.txt
@Tomasz-Smelcerz-SAP, you claim that this is a problem with Dex, I cannot find dex in logs AT ALL!

I reopen this issue.

**Comment by sjanota** [comment] 2019-04-04 18:20
@aszecowka First of all two issues you mentioned are not showing that Installer/Istio is unstable. Both of them failed because some job in core failed with timeout. I haven't seen a single issue for that error even though it happens very often.

Regarding issue you from @sayanh I agree that something very weird happened here. Looks like tiller crash or some network error (transport closing and timeout both coming from helm).

And it is not a problem with installer logs. It is problem with istio chart implementation which causes first attempt to install istio to fail (usually, not always). Let me stress it one more time: there is no problem with istio installation we know about, and all reports posted here are reflecting different problems. There should be already two different tickets with proper description instead of this one. I'll create them tomorrow. In the meanwhile let me close this ticket so problems are not hidden here.

**Closed by sjanota** 2019-04-04 18:20 UTC
Labels: area/installation, bug, invalid, priority/critical

**Comment by sjanota** [comment] 2019-04-05 06:34
Issue for unnecessary error: https://github.com/kyma-project/kyma/issues/3589
Issue for job timeout: https://github.com/kyma-project/kyma/issues/3590
