### ISSUE TITLE
Application Mapping not cleared after Application is deleted

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#6854] opened 2020-01-14 11:18 UTC
**Description**

Application controller doesn't clean up ApplicationMappings when Applications are deleted.

**Expected result**

Application controller cleans up ApplicationMappings of the application instance that is being deleted

**Actual result**

There are orphaned ApplicationMappings whenever application was bound to a namespace and later on deleted (w/o unbinding the namespace)

**Steps to reproduce**

1. Create application (using Application CR or via compass) (`my-application`)
2. Bind the new application to a namespace (`default`)
3. Delete the application (either delete the CR via CLI or UI, or delete application via compass)

The application resource is gone, but there is a leftover ApplicationMapping (to the bound namespace `default`)

Now, with every `ListInNamespace` execution (i.e when listing namespaces in the UI) you can see a warning log indicating the existence of orphaned mapping.
 
```
app_service.go:241] Found ApplicationMapping "Application" in namespaces "my-application" but default with name "my-application" does not exists
```

**Comment by janmedrek** [comment] 2020-05-15 12:53
Closing as a semi-duplicate of: https://github.com/kyma-project/kyma/issues/3728

**Closed by janmedrek** 2020-05-15 12:53 UTC
Labels: area/application-connector, bug
