### ISSUE TITLE
Error installing kyma with minikube

### ISSUE THREAD

**Issue by SofiaTa** [kyma-project/kyma#7830] opened 2020-03-29 20:15 UTC
Steps to reproduce 

- brew install kyma-cli
- kyma provision minikube
- kyma install

`mac 10.15.3` 
 `kyma 1.10` , 

using minikube **1.6.2** and also **1.9.0** provide the same error:

the cluster is reacable, I tried simply 
`kubectl get ns`

NAME              STATUS   AGE
default           Active   63m
kube-node-lease   Active   63m
kube-public       Active   63m
kube-system       Active   63m

This is the outpupt, from `kyma install` command , the error is in the bottom

   ~/.kube  kyma provision minikube --vm-driver=virtualbox                                                                                                                                                                   ✔  at 22:17:18 
- Requirements verified
  Preparing Minikube using vm-driver 'virtualbox'
- Minikube status verified
- Minikube config initialized
- Minikube up and running
- Adjustments finished
- ConfigMap created

Minikube cluster installed
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured

Happy Minikube-ing! :)
    ~/.kube  kyma install                                                                                                                                                                                      ✔  took 2m 9s   at 22:20:20 
- Cluster info read
- Configurations validated
  Installing Kyma in version '1.10.0'
- Installation source checked
- Tiller deployed
- Installation files loaded
X Deploying Kyma Installer
Error: Executing kubectl 'kubectl apply -f -[map[apiVersion:v1 kind:Namespace metadata:map[labels:map[istio-injection:disabled kyma-project.io/installation:] name:kyma-installer]] map[apiVersion:v1 kind:LimitRange metadata:map[labels:map[kyma-project.io/installation:] name:kyma-default namespace:kyma-installer] spec:map[limits:[map[default:map[memory:256Mi] defaultRequest:map[memory:32Mi] max:map[memory:1024Mi] type:Container]]]] map[apiVersion:apiextensions.k8s.io/v1beta1 kind:CustomResourceDefinition metadata:map[labels:map[kyma-project.io/installation:] name:installations.installer.kyma-project.io] spec:map[group:installer.kyma-project.io names:map[kind:Installation plural:installations shortNames:[installation] singular:installation] scope:Namespaced version:v1alpha1]] map[apiVersion:apiextensions.k8s.io/v1beta1 kind:CustomResourceDefinition metadata:map[labels:map[kyma-project.io/installation:] name:releases.release.kyma-project.io] spec:map[group:release.kyma-project.io names:map[kind:Release plural:releases shortNames:[release] singular:release] scope:Namespaced version:v1alpha1]] map[apiVersion:v1 kind:ServiceAccount metadata:map[name:helm-certs-job-sa namespace:kyma-installer]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:RoleBinding metadata:map[name:helm-certs-rolebinding namespace:kube-system] roleRef:map[apiGroup:rbac.authorization.k8s.io kind:Role name:helm-certs-getter] subjects:[map[kind:ServiceAccount name:helm-certs-job-sa namespace:kyma-installer]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:RoleBinding metadata:map[name:helm-certs-rolebinding namespace:kyma-installer] roleRef:map[apiGroup:rbac.authorization.k8s.io kind:Role name:helm-certs-setter] subjects:[map[kind:ServiceAccount name:helm-certs-job-sa namespace:kyma-installer]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:Role metadata:map[name:helm-certs-getter namespace:kube-system] rules:[map[apiGroups:[] resources:[secrets] verbs:[get list]]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:Role metadata:map[name:helm-certs-setter namespace:kyma-installer] rules:[map[apiGroups:[] resources:[secrets] verbs:[get list create patch]]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:ClusterRole metadata:map[name:all-psp] rules:[map[apiGroups:[policy/v1beta1] resources:[podsecuritypolicies] verbs:[use]]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:ClusterRoleBinding metadata:map[name:all-psp] roleRef:map[apiGroup:rbac.authorization.k8s.io kind:ClusterRole name:all-psp] subjects:[map[kind:ServiceAccount name:helm-certs-job-sa namespace:kyma-installer]]] map[apiVersion:batch/v1 kind:Job metadata:map[labels:map[kyma-project.io/installation:] name:helm-certs-job namespace:kyma-installer] spec:map[template:map[metadata:map[annotations:map[sidecar.istio.io/inject:“false”] name:helm-certs-job namespace:kyma-installer] spec:map[containers:[map[command:[bash -c WORKING_DIR="/tmp/certs"
mkdir -p "${WORKING_DIR}"

cat <<EOF > "${WORKING_DIR}/openssl.cnf"
[ req ]
#default_bits   = 2048
#default_md   = sha256
#default_keyfile  = privkey.pem
distinguished_name  = req_distinguished_name
attributes    = req_attributes

[ req_distinguished_name ]
countryName     = Country Name (2 letter code)
countryName_min     = 2
countryName_max     = 2
stateOrProvinceName   = State or Province Name (full name)
localityName      = Locality Name (eg, city)
0.organizationName    = Organization Name (eg, company)
organizationalUnitName    = Organizational Unit Name (eg, section)
commonName      = Common Name (eg, fully qualified host name)
commonName_max      = 64
emailAddress      = Email Address
emailAddress_max    = 64

[ req_attributes ]
challengePassword   = A challenge password
challengePassword_min   = 4
challengePassword_max   = 20
[ v3_ca ]
basicConstraints = critical,CA:TRUE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
EOF

echo "---> Get Tiller CA"
if [[ $(kubectl get -n kube-system secret tiller-secret) ]] ; then
  kubectl get -n kube-system secret tiller-secret -o jsonpath="{.data['ca\.crt']}" | base64 --decode > "${WORKING_DIR}/ca.crt"
  kubectl get -n kube-system secret tiller-secret -o jsonpath="{.data['ca\.key']}" | base64 --decode > "${WORKING_DIR}/ca.key"
else
  echo "Secret: tiller-secret does not exists!"
  exit 1
fi

echo "---> Generate Helm key"
openssl genrsa -out "${WORKING_DIR}/helm.key.pem" 4096
openssl req -key "${WORKING_DIR}/helm.key.pem" -new -sha256 -out "${WORKING_DIR}/helm.csr.pem" -subj "/C=PL/ST=Gliwice/L=Gliwice/O=Helm Client/CN=helm-client"
openssl x509 -req -CA "${WORKING_DIR}/ca.crt" -CAkey "${WORKING_DIR}/ca.key" -CAcreateserial -in "${WORKING_DIR}/helm.csr.pem" -out "${WORKING_DIR}/helm.cert.pem" -days 365

echo "---> Create secrets in k8s"
COMBO_YAML=$(cat << EOF
---
apiVersion: v1
data:
  global.helm.ca.crt: "$(base64 "${WORKING_DIR}/ca.crt" | tr -d '\n')"
  global.helm.tls.crt: "$(base64 ${WORKING_DIR}/helm.cert.pem | tr -d '\n')"
  global.helm.tls.key: "$(base64 ${WORKING_DIR}/helm.key.pem | tr -d '\n')"
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    installer: overrides
    kyma-project.io/installation: ""
  name: helm-secret
  namespace: kyma-installer
type: Opaque
EOF
)

echo "${COMBO_YAML}" | kubectl create -f -
] image:eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20190325-ff66a3a name:certhelper]] restartPolicy:OnFailure serviceAccountName:helm-certs-job-sa]]]] map[apiVersion:v1 kind:ServiceAccount metadata:map[labels:map[kyma-project.io/installation:] name:kyma-installer namespace:kyma-installer]] map[apiVersion:apps/v1 kind:Deployment metadata:map[labels:map[kyma-project.io/installation: name:kyma-installer] name:kyma-installer namespace:kyma-installer] spec:map[selector:map[matchLabels:map[name:kyma-installer]] template:map[metadata:map[labels:map[name:kyma-installer]] spec:map[containers:[map[args:[-tillerTLSInsecureSkipVerify=true] image:eu.gcr.io/kyma-project/kyma-installer:1.10.0 imagePullPolicy:IfNotPresent name:kyma-installer-container volumeMounts:[map[mountPath:/etc/certs name:helm-certs readOnly:%!s(bool=true)]]]] serviceAccountName:kyma-installer volumes:[map[name:helm-certs secret:map[items:[map[key:global.helm.tls.crt path:tls.crt] map[key:global.helm.tls.key path:tls.key]] secretName:helm-secret]]]]]]] map[apiVersion:rbac.authorization.k8s.io/v1beta1 kind:ClusterRole metadata:map[labels:map[kyma-project.io/installation:] name:kyma-installer-reader] rules:[map[apiGroups:[*] resources:[*] verbs:[*]]]] map[apiVersion:rbac.authorization.k8s.io/v1beta1 kind:ClusterRoleBinding metadata:map[labels:map[kyma-project.io/installation:] name:kyma-installer] roleRef:map[apiGroup:rbac.authorization.k8s.io kind:ClusterRole name:kyma-installer-reader] subjects:[map[kind:ServiceAccount name:kyma-installer namespace:kyma-installer]]] map[apiVersion:v1 data:map[global.applicationConnectorCa: global.applicationConnectorCaKey:] kind:Secret metadata:map[labels:map[installer:overrides kyma-project.io/installation:] name:application-connector-certificate-overrides namespace:kyma-installer] type:Opaque] map[apiVersion:v1 data:map[global.tlsCrt:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU4RENDQXRpZ0F3SDhWa24yeFNlV2kKVm1hVW5TSDBTZ2tlUENMRnlra25yQzgxU2pXZkRBMD0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=] kind:ConfigMap metadata:map[labels:map[installer:overrides kyma-project.io/installation:] name:cluster-certificate-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[global.adminPassword: global.domainName:kyma.local global.isLocalEnv:true global.minikubeIP: nginx-ingress.controller.service.loadBalancerIP:] kind:ConfigMap metadata:map[labels:map[installer:overrides kyma-project.io/installation:] name:installation-config-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[gateways.istio-ingressgateway.autoscaleEnabled:false gateways.istio-ingressgateway.loadBalancerIP: gateways.istio-ingressgateway.type:NodePort mixer.loadshedding.mode:disabled mixer.policy.autoscaleEnabled:false mixer.policy.resources.limits.cpu:500m mixer.policy.resources.limits.memory:2048Mi mixer.policy.resources.requests.cpu:300m mixer.policy.resources.requests.memory:512Mi mixer.telemetry.autoscaleEnabled:false mixer.telemetry.resources.limits.cpu:500m mixer.telemetry.resources.limits.memory:2048Mi mixer.telemetry.resources.requests.cpu:300m mixer.telemetry.resources.requests.memory:512Mi pilot.autoscaleEnabled:false pilot.resources.limits.cpu:500m pilot.resources.limits.memory:1024Mi pilot.resources.requests.cpu:250m pilot.resources.requests.memory:512Mi] kind:ConfigMap metadata:map[labels:map[component:istio installer:overrides kyma-project.io/installation:] name:istio-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[etcd-stateful.etcd.resources.limits.memory:256Mi etcd-stateful.replicaCount:1] kind:ConfigMap metadata:map[labels:map[component:service-catalog installer:overrides kyma-project.io/installation:] name:service-catalog-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[global.isDevelopMode:true] kind:ConfigMap metadata:map[labels:map[component:helm-broker installer:overrides kyma-project.io/installation:] name:helm-broker-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[telemetry.enabled:false] kind:ConfigMap metadata:map[labels:map[component:dex installer:overrides kyma-project.io/installation:] name:dex-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[application-operator.tests.enabled:false application-registry.tests.enabled:false connector-service.tests.enabled:false tests.application_connector_tests.enabled:false] kind:ConfigMap metadata:map[labels:map[component:application-connector installer:overrides kyma-project.io/installation:] name:application-connector-tests namespace:kyma-installer]] map[apiVersion:v1 data:map[compassRuntimeAgent.tests.enabled:false] kind:ConfigMap metadata:map[labels:map[component:compass-runtime-agent installer:overrides kyma-project.io/installation:] name:compass-runtime-agent-tests namespace:kyma-installer]] map[apiVersion:v1 data:map[kubeless.tests.enabled:false] kind:ConfigMap metadata:map[labels:map[component:core installer:overrides kyma-project.io/installation:] name:core-tests namespace:kyma-installer]] map[apiVersion:installer.kyma-project.io/v1alpha1 kind:Installation metadata:map[finalizers:[finalizer.installer.kyma-project.io] labels:map[kyma-project.io/installation:] name:kyma-installation namespace:default] spec:map[components:[map[name:cluster-essentials namespace:kyma-system] map[name:testing namespace:kyma-system] map[name:istio-init namespace:istio-system] map[name:istio namespace:istio-system] map[name:xip-patch namespace:kyma-installer] map[name:istio-kyma-patch namespace:istio-system] map[name:knative-serving-init namespace:knative-serving] map[name:knative-serving namespace:knative-serving] map[name:knative-eventing namespace:knative-eventing] map[name:dex namespace:kyma-system] map[name:ory namespace:kyma-system] map[name:api-gateway namespace:kyma-system] map[name:rafter namespace:kyma-system] map[name:service-catalog namespace:kyma-system] map[name:service-catalog-addons namespace:kyma-system] map[name:helm-broker namespace:kyma-system] map[name:nats-streaming namespace:natss] map[name:core namespace:kyma-system] map[name:permission-controller namespace:kyma-system] map[name:knative-provisioner-natss namespace:knative-eventing] map[name:event-bus namespace:kyma-system] map[name:event-sources namespace:kyma-system] map[name:application-connector-ingress namespace:kyma-system] map[name:application-connector-helper namespace:kyma-integration] map[name:application-connector namespace:kyma-integration]] url:__URL__ version:__VERSION__]]]' command  with output 'error: unable to recognize "STDIN": no matches for kind "Installation" in version "installer.kyma-project.io/v1alpha1"
' and error message 'exit status 1' failed
    ~/.kube  kyma install                                                                                                                                                                                      1 ✘  took 35s   at 22:21:07 
- Cluster info read
- Configurations validated
  Installing Kyma in version '1.10.0'
- Installation source checked
/ Validating configurations - Tiller deployed
- Installation files loaded
X Deploying Kyma Installer
Error: Executing kubectl 'kubectl apply -f -[map[apiVersion:v1 kind:Namespace metadata:map[labels:map[istio-injection:disabled kyma-project.io/installation:] name:kyma-installer]] map[apiVersion:v1 kind:LimitRange metadata:map[labels:map[kyma-project.io/installation:] name:kyma-default namespace:kyma-installer] spec:map[limits:[map[default:map[memory:256Mi] defaultRequest:map[memory:32Mi] max:map[memory:1024Mi] type:Container]]]] map[apiVersion:apiextensions.k8s.io/v1beta1 kind:CustomResourceDefinition metadata:map[labels:map[kyma-project.io/installation:] name:installations.installer.kyma-project.io] spec:map[group:installer.kyma-project.io names:map[kind:Installation plural:installations shortNames:[installation] singular:installation] scope:Namespaced version:v1alpha1]] map[apiVersion:apiextensions.k8s.io/v1beta1 kind:CustomResourceDefinition metadata:map[labels:map[kyma-project.io/installation:] name:releases.release.kyma-project.io] spec:map[group:release.kyma-project.io names:map[kind:Release plural:releases shortNames:[release] singular:release] scope:Namespaced version:v1alpha1]] map[apiVersion:v1 kind:ServiceAccount metadata:map[name:helm-certs-job-sa namespace:kyma-installer]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:RoleBinding metadata:map[name:helm-certs-rolebinding namespace:kube-system] roleRef:map[apiGroup:rbac.authorization.k8s.io kind:Role name:helm-certs-getter] subjects:[map[kind:ServiceAccount name:helm-certs-job-sa namespace:kyma-installer]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:RoleBinding metadata:map[name:helm-certs-rolebinding namespace:kyma-installer] roleRef:map[apiGroup:rbac.authorization.k8s.io kind:Role name:helm-certs-setter] subjects:[map[kind:ServiceAccount name:helm-certs-job-sa namespace:kyma-installer]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:Role metadata:map[name:helm-certs-getter namespace:kube-system] rules:[map[apiGroups:[] resources:[secrets] verbs:[get list]]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:Role metadata:map[name:helm-certs-setter namespace:kyma-installer] rules:[map[apiGroups:[] resources:[secrets] verbs:[get list create patch]]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:ClusterRole metadata:map[name:all-psp] rules:[map[apiGroups:[policy/v1beta1] resources:[podsecuritypolicies] verbs:[use]]]] map[apiVersion:rbac.authorization.k8s.io/v1 kind:ClusterRoleBinding metadata:map[name:all-psp] roleRef:map[apiGroup:rbac.authorization.k8s.io kind:ClusterRole name:all-psp] subjects:[map[kind:ServiceAccount name:helm-certs-job-sa namespace:kyma-installer]]] map[apiVersion:batch/v1 kind:Job metadata:map[labels:map[kyma-project.io/installation:] name:helm-certs-job namespace:kyma-installer] spec:map[template:map[metadata:map[annotations:map[sidecar.istio.io/inject:“false”] name:helm-certs-job namespace:kyma-installer] spec:map[containers:[map[command:[bash -c WORKING_DIR="/tmp/certs"
mkdir -p "${WORKING_DIR}"

cat <<EOF > "${WORKING_DIR}/openssl.cnf"
[ req ]
#default_bits   = 2048
#default_md   = sha256
#default_keyfile  = privkey.pem
distinguished_name  = req_distinguished_name
attributes    = req_attributes

[ req_distinguished_name ]
countryName     = Country Name (2 letter code)
countryName_min     = 2
countryName_max     = 2
stateOrProvinceName   = State or Province Name (full name)
localityName      = Locality Name (eg, city)
0.organizationName    = Organization Name (eg, company)
organizationalUnitName    = Organizational Unit Name (eg, section)
commonName      = Common Name (eg, fully qualified host name)
commonName_max      = 64
emailAddress      = Email Address
emailAddress_max    = 64

[ req_attributes ]
challengePassword   = A challenge password
challengePassword_min   = 4
challengePassword_max   = 20
[ v3_ca ]
basicConstraints = critical,CA:TRUE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
EOF

echo "---> Get Tiller CA"
if [[ $(kubectl get -n kube-system secret tiller-secret) ]] ; then
  kubectl get -n kube-system secret tiller-secret -o jsonpath="{.data['ca\.crt']}" | base64 --decode > "${WORKING_DIR}/ca.crt"
  kubectl get -n kube-system secret tiller-secret -o jsonpath="{.data['ca\.key']}" | base64 --decode > "${WORKING_DIR}/ca.key"
else
  echo "Secret: tiller-secret does not exists!"
  exit 1
fi

echo "---> Generate Helm key"
openssl genrsa -out "${WORKING_DIR}/helm.key.pem" 4096
openssl req -key "${WORKING_DIR}/helm.key.pem" -new -sha256 -out "${WORKING_DIR}/helm.csr.pem" -subj "/C=PL/ST=Gliwice/L=Gliwice/O=Helm Client/CN=helm-client"
openssl x509 -req -CA "${WORKING_DIR}/ca.crt" -CAkey "${WORKING_DIR}/ca.key" -CAcreateserial -in "${WORKING_DIR}/helm.csr.pem" -out "${WORKING_DIR}/helm.cert.pem" -days 365

echo "---> Create secrets in k8s"
COMBO_YAML=$(cat << EOF
---
apiVersion: v1
data:
  global.helm.ca.crt: "$(base64 "${WORKING_DIR}/ca.crt" | tr -d '\n')"
  global.helm.tls.crt: "$(base64 ${WORKING_DIR}/helm.cert.pem | tr -d '\n')"
  global.helm.tls.key: "$(base64 ${WORKING_DIR}/helm.key.pem | tr -d '\n')"
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    installer: overrides
    kyma-project.io/installation: ""
  name: helm-secret
  namespace: kyma-installer
type: Opaque
EOF
)

echo "${COMBO_YAML}" | kubectl create -f -
] image:eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20190325-ff66a3a name:certhelper]] restartPolicy:OnFailure serviceAccountName:helm-certs-job-sa]]]] map[apiVersion:v1 kind:ServiceAccount metadata:map[labels:map[kyma-project.io/installation:] name:kyma-installer namespace:kyma-installer]] map[apiVersion:apps/v1 kind:Deployment metadata:map[labels:map[kyma-project.io/installation: name:kyma-installer] name:kyma-installer namespace:kyma-installer] spec:map[selector:map[matchLabels:map[name:kyma-installer]] template:map[metadata:map[labels:map[name:kyma-installer]] spec:map[containers:[map[args:[-tillerTLSInsecureSkipVerify=true] image:eu.gcr.io/kyma-project/kyma-installer:1.10.0 imagePullPolicy:IfNotPresent name:kyma-installer-container volumeMounts:[map[mountPath:/etc/certs name:helm-certs readOnly:%!s(bool=true)]]]] serviceAccountName:kyma-installer volumes:[map[name:helm-certs secret:map[items:[map[key:global.helm.tls.crt path:tls.crt] map[key:global.helm.tls.key path:tls.key]] secretName:helm-secret]]]]]]] map[apiVersion:rbac.authorization.k8s.io/v1beta1 kind:ClusterRole metadata:map[labels:map[kyma-project.io/installation:] name:kyma-installer-reader] rules:[map[apiGroups:[*] resources:[*] verbs:[*]]]] map[apiVersion:rbac.authorization.k8s.io/v1beta1 kind:ClusterRoleBinding metadata:map[labels:map[kyma-project.io/installation:] name:kyma-installer] roleRef:map[apiGroup:rbac.authorization.k8s.io kind:ClusterRole name:kyma-installer-reader] subjects:[map[kind:ServiceAccount name:kyma-installer namespace:kyma-installer]]] map[apiVersion:v1 data:map[global.applicationConnectorCa: global.applicationConnectorCaKey:] kind:Secret metadata:map[labels:map[installer:overrides kyma-project.io/installation:] name:application-connector-certificate-overrides namespace:kyma-installer] type:Opaque] map[apiVersion:v1 data:map[global.tlsCrt:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU4RENDQXRpZ0F3SDhWa24yeFNlV2kKVm1hVW5TSDBTZ2tlUENMRnlra25yQzgxU2pXZkRBMD0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=] kind:ConfigMap metadata:map[labels:map[installer:overrides kyma-project.io/installation:] name:cluster-certificate-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[global.adminPassword: global.domainName:kyma.local global.isLocalEnv:true global.minikubeIP: nginx-ingress.controller.service.loadBalancerIP:] kind:ConfigMap metadata:map[labels:map[installer:overrides kyma-project.io/installation:] name:installation-config-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[gateways.istio-ingressgateway.autoscaleEnabled:false gateways.istio-ingressgateway.loadBalancerIP: gateways.istio-ingressgateway.type:NodePort mixer.loadshedding.mode:disabled mixer.policy.autoscaleEnabled:false mixer.policy.resources.limits.cpu:500m mixer.policy.resources.limits.memory:2048Mi mixer.policy.resources.requests.cpu:300m mixer.policy.resources.requests.memory:512Mi mixer.telemetry.autoscaleEnabled:false mixer.telemetry.resources.limits.cpu:500m mixer.telemetry.resources.limits.memory:2048Mi mixer.telemetry.resources.requests.cpu:300m mixer.telemetry.resources.requests.memory:512Mi pilot.autoscaleEnabled:false pilot.resources.limits.cpu:500m pilot.resources.limits.memory:1024Mi pilot.resources.requests.cpu:250m pilot.resources.requests.memory:512Mi] kind:ConfigMap metadata:map[labels:map[component:istio installer:overrides kyma-project.io/installation:] name:istio-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[etcd-stateful.etcd.resources.limits.memory:256Mi etcd-stateful.replicaCount:1] kind:ConfigMap metadata:map[labels:map[component:service-catalog installer:overrides kyma-project.io/installation:] name:service-catalog-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[global.isDevelopMode:true] kind:ConfigMap metadata:map[labels:map[component:helm-broker installer:overrides kyma-project.io/installation:] name:helm-broker-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[telemetry.enabled:false] kind:ConfigMap metadata:map[labels:map[component:dex installer:overrides kyma-project.io/installation:] name:dex-overrides namespace:kyma-installer]] map[apiVersion:v1 data:map[application-operator.tests.enabled:false application-registry.tests.enabled:false connector-service.tests.enabled:false tests.application_connector_tests.enabled:false] kind:ConfigMap metadata:map[labels:map[component:application-connector installer:overrides kyma-project.io/installation:] name:application-connector-tests namespace:kyma-installer]] map[apiVersion:v1 data:map[compassRuntimeAgent.tests.enabled:false] kind:ConfigMap metadata:map[labels:map[component:compass-runtime-agent installer:overrides kyma-project.io/installation:] name:compass-runtime-agent-tests namespace:kyma-installer]] map[apiVersion:v1 data:map[kubeless.tests.enabled:false] kind:ConfigMap metadata:map[labels:map[component:core installer:overrides kyma-project.io/installation:] name:core-tests namespace:kyma-installer]] map[apiVersion:installer.kyma-project.io/v1alpha1 kind:Installation metadata:map[finalizers:[finalizer.installer.kyma-project.io] labels:map[kyma-project.io/installation:] name:kyma-installation namespace:default] spec:map[components:[map[name:cluster-essentials namespace:kyma-system] map[name:testing namespace:kyma-system] map[name:istio-init namespace:istio-system] map[name:istio namespace:istio-system] map[name:xip-patch namespace:kyma-installer] map[name:istio-kyma-patch namespace:istio-system] map[name:knative-serving-init namespace:knative-serving] map[name:knative-serving namespace:knative-serving] map[name:knative-eventing namespace:knative-eventing] map[name:dex namespace:kyma-system] map[name:ory namespace:kyma-system] map[name:api-gateway namespace:kyma-system] map[name:rafter namespace:kyma-system] map[name:service-catalog namespace:kyma-system] map[name:service-catalog-addons namespace:kyma-system] map[name:helm-broker namespace:kyma-system] map[name:nats-streaming namespace:natss] map[name:core namespace:kyma-system] map[name:permission-controller namespace:kyma-system] map[name:knative-provisioner-natss namespace:knative-eventing] map[name:event-bus namespace:kyma-system] map[name:event-sources namespace:kyma-system] map[name:application-connector-ingress namespace:kyma-system] map[name:application-connector-helper namespace:kyma-integration] map[name:application-connector namespace:kyma-integration]] url:__URL__ version:__VERSION__]]]' command  with **output 'error: unable to recognize "STDIN": no matches for kind "Installation" in version "installer.kyma-project.io/v1alpha1"
' and error message 'exit status 1' failed**

Any idea? 

runnig comand `kubectl get installation/kyma-installation -o jsonpath='{.status.state}'`  provide this error: error: the server doesn't have a resource type "installation"

**Comment by astrixj** [comment] 2020-03-30 06:20
I try to install it either , on mac-book pro Catalina , and got the same results , output 'error: unable to recognize "STDIN": no matches for kind "Installation" in version "installer.kyma-project.io/v1alpha1"
' and error message 'exit status 1' failed . is there any workaround  to install it on minikube ?

**Comment by a-thaler** [comment] 2020-03-30 07:58
Hi @SofiaTa ,
thanks for your feedback, the issue is already known from https://github.com/kyma-project/kyma/issues/7079
As more people seem to face it, I will see that we address it with next release.
I will close this ticket as duplicate. However, please try to repeat the install command and let us know in the ticket if that helped.

**Closed by a-thaler** 2020-03-30 07:58 UTC

**Comment by SofiaTa** [comment] 2020-03-30 08:03
@a-thaler - I already saw that however there is no solution there or some workaround ...any new info what I should try to overcome this ?
