### ISSUE TITLE
Removal of Application Connector Kubernetes Services

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#4665] opened 2019-06-27 13:42 UTC
**Description**

Dear Colleagues,

on Kyma 1.2 removing an application does not remove the corresponding Kubernetes Services. This has an impact on Istio (Sidecar) Memory Consumption.

Please fix.

Thanks

Andreas 

**Expected result**

When a Kyma Application is removed, also the corresponding Services should be removed

**Actual result**

Services remain alive

**Steps to reproduce**

Create an application, register services, delete the application. Then issue:

`kubectl get svc -n kyma-integration`

**Troubleshooting**

Delete Services manually

**Comment by a-thaler** [comment] 2019-06-28 08:26
Duplicate of https://github.com/kyma-project/kyma/issues/3515

**Closed by a-thaler** 2019-06-28 08:26 UTC
Labels: duplicate
