### ISSUE TITLE
Upgrade knative-serving to 0.14(latest ATM)

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#8351] opened 2020-05-04 11:40 UTC
**Description**

The objective is to upgrade knative-serving to 0.14([latest](https://github.com/knative/serving/releases/tag/v0.14.0), at the time of writing).

**Reasons**

This will solve: https://github.com/kyma-project/kyma/issues/8280

**Comment by michal-hudy** [comment] 2020-05-04 15:00
Duplicate of https://github.com/kyma-project/kyma/issues/7854

**Closed by michal-hudy** 2020-05-04 15:00 UTC
Labels: area/serverless
