### ISSUE TITLE
The status of NodeJS function changes to "deploying" when load test, and performance become to be poor

### ISSUE THREAD

**Issue by wh7577** [kyma-project/kyma#12005] opened 2021-09-01 03:00 UTC
I installed Kyma 1.24.3 in azure, and created 3 nodes AKS using Standard_D8s_v3. When I test the performance of helloworld function (NodeJS default), the status of helloworld function will changed to "deploying" from time to time. And the performance become to be poor, from 30ms(when start) downgrade to 1000+ ms, and error "context deadline exceeded (Client.Timeout exceeded while awaiting headers)" shows in azure. 

AKS Kubernetes versions: 1.20.7
Kyma version : 1.24.3
Load Test tool : JMeter 5.4.1

**Expected result**
Status should be running and not change, the helloworld performance should be under 50 ms.

**Actual result**
Status changed to "deploying" from time to time, and the performance become to poor, from 30ms (when start) downgrade to 1000+ ms.

**Steps to reproduce**
1. create NodeJS function, set 3 replicas
2. perform load test by JMeter by 200 concurrent threads

**Troubleshooting**
See attached screendump.
![nodejs12-helloworld-become-to-deploying](https://user-images.githubusercontent.com/3860078/131604547-69d5a072-2674-46cc-9dd9-b78d362a2b18.png)
![nodejs12-helloworld-containers-not-ready](https://user-images.githubusercontent.com/3860078/131604549-9476d37a-9b25-4ebc-bc67-e98d2c45d1e0.png)
![nodejs12-helloworld-context-deadline-exceed](https://user-images.githubusercontent.com/3860078/131604551-d2dc6437-0973-4ede-9bfc-77b1f01db890.png)
![nodejs12-helloworld-function](https://user-images.githubusercontent.com/3860078/131604552-5537b0ba-d258-4cb0-8f9d-bb7631ff4674.png)
![nodejs12-helloworld-performance (3 pods)](https://user-images.githubusercontent.com/3860078/131604554-62b9a35e-c909-4264-92bd-5a224d30e569.png)
![nodejs12-helloworld-pods-config](https://user-images.githubusercontent.com/3860078/131604556-f1698129-d891-4218-8764-5069c3f8b4f4.png)
![nodejs12-helloworld-pod-warning-in-azure](https://user-images.githubusercontent.com/3860078/131604557-b275c71f-f07b-4e90-8ff1-db85a3fd7e4b.png)

**Comment by kwiatekus** [comment] 2021-09-02 08:35
Hi @wh7577 thanks for checking.
I believe this could be happening because the function pods are hit with OOM and kubernetes is trying to redeploy them.
Could you check if you see any k8s events when calling `kubectl describe` against the function pods?

If that's the case the remedy could be to increate the runtime profile of the function to L ( or custom one ) to increase the resource allocation for the function runtime.
https://kyma-project.io/docs/components/serverless/#details-available-presets

If you use  Kyma UI you can manage function runtime resources under `Resources` tab
![Screen Shot 2021-09-02 at 10 32 54](https://user-images.githubusercontent.com/6783567/131810878-a428a862-7d8c-439f-b6ca-0286b5d5ab9d.png)
If you use Kyma CLI you can manage resources as part of the config.yaml file
Here is a description
https://kyma-project.io/docs/cli/#details-function-configuration-file

**Comment by dbadura** [comment] 2021-09-02 08:50
Hello,
as @kwiatekus mention, you can try to change the runtime profile to something bigger.
Here are results of our performance test: https://github.com/kyma-project/kyma/issues/10154
Nodejs function can handle about 35 request/s. Having 3 replicas means 105 r/s.
As far as I understand, jmeter can throw up to 200 parallel request, which is to many for the functions and those functions are killed because the cannot respond to anything under 1 second, even `healthz`.

**Comment by wh7577** [comment] 2021-09-02 09:48
@kwiatekus It should be kubernetes is trying to redeploy them, but no OOM events found.
![image](https://user-images.githubusercontent.com/3860078/131822443-5ff3bf86-3650-4f41-aa95-298ffa812197.png)

**Comment by dbadura** [comment] 2021-09-03 07:56
The problem here is `heatlhz` and function which is too busy to respond, not OOM.
Change the profile of function to something bigger than `L`.

**Comment by kwiatekus** [comment] 2021-09-06 09:30
I will close it. @wh7577 Feel free to re-open and contact us again in case vertical scaling of function resources didn't help

**Comment by wh7577** [comment] 2021-09-07 01:35
Why close it ? If I use springboot deploy as 3 pods using same resources, no error found, and the performance is also more better than NodeJS. 
I also increased 3 nodes to 5 nodes in NodeJS,  the error frequency downgraded,  but this error still occurs.

**Comment by wh7577** [comment] 2021-09-07 01:43
I think Kyma should allow customize the http probe timeout setting by deployment/pod, instead of by default setting.

**Comment by wh7577** [comment] 2021-09-08 03:21
> I will close it. @wh7577 Feel free to re-open and contact us again in case vertical scaling of function resources didn't help

Don't close it. Pls check below my comments.

**Comment by wh7577** [comment] 2021-09-11 07:34
@kwiatekus can you check my comments

**Comment by kwiatekus** [comment] 2021-09-14 06:39
> I also increased 3 nodes to 5 nodes in NodeJS
Do you mean replicas of the function pods? That would be my next suggestion to change the resource config for the function increase the min replicas for the function under load.

The replication ( HPA ) should happen. [`APP_FUNCTION_TARGET_CPU_UTILIZATION_PERCENTAGE`](https://github.com/kyma-project/kyma/blob/8627183dcd62063305c37c14087c89a9ddcda142/components/function-controller/README.md) controls scaling  upon CPU utilisation. But clearly CPU utilisation is not the valid criteria for replication in your case and the response from health check gets too long which makes the kubernetes to restart the pod even before replication kicks in.
[We want to improve it](https://github.com/kyma-project/kyma/issues/11225)
Also we want to enable to plug in [external scalers](https://github.com/kyma-project/kyma/issues/11997), i.e KEDA that would allow for various scaling strategies.

We need to fine tune it.

Have you checked the function dashboard at the grafana?
![Screen Shot 2021-09-14 at 08 37 58](https://user-images.githubusercontent.com/6783567/133207720-9c906fa0-20bb-4006-bd75-6d1a27f86992.png)
![Screen Shot 2021-09-14 at 08 38 36](https://user-images.githubusercontent.com/6783567/133207731-d300b6b0-981c-4390-8ca7-bfc2cd7dbbb3.png)

It would be interesting to check whether any of the metrics that are available for scaling ootb ( cpu or memory consumption ) is close to the limit before the restart happens

**Comment by kwiatekus** [comment] 2021-09-14 14:42
> The problem here is `heatlhz` and function which is too busy to respond, not OOM.
By observing readiness endpoint, k8s decides to restart container already after 1 failure.
I have tested a CPU intensive function ( fibonacci calculation ) and I can reproduce it.

By increasing failure threshold I get much more stable setup. I'm not yet sure if its the right approach though

**Comment by kwiatekus** [comment] 2021-09-15 12:09
While we still work on a PR that would resolve the issue, here is a patch that could be applied on the deployment ( resulting from a function ). 

[deployment-patch.yaml.txt](https://github.com/kyma-project/kyma/files/7169868/deployment-patch.yaml.txt)
The patch
 - increases the timeout and failure threshold to the readiness probe
 - adds a liveness probe which is much more tolerant 
This helps to distinguish busy pods(that need to be excluded from traffic routing) from dead pods (that need to be restarted)
 
`kubectl patch deployment {deployment name} -n {namespace} --patch "$(cat deployment-patch.yaml)"`
 
 This, plus bumping minReplicas (~3) and maxReplicas (~6) on the function should have a positive impact on the performance

**Comment by kwiatekus** [comment] 2021-09-17 10:06
Currently there is no dedicated condition that indicates that minimum availibility condition of replicas (of the function's deployment) is not satisfied.
Function controller interprets it as `Deploying`, which is wrong.
Proposed changes introduce new function condition `Unhealthy`. Function enters this condition whenever k8s isolates (based on readiness probe) such amount of replicas that makes the minimum available replicas (by default 75%) condition not satisfied.

![Screen Shot 2021-09-17 at 11 59 05](https://user-images.githubusercontent.com/6783567/133765518-02e16719-e596-4ff7-8369-53d7f185485d.png)

**Closed** 2021-09-17 14:21 UTC
Labels: bug, area/serverless
