### ISSUE TITLE
Improve Application deletion process

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#4639] opened 2019-06-26 08:06 UTC
**Description**

Improve Application deletion process. There are two issues with Application deletion:

- there are leftovers after deleting an Application such as services and deniers
- there is no mechanism protecting against accidental Application deletion with the whole setup

**Acceptance criteria**

- investigate what Application resources are still running after its deletion
- search for possibilities of deleting the resources automatically when the Application is being deleted
  - I suggest to look at the [Garbage Collection](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/) Kubernetes mechanism
- implement the mechanism of automatic resources deletion

- search for possibilities of protecting against accidental Application deletion with the whole setup
  - [there](https://github.com/kyma-project/kyma/issues/940#issuecomment-494419240) was a suggestion to add some kind of `--force` flag to the Kyma API
- implement the Application deleting protection mechanism 

- document the Application deletion process well

**Comment by janmedrek** [comment] 2020-05-15 12:56
Duplicate of: https://github.com/kyma-project/kyma/issues/3728

**Closed by janmedrek** 2020-05-15 12:56 UTC
Labels: Epic, area/application-connector, enhancement, wontfix
