### ISSUE TITLE
Uninstallation leaves resources

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#2554] opened 2019-02-04 09:37 UTC
**Description**

Uninstalling kyma leaves some resources, which causes the next installation to fail. 
Resources in question:
- `resourcequotas "kyma-default" already exists`

**Expected result**
Uninstallation of kyma leaves the cluster in a clean state

**Actual result**
There are leftovers that block next installation

**Steps to reproduce**

**Troubleshooting**

**Comment by sjanota** [comment] 2019-02-05 08:16
Closing as duplicate of #1826

**Closed by sjanota** 2019-02-05 08:16 UTC
Labels: area/installation, bug
