### ISSUE TITLE
nkyma Gardener cluster with Kyma 2.0 is broken

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/kyma#12269] opened 2021-10-04 12:58 UTC
**Description**

nkyma Gardener cluster is broken (e.g. there is no Function CRD) - probably uninstall does not work properly
Failing jobs: https://status.build.kyma-project.io/?job=*gcp-busola-kyma

**Comment by a-thaler** [comment] 2021-10-04 13:03
Duplicate of https://github.com/kyma-project/kyma/issues/12261

**Closed by a-thaler** 2021-10-04 13:03 UTC
Labels: bug, area/cli, test-failing
