### ISSUE TITLE
Istio dashboards in grafana are not displaying information properly

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#6973] opened 2020-01-24 07:23 UTC
**Description**

The istio dashboards in grafana are not displaying all confiured metrics as they should, a lot of charts are simply empty, like the "Istio Pilot Dashboard". On looking into the upstream charts they are also not correct. The charts in the kyma need to be fixed so that we have the information in grafana.

**Expected result**

Istio dashboards show all configured metrics and have no empty charts.

**Actual result**

The dashboards are not displaying any info

**Comment by piotrmsc** [comment] 2020-02-14 07:05
Closing as duplicate of https://github.com/kyma-project/kyma/issues/6440

**Closed by piotrmsc** 2020-02-14 07:05 UTC
Labels: area/monitoring, area/service-mesh, bug
