### ISSUE TITLE
Sometimes Kyma eventing pods fail to connect to API server with mTLS timeout

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3899] opened 2019-04-29 15:09 UTC
**Description**
As reported by one of the colleagues, his lambda was not getting triggered by the events.

On inspecting it was found that the `nats-dispatcher` component has become inactive and not reacting to the creation of Knative Subscriptions. This caused the underlying NATS Streaming Subscription to be not created.
Only a restart of the `nats-dispatcher` fixed the issue.

Looking at the logs, it was observed that the event bus pods were not able to connect to APIServer and failing with TLS timeout.

After talking to @piotrmiskiewicz , it seems the problem is with the Istio-pilot taking time to propagate the configuration to the sidecars which should tell envoy to not use mTLS for APIServer configuration.

From a customer and developer experience, this is not acceptable to tell them to restart the PODs.
This problem should be auto-resolved by the Kyma or event bus.

**Comment by sayanh** [comment] 2019-07-12 12:48
This cannot be reproduced so far. A cluster which is 3 days old still works meaning the event-bus-e2e-tester works fine. I have a job set up which runs the tests periodically and posts results to #sayan-test slack channel. I believe this issue can only be debugged when it starts happening in this cluster. As I understood this usually happens when a cluster is really old so I will keep an eye on this.

In the meantime, I think a readiness/liveness probe could solve this as `restart the PODs` seems to be bringing nats-dispatcher to working state.

**Comment by sayanh** [comment] 2019-08-02 12:43
Couldn't reproduce this hence closing it for now.

**Closed by sayanh** 2019-08-02 12:43 UTC
Labels: area/eventing, bug
