### ISSUE TITLE
Application-connector component installation fails on Apple M1 SoC

### ISSUE THREAD

**Issue by werdes72** [kyma-project/kyma#14617] opened 2022-06-20 07:21 UTC
Kyma 2.3.0 installation fails on Apple M1 SoC because of application-connector component.

Additional log:
```
2022-06-17T13:02:06.383+0200	INFO	progress/tracker.go:120	Stop checking progress of resource transition to state 'ready' because parent context got closed
2022-06-17T13:02:06.383+0200	DEBUG	invoker/localinvoker.go:73	Local invoker has Status-func configured: sending status-update 'error' (error: 'context deadline exceeded') for component 'application-connector' to caller
2022-06-17T13:02:06.384+0200	ERROR	progress/tracker.go:249	Tracker stopped checking the progress of the following resource: Deployment [namespace:kyma-integration|name:application-broker]. Failed to get resource: context deadline exceeded
2022-06-17T13:02:06.384+0200	INFO	progress/tracker.go:252	Tracker stopped checking the progress of the following resource: Deployment [namespace:kyma-integration|name:application-broker]. Resource state: 
2022-06-17T13:02:06.384+0200	ERROR	progress/tracker.go:249	Tracker stopped checking the progress of the following resource: Deployment [namespace:kyma-system|name:central-application-gateway]. Failed to get resource: context deadline exceeded
2022-06-17T13:02:06.384+0200	INFO	progress/tracker.go:252	Tracker stopped checking the progress of the following resource: Deployment [namespace:kyma-system|name:central-application-gateway]. Resource state: 
2022-06-17T13:02:06.384+0200	ERROR	progress/tracker.go:249	Tracker stopped checking the progress of the following resource: StatefulSet [namespace:kyma-integration|name:application-operator]. Failed to get resource: context deadline exceeded
2022-06-17T13:02:06.384+0200	INFO	progress/tracker.go:252	Tracker stopped checking the progress of the following resource: StatefulSet [namespace:kyma-integration|name:application-operator]. Resource state: 
2022-06-17T13:02:06.384+0200	WARN	service/install.go:66	Failed to deploy manifests on target cluster: Running resource transition to state 'ready' was not completed: transition is treated as failed
2022-06-17T13:02:06.384+0200	DEBUG	service/runner.go:187	Runner: Default-reconcile action of 'application-connector' with version '2.3.0' failed: Running resource transition to state 'ready' was not completed: transition is treated as failed
2022-06-17T13:02:06.384+0200	WARN	service/runner.go:94	Runner: failing reconciliation of 'application-connector' in version '2.3.0' with profile '': Running resource transition to state 'ready' was not completed: transition is treated as failed
2022-06-17T13:02:06.384+0200	DEBUG	invoker/localinvoker.go:107	Local invoker is updating operation (schedulingID:local--c4e0ffbc-16cf-4df4-9a8e-1372ff429b50/correlationID:local--52924546-10cc-423a-aa32-9888a8a6ab33) to state 'error': context deadline exceeded
2022-06-17T13:02:06.385+0200	DEBUG	heartbeat/heartbeat.go:100	Heartbeat communicated status 'error' successfully to mothership-reconciler
2022-06-17T13:02:06.400+0200	WARN	service/status.go:71	Error getting ConfigMap 'application-connector-status': context deadline exceeded
2022-06-17T13:02:06.400+0200	WARN	service/runner.go:141	Reconciler Metrics not initialized
2022-06-17T13:02:06.400+0200	ERROR	service/runner.go:123	Runner: reconciliation of component 'application-connector' for version '2.3.0' terminated because context was closed
2022-06-17T13:02:06.400+0200	WARN	worker/worker.go:69	Worker stops processing operation 'OperationEntity [SchedulingID=local--c4e0ffbc-16cf-4df4-9a8e-1372ff429b50,CorrelationID=local--52924546-10cc-423a-aa32-9888a8a6ab33,RuntimeID=local,ClusterConfig=1,Component=application-connector,Prio=2,State=new,Type=reconcile]' because invoker returned consistently errors (1 retries): All attempts fail:
#1: context deadline exceeded
2022-06-17T13:02:06.400+0200	WARN	worker/workerpool.go:137	Worker pool received an error from worker assigned to operation 'OperationEntity [SchedulingID=local--c4e0ffbc-16cf-4df4-9a8e-1372ff429b50,CorrelationID=local--52924546-10cc-423a-aa32-9888a8a6ab33,RuntimeID=local,ClusterConfig=1,Component=application-connector,Prio=2,State=new,Type=reconcile]': All attempts fail:
#1: context deadline exceeded
2022-06-17T13:02:07.382+0200	DEBUG	worker/workerpool.go:91	Worker pool is waiting for 1 workers to be finished
2022-06-17T13:02:08.382+0200	DEBUG	worker/workerpool.go:80	Worker pool has no running workers
2022-06-17T13:02:08.382+0200	DEBUG	worker/workerpool.go:142	Worker pool is checking for processable operations (max parallel ops per cluster: 25)
2022-06-17T13:02:08.398+0200	DEBUG	worker/workerpool.go:152	Worker pool found 0 processable operations: 
2022-06-17T13:02:08.398+0200	DEBUG	worker/workerpool.go:87	Worker pool invoked all processable operations
2022-06-17T13:02:08.398+0200	INFO	worker/workerpool.go:62	Stopping worker pool
2022-06-17T13:02:08.398+0200	INFO	service/run.go:128	Worker pool finished successfully
2022-06-17T13:02:08.398+0200	INFO	step/log.go:62	Deploying Kyma

Deployed Components: [0;33;1m1/2
[0mCould not deploy the following components:
- application-connector

Error: kyma deployment failed
```

Steps to reproduce:
Install Kyma 2.3.0 on Apple M1 k3d cluster.

**Comment by janmedrek** [comment] 2022-07-13 08:58
Closing this one as the issue is related to Istio's sidecars, if something more pops up - feel free to reopen.
https://github.com/kyma-project/kyma/issues/14797

**Closed by janmedrek** 2022-07-13 08:58 UTC
Labels: area/application-connector
