### ISSUE TITLE
Change Jaeger storage from in-memory to persistence storage 

### ISSUE THREAD

**Issue by hisarbalik** [kyma-project/kyma#5189] opened 2019-08-05 05:56 UTC
Description

Current tracing setup with Jaeger using in-memory stirage instead of persistence storage, in order to optimize memory usage we need to switch from in-memory storage to persistence storage.
 
Reasons
Optimize Kyma resources usage

**Comment by clebs** [comment] 2019-08-05 11:38
Duplicate of #4542

**Closed by clebs** 2019-08-05 11:38 UTC
Labels: area/tracing, quality/performance, quality/robustness
