### ISSUE TITLE
Kyma deploy: Component 'certificates' failed

### ISSUE THREAD

**Issue by dvankempen** [kyma-project/kyma#13058] opened 2022-01-13 09:59 UTC
**Description**

When deploying Kyma 2.0 on k3d the component 'certificates' fails with message

_no matches for kind “Gateway” in version “networking.istio.io/v1apha3”_

Second attempt is successful. 

k3d (macOS Monterey and Windows 2019)
Kyma 2.0

MacBook Pro with 6 core CPU and 16 GB RAM
Windows 2019 with 8 CPU and 32 GB RAM

**Expected result**

No error messages during deployment

**Actual result**

Error message

**Steps to reproduce**

Consistent behaviour running k3d on macOS Monterey and Windows Server 2019. See

- https://blogs.sap.com/2021/12/23/install-kyma-sap-btp-kyma-runtime-getting-started/
- https://kyma-community.slack.com/archives/CD2HJ0E78/p1640594532013100

**Troubleshooting**

First occurrence on macOS. Issue could be reproduced on Windows 2019.

**Comment by strekm** [comment] 2022-01-19 08:01
@dvankempen thank you for reporting that. we are aware of this problem which is caused by a fact that certificates component is a part of pre-requisites components list along with istio. at this moment components are getting installed in parallel and since istio takes some time to install certificates components complains that istio gateway CRD is not there yet. on second run istio is fully installed including CRDs so kyma-gateway can be installed without any troubles as well.  we plan to fix this behaviour with small restructuring of components. feel free to track progress on https://github.com/kyma-incubator/reconciler/issues/543 which is planned to be rolled out with kyma 2.1

Cheers, 
Magda

**Comment by strekm** [comment] 2022-03-22 12:08
implemented with https://github.com/kyma-incubator/reconciler/issues/543, will be released with kyma 2.1

**Closed by strekm** 2022-03-22 12:08 UTC
Labels: kind/bug, area/service-mesh, area/installation
