### ISSUE TITLE
Installation of Kyma from Windows 10 into a GCP Kubernates cluster failed

### ISSUE THREAD

**Issue by admiralsmaster** [kyma-project/kyma#8249] opened 2020-04-27 08:43 UTC
**Description**

Installation of Kyma from Windows 10 into a GCP Kubernates cluster failed with 
```
error: unable to recognize "https://github.com/kyma-project/kyma/releases/download/1.11.1/kyma-installer-cluster.yaml": no matches for kind "Installation" in version "installer.kyma-project.io/v1alpha1"
```

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.9", GitCommit:"e1af17fd873e15a48769e2c7b9851405f89e3d0d", GitTreeState:"clean", BuildDate:"2020-04-06T20:56:54Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

$ gcloud version
Google Cloud SDK 290.0.0
bq 2.0.56
core 2020.04.21
gsutil 4.49

**Expected result**

Successful installation of Kyma.

**Actual result**

```
$ kubectl apply -f https://github.com/kyma-project/kyma/releases/download/$KYMA_VERSION/kyma-installer-cluster.yaml
error: unable to recognize "https://github.com/kyma-project/kyma/releases/download/1.11.1/kyma-installer-cluster.yaml": no matches for kind "Installation" in version "installer.kyma-project.io/v1alpha1"
```

**Steps to reproduce**

Installation: https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster

```
export KYMA_VERSION=1.11.1
export CLUSTER_NAME=cluster-3
export GCP_PROJECT=kyma-2
export GCP_ZONE=europe-west3-c


$ gcloud container --project "$GCP_PROJECT" clusters \
> create "$CLUSTER_NAME" --zone "$GCP_ZONE" \
> --cluster-version "1.15" --machine-type "n1-standard-4" \
> --addons HorizontalPodAutoscaling,HttpLoadBalancing
WARNING: Currently VPC-native is not the default mode during cluster creation. In the future, this will become the default mode and can be disabled using `--no-enable-ip-alias` flag. Use `--[no-]enable-ip-alias` flag to suppress this warning.
WARNING: Newly created clusters and node-pools will have node auto-upgrade enabled by default. This can be disabled using the `--no-enable-autoupgrade` flag.
WARNING: Starting with version 1.18, clusters will have shielded GKE nodes by default.
WARNING: Your Pod address range (`--cluster-ipv4-cidr`) can accommodate at most 1008 node(s).
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
Creating cluster cluster-3 in europe-west3-c...
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................done.
Created [https://container.googleapis.com/v1/projects/kyma-2/zones/europe-west3-c/clusters/cluster-3].
To inspect the contents of your cluster, go to: https://console.cloud.google.com/kubernetes/workload_/gcloud/europe-west3-c/cluster-3?project=kyma-2
kubeconfig entry generated for cluster-3.
NAME       LOCATION        MASTER_VERSION  MASTER_IP       MACHINE_TYPE   NODE_VERSION   NUM_NODES  STATUS
cluster-3  europe-west3-c  1.15.11-gke.9   xx.xxx.xxx.xxx  n1-standard-4  1.15.11-gke.9  3          RUNNING


$ gcloud container clusters get-credentials $CLUSTER_NAME --zone $GCP_ZONE --project $GCP_PROJECT
Fetching cluster endpoint and auth data.
kubeconfig entry generated for cluster-3.


$ kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value account)
Your active configuration is: [kyma-2]
clusterrolebinding.rbac.authorization.k8s.io/cluster-admin-binding created


$ kubectl apply -f https://raw.githubusercontent.com/kyma-project/kyma/$KYMA_VERSION/installation/resources/tiller.yaml
serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller-cluster-admin created
deployment.apps/tiller-deploy created
service/tiller-deploy created


$ kubectl apply -f https://github.com/kyma-project/kyma/releases/download/$KYMA_VERSION/kyma-installer-cluster.yaml
error: unable to recognize "https://github.com/kyma-project/kyma/releases/download/1.11.1/kyma-installer-cluster.yaml": no matches for kind "Installation" in version "installer.kyma-project.io/v1alpha1"

```

**Troubleshooting**

I foud #7079. "kyma.exe install" ist running. But the issue is closed but the currect kyma version 1.11.0 is not fixed.

**Comment by a-thaler** [comment] 2020-04-28 13:06
Indeed the linked issue got fixed with Kyma-CLI 1.11.1. Can you please double-check that you are using that version (by calling "kyma version").

**Comment by admiralsmaster** [comment] 2020-04-28 14:22
I try to install Kyma in the GCP with the manual https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster-install-kyma . There is no use of the Kyma CLI.

I use "kyma.exe install" for toubleshooting from #7079 to finished the installation. 

I would expect the installation to work with "gcloud" and "kubectl" according to the instructions.

**Comment by a-thaler** [comment] 2020-05-04 20:16
Hi @admiralsmaster,
Kyma does not yet support kubernetes 1.18 (but we are already working on that). With that, also kubectl 1.18 is not supported yet. The reported problem is indeed caused by using that new version, see also https://github.com/kyma-project/kyma/issues/8360.
We will address the problem in the linked ticket, for now please downgrade your kubectl version to 1.16.x.

**Closed** 2020-05-04 20:17 UTC
Labels: area/cli, bug, duplicate
