### ISSUE TITLE
Serverless fails on "Create Git Function"

### ISSUE THREAD

**Issue by rafalpotempa** [kyma-project/kyma#9336] opened 2020-08-31 09:58 UTC
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/9294/pre-master-kyma-gke-compass-integration/1300340642592854017

```log
  time="2020-08-31T08:44:04Z" level=info msg="Cleanup: 'Create test namespace'"
  time="2020-08-31T08:44:04Z" level=info msg="{\"metadata\":{\"name\":\"test-parallel-8h-28m-53s\",\"selfLink\":\"/api/v1/namespaces/test-parallel-8h-28m-53s\",\"uid\":\"2cd57c64-252f-4260-b0e7-97d6154f9076\",\"resourceVersion\":\"14810\",\"creationTimestamp\":\"2020-08-31T08:28:53Z\",\"labels\":{\"created-by\":\"serverless-controller-manager-test\",\"knative-eventing-injection\":\"enabled\"}},\"spec\":{\"finalizers\":[\"kubernetes\"]},\"status\":{\"phase\":\"Active\"}}"
  time="2020-08-31T08:44:04Z" level=info msg="DELETE: namespace: test-parallel-8h-28m-53s"
      main_test.go:66: 
          Unexpected error:
              <*errors.withStack | 0xc00009c040>: {
                  error: {
                      cause: {
                          s: "timed out waiting for the condition",
                      },
                      msg: "while waiting for function: Create Git Function, to be ready:",
                  },
                  stack: [0x12fc252, 0xa16c25, 0xa169db, 0xa15b5a, 0x16100a7, 0x160fcb7, 0x522f0f, 0x46f481],
              }
              while waiting for function: Create Git Function, to be ready:: timed out waiting for the condition
          occurred
  --- FAIL: TestGitops (911.49s)
  FAIL
  exit_code is 1
  stopping pilot-agent...
```

**Comment by tgorgol** [comment] 2020-08-31 11:34
The reason why the function wasn't ready was:
```
Sources update failed: while listing remotes from repository: http://gitserver.test-parallel-8h-28m-53s.svc.cluster.local:80/function.git: Get "http://gitserver.test-parallel-8h-28m-53s.svc.cluster.local/function.git/info/refs?service=git-upload-pack": dial tcp 10.35.252.205:80: connect: connection refused
```
The function-controller was trying to connect to the in-cluster git repository, but couldn't reach it. That in-cluster repository is deployed in one of the preceding steps, that step also tests the connectivity from the test pod (with Istio injected) to the repository pod (without Istio injected) via Istio DestinationRule, so we can assume that the server was deployed successfully.

I can see that after rerunning the test it succeeded so this error seems random. I will try reproducing the error and monitor the job to see if it fails frequently.

**Comment by tgorgol** [comment] 2020-09-02 12:23
Since this issue was opened I haven't seen another occurrence of this error and I wasn't able to reproduce it so I will close the issue for now. The issue can be reopened if the error starts showing up again.

**Comment by tgorgol** [comment] 2020-09-04 07:36
Looks like this problem started popping up again so I'll reopen the issue.

[LOG 1](https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1301530256527593472/build-log.txt)
[LOG 2](https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1301408954877743104/build-log.txt)

**Comment by dbadura** [comment] 2020-09-14 09:25
This issue should be fixed.

**Closed by dbadura** 2020-09-14 09:25 UTC
Labels: area/serverless, test-failing
