### ISSUE TITLE
Runtime Agent: Add delay before requeuing reconcile request in CompassConnection controller 

### ISSUE THREAD

**Issue by Maladie** [kyma-project/kyma#9617] opened 2020-10-02 12:15 UTC
**Description**

At the moment, each time error occurs during reconciling, the request is immediately requeued. Some of those errors may be related to problems with other components, mostly Connector. We should consider adding a delay before requeuing after error to avoid potential problems when too many requests are send to already heavy loaded component.

Potential solution is to simply set proper value in the field in returned reconcile.Result struct, e.g. `reconcile.Result{RequeueAfter: 5 * time.Minute}`

**Reasons**

This may help to diminish the load when multiple Runtime Agents receiving errors due to problems with component Runtime Agent is sending requests to.

**Comment by franpog859** [comment] 2020-10-15 10:55
For now, the issue is solved on the Compass side. I did some investigation on how to deal with this kind of requeued reconciliation and I put it [here](https://github.com/kyma-project/kyma/issues/9660#issuecomment-708384967). I think we can close this issue for now and work on this topic under [this ticket](https://github.com/kyma-project/kyma/issues/9660)

**Closed** 2020-11-03 10:01 UTC
Labels: area/control-plane, enhancement
