### ISSUE TITLE
Enable core-cluster-users test

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#5910] opened 2019-10-08 08:45 UTC
**Description**

As we agreed in https://github.com/kyma-project/community/issues/369 we are turning off flaky tests in [this](https://github.com/kyma-project/kyma/pull/5901) PR, and `core-cluster-users` is one of them. This needs to be re-enabled.

**Comment by Demonsthere** [comment] 2019-10-10 10:40
I have reenabled the tests to do some research, and it seems that the cause of the errors is in flaky connections to the kubernetes api-server. The tests themselves are not faulty, but rely on connections to dex, which fail due to timeouts

**Comment by aerfio** [comment] 2019-10-13 17:55
Whoops, I missed this issue when I was copy pasting 😭

**Update after quality SIG meeting:**

During the meeting it was discussed that disabling whole test suite is too much most of the time, as only few tests inside are really unstable. It was proposed that a person on duty on CI-Force should have an easy way to disable one particular test by regexp or some other mechanism.

**Comment by Demonsthere** [comment] 2019-10-15 13:43
Tests are reenabled by #5929 and #6017

**Comment by Demonsthere** [comment] 2019-10-16 07:26
Tests have been merged, can we close this?

**Closed** 2019-10-28 06:34 UTC
Labels: priority/critical
