### ISSUE TITLE
Kyma install: Helm install errors

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/kyma#3472] opened 2019-04-01 08:46 UTC
**Description**
There are some helm install errors in plan 
_post-master-kyma-gke-integration_, probably related to istio version update:
```
Status: InProgress, description: Processing component helm-broker
----------
istio:istio:
Helm install error: rpc error: code = Unknown desc = validation failed: [unable to recognize "": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "handler" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "handler" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "kubernetes" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "rule" in version "config.istio.io/v1alpha2"]
core:
Helm install error: rpc error: code = Unknown desc = Job failed: DeadlineExceeded
core:
Helm install error: rpc error: code = Unknown desc = a release named core already exists.
Run: helm ls --all core; to check the status of the release
Or run: helm del --purge core; to delete it
----------
timeout reached. Exiting
```

**Expected result**
Kyma is installed without errors

**Actual result**
Kyma installation fails due to helm errors 

**Troubleshooting**
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1112605248012161026
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1112613553623273474

**Comment by kfurgol** [comment] 2019-04-04 07:07
Duplicate of #3494

**Closed by kfurgol** 2019-04-04 07:07 UTC
Labels: area/installation, test-failing
