### ISSUE TITLE
Replica set does not get removed when modifying the Runtime Profile in the resources tab for functions

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/kyma#10147] opened 2020-12-07 07:59 UTC
**Description**

When using the UI to change the Runtime Profile in the Resources tabs, new Replica sets are created, and old one are not deleted

**Expected result**

I should have only one replica set after the changes

**Actual result**

Replica sets pile up, They are only removed when resource gets deleted

**Steps to reproduce**

1. Create a function
2. Wait for the creation to finish
3. Click one edit resources
4. Modify the runtime profile to L or XL
5. Observe the duplicate replica set in the replica set tab

**Troubleshooting**

**Comment by moelsayed** [comment] 2021-06-29 07:59
This is not a bug. This is a normal behavior. The deployment controller keeps older replicasets scaled to 0 replicas to support revisions and rollback.
The number of revision is configurable and can be reduced or disabled entirely . However, if the issue is UI/UX related, it would be simpler to simply only display replicasets with replica count > 0.

**Comment by kwiatekus** [comment] 2021-07-01 07:22
@valentinvieriu in this case I would close the issue. Filtering out previous replicas might be an option.
How does it look like when using lens or similar tool ?

**Closed by kwiatekus** 2021-07-01 07:22 UTC
Labels: area/serverless, bug
