### ISSUE TITLE
Let´s encrypt error: could not parse resource [] (kyma-aks-nightly)

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/kyma#3425] opened 2019-03-29 09:07 UTC
**Description**
In the last 24h, two builds for _kyma-aks-nightly_ failed with the following error:
```
failed to retrieve log lines: couldn't read requested bytes: read range exceeds artifact contents
- If you like Certbot, please consider supporting our work by:
Donating to ISRG / Let's Encrypt: https://letsencrypt.org/donate
Donating to EFF: https://eff.org/donate-le
ERROR: (gcloud.kms.encrypt) could not parse resource []
```
**Expected result**
Resource has proper content and can be parsed.

**Actual result**
`ERROR: (gcloud.kms.encrypt) could not parse resource []`

**Steps to reproduce**
Rerun kyma-aks-nightly from here https://status.build.kyma-project.io/?job=kyma-aks-nightly.

**Troubleshooting**
Prow logs: 
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-aks-nightly/1111251970213023744
- https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-aks-nightly/1111478336736989184

**Comment by jasiu001** [comment] 2019-04-01 06:40
The issue is related to new functionality about saving certificate on google bucket. Command `gcloud kms encrypt` has missing parameters or there are some missing settings.

**Comment by tuxgoose** [comment] 2019-04-01 13:05
Looks like we hit the rate limit again, KYMA_KEYRING should have been in the prow/config.yaml yet was not added.

**Comment by tuxgoose** [comment] 2019-04-01 18:19
https://github.com/kyma-project/test-infra/pull/827

**Comment by aszecowka** [comment] 2019-04-03 06:22
Jobs are still failing

**Comment by tehcyx** [comment] 2019-04-22 17:50
Should be resolved by this merge: https://github.com/kyma-project/test-infra/pull/872

**Closed** 2019-05-08 23:29 UTC
Labels: area/cluster, test-failing
