### ISSUE TITLE
Update Kyma installation to integrate knative eventing

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#1915] opened 2018-12-04 13:57 UTC
**Description**
The installation of Kyma should be updated to have the possibility to installation a version of kyma-eventing that is based on knative eventing.

>Note: This is driven by a feature flag.
If the feature flag is set to true, kyma eventing is based on knative eventing
else, the current flavor should be installed.

**AC**
* Kyma installation supports switching to knative eventing based on feature flag

**Comment by lilitgh** [comment] 2019-01-11 13:34
Duplicate of #2188

**Closed** 2019-01-11 13:33 UTC
Labels: area/eventing, wg/knative
