### ISSUE TITLE
Provisioning events service instance fails on kyma 1.9

### ISSUE THREAD

**Issue by kjaksik** [kyma-project/kyma#7193] opened 2020-02-12 13:39 UTC
**Description**

After registering application, binding it to a namespace and providing it with API and Event, provisioning of the Event service instance fails.

**Expected result**

Provisioned service instance of events

**Actual result**

```
Provision call failed: provisioning failed while persisting Knative Subscription for application: commerce-test namespace: default on error: getting the Knative channel for the application [commerce-test]: channels.messaging.knative.dev "" not found
```

**Steps to reproduce**

- create application
- bind it to namespace
- register api and events
- provision the newly created service classes

**Logs from `event-sources-controller-manager`**
```
{"level":"info","ts":"2020-02-12T13:24:30.150Z","logger":"event_sources_controller.http-source-controller","caller":"controller/controller.go:351","msg":"Reconcile succeeded. Time taken: 161.629µs.","knative.dev/controller":"http-source-controller","knative.dev/traceid":"d23bf2ef-aaaf-4820-b0b7-2887d17af463","knative.dev/key":"kyma-integration/marketing"}
W0212 13:28:12.047674       1 reflector.go:302] k8s.io/client-go/informers/factory.go:133: watch of *v1.ConfigMap ended with: too old resource version: 13477863 (13483169)
```

**Comment by antoineco** [comment] 2020-02-12 14:26
The broker was looking for a Channel by label (`application-name == commerce-test`) and didn't find any ([code](https://github.com/kyma-project/kyma/blob/2bed6bc/components/application-broker/internal/broker/provision.go#L385-L387)). That could be due to a delay between the creation of the Channel (event-sources controller) and the moment the broker cached that Channel, but I would expect the broker to retry provisioning in that case.

**Comment by k15r** [comment] 2020-02-12 14:34
i see the same issue after restoring a backup (kyma:master)

**Comment by nachtmaar** [comment] 2020-02-18 14:08
A few questions:
- Did you use minikube/gke or something else?
- Did you use the UI for the steps or kubectl ? (using kubectl could make a timing difference).

I am trying to reproduce it on a Kyma 1.9 cluster now.

**Comment by nachtmaar** [comment] 2020-02-21 09:20
This is the code line where the provisioning of the ServiceInstance fails: <https://github.com/kyma-project/kyma/blob/2bed6bcf03b35e024d73d1a4c2534935faeeebfe/components/application-broker/internal/broker/provision.go#L240>

**How to reproduce**:
The idea is to remove the Knative Channel and trigger a provisioning request to the application broker.

Before creating the ServiceInstance do this:

```bash
kubectl scale --replicas=0 -n kyma-system deployment event-sources-controller-manager
kubectl delete channels.messaging.knative.dev -n kyma-integration <channel-name>
```


After creating the ServiceInstance and the first provision request fails do this:
```bash
kubectl scale --replicas=1 -n kyma-system deployment event-sources-controller-manager
kubectl get channels.messaging.knative.dev -n kyma-integration <channel-name> # check channel has been recreated
```

In the ServiceCatalog one can see this message: `Not processing event because status showed there is no work to do`.

Investigation further now why the provisioning is not retried. Likelihood may be low that the channel does not exist before a ServiceInstance is created, but still there is a chance and it is a bug since ServiceCatalog should trigger a new provisioning request.

**Comment by nachtmaar** [comment] 2020-03-17 09:00
In short: After investigation of @ksputo, ServiceCatalog behaves correctly. It is the responsibility of the Application-Broker to implement the retry behaviour. 

The [ticket](https://github.com/kyma-project/kyma/issues/7288) will be updated shortly.

**Comment by anishj0shi** [comment] 2020-07-29 11:34
we don't observe this issue anymore. Hence, closing this issue. 
need more thorough steps to reproduce this issue.

**Closed by anishj0shi** 2020-07-29 11:34 UTC
Labels: area/eventing, bug, invalid
