### ISSUE TITLE
Remote Environment Services not Visible in Catalog

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#1697] opened 2018-11-16 11:06 UTC
**Description**

Dear Colleagues,

when registering services of a Remote Environment through the metadata API, they do not become visible in the catalog of the Kyma environment, if the binding between environment and remote environment happened prior to the metadata publication.

Regards

Andreas

**Expected result**

Services become visible instantaneously (or at least without unbinding)
 
**Actual result**

Services are not visible

**Steps to reproduce**

Create Remote Environment, Bind to Kyma Environment, Publish Metadata
**Troubleshooting**

N/A

**Comment by Disper** [comment] 2018-11-19 12:42
@akrausesap could you attach Remote environment CRD?

**Comment by Disper** [comment] 2018-11-24 10:36
We're closing it for now as we were not able to reproduce it. 
Please contact us if the problem is occurring.

**Closed** 2018-11-24 10:36 UTC
Labels: area/application-connector, bug

**Comment by PK85** [comment] 2018-12-07 17:05
Duplicated, and will be solved by #1954
