### ISSUE TITLE
Installation of the GCP broker is stuck in the provisioning state

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#5825] opened 2019-09-30 11:37 UTC
**Description**
Sometimes the installation of the GCP broker is stuck in the provisioning state. Restarting the helm broker seems to fix the issue.

**Steps to reproduce**
* Install Kyma 1.5 from https://cockpit.cx.cloud.sap/
* Provision GCP Broker

Raised by @brendandobbs

**Comment by brendandobbs** [comment] 2019-10-01 19:22
In my case restarting the helm broker didn't work however @joek I think had some success and might be able to provide more details about the issue.

**Comment by mszostok** [comment] 2019-10-08 09:57
The GCP broker is in the Preview state in 1.5. 

I've followed my own testing scenario because this issue does not have such information

# Testing scenario
0. I've created Kyma cluster in version 1.5 via https://cockpit.int.faros.kyma.cx
1. I've followed docs about enabling **Preview** GCP Broker in cluster:
https://kyma-project.io/docs/1.5/components/service-catalog#service-brokers-google-cloud-platform-service-broker-enable-gcp-service-broker
2. Once the GCP Addon was added in Service Catalog view I've followed the instruction in Overview section about creating Broker Secret
    ## Create a Secret
    
    To add the GCP Service Broker to your Namespace, prepare a service account and a JSON access key. 
    
    Follow these steps to create a Kubernetes Secret which contains a JSON access key:
    
    1. Open `https://console.cloud.google.com/` and select your project.
    
    2. On the left pane, go to **IAM & admin** and select **Service accounts**.
    
    3. Click **Create service account**, name your account, and click **Create**.
    
    4. Set the `Project Owner` role.
    
    5. Click **Create key** and choose `JSON` as a key type.
    
    6. Save the `JSON` file.
    
    7. Create a Secret from the JSON file by running this command:
    
            kubectl create secret generic gcp-broker-data --from-file=sa-key={filename} --from-literal=project-name={gcp-project} --namespace {namespace}
    
    8. Click **Done**.
    
    >**NOTE:** You can provision only one instance of the GCP Service Broker in each Namespace.
3. I provisioned instance on GCP broker with the secret name that I created
4. After a few minutes the GCP classes were visible in Service Catalog UI.
![Screen Shot 2019-10-08 at 11 56 40](https://user-images.githubusercontent.com/17568639/66386547-b7515a00-e9c2-11e9-8758-7de29fabb983.png)


With the above scenario, I was not able to reproduce this error. **Please ensure that you always have a correct secret for your GCP broker. Without that instance will not be never in success state and helm installation will be timeouted.**


@brendandobbs and @joek please add more info on how to reproduce that error. Also helm-broker logs and addon configuration status will be helpful.

**Comment by brendandobbs** [comment] 2019-10-08 10:17
thanks, @mszostok. I only saw the issue once and I didn't have an opportunity to get the logs before the cluster was destroyed. If Johannes doesn't have more details lets wait and see if the issue comes up again this week at TechEd. We can close it if there are no problems during the sessions.

**Closed** 2019-10-28 12:09 UTC
Labels: area/service-catalog, bug
