### ISSUE TITLE
Odata spec not being uploaded into Rafter

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#9863] opened 2020-11-04 14:50 UTC
**Description**

After Odata API is registered there is no documentation rendered in the UI. We've already noticed that there is no spec present in the Rafter (empty bucket). This concerns Runtime Agent scenario integrated with Compass.

**Expected result**

Odata API spec renders

**Actual result**

Error present, no API spec rendered.

**Steps to reproduce**

- Register Odata API
- Go into the Service Catalog part of the UI

**Comment by franpog859** [comment] 2020-11-20 13:23
I tried to reproduce the bug but I failed to do it. Here is what I tried:
1. I created a cluster on Gardener Azure
1. I installed [Kyma with disabled legacy connectivity and Compass](https://github.com/kyma-incubator/compass/blob/master/docs/compass/04-01-installation.md#cluster-installation-1) on the cluster
1. I created an Application, connected to it with Connectivity Adapter API - `https://adapter-gateway.fran-cluster.com/v1/applications/signingRequests/info?token=qweasd` + [one-click-integration.sh](https://github.com/janmedrek/one-click-integration-script)
1. I registered an OData service using Connectivity Adapter API - 
```
curl -X POST -d '{
  "provider": "odata-prov",
  "name": "odata-curl",
  "description": "odata-desc",
  "api": {
    "targetUrl": "https://services.odata.org/OData/OData.svc",
    "specificationUrl": "https://services.odata.org/OData/OData.svc/$metadata",
    "apiType": "odata"
}}' https://adapter-gateway-mtls.fran-cluster.com/fran-test-2/v1/metadata/services --cert generated.crt --key generated.key -k
```
5. I went to the Runtime Console and bound my Application to my newly created Namespace
6. I went to the Service Management and then to the Catalog, opened my Package and there was my OData definition
![image](https://user-images.githubusercontent.com/32485355/99804619-92269900-2b3b-11eb-8b88-60f05d4ac08d.png)

Maybe I did something wrong. Could you provide a quick guide on how to reproduce the error?

**Comment by franpog859** [comment] 2020-11-24 07:40
I think I finally managed to reproduce it! 

It seems that if you try to register a basic-auth (or any auth to be honest) secured OData spec it just doesn't work. And as far as I can see, [this is the intended action](https://github.com/kyma-incubator/compass/blob/master/components/director/internal/domain/fetchrequest/service.go#L97-L99). Director fails to validate such Fetch Request and it results in `Invalid data [reason=Auth for Fetch Request was provided, currently it's unsupported` in the status_message from fetch_requests and `<null>` in the spec_data from api_definitions

I created [a feature request](https://github.com/kyma-incubator/compass/issues/1629) issue in the kyma-incubator/compass repository. I think we can close this issue

**Closed** 2020-11-24 09:55 UTC
Labels: area/control-plane, bug
