### ISSUE TITLE
Split serving.yaml to files per resource

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/kyma#6982] opened 2020-01-24 12:20 UTC
**Description**

Split https://github.com/kyma-project/kyma/blob/master/resources/knative-serving/templates/serving.yaml template to files per resource for better development. Remove also comments and point to them by links to original templates in knative-serving repo.

**Comment by michal-hudy** [comment] 2020-05-06 19:54
Duplicate of https://github.com/kyma-project/kyma/issues/7854

**Closed by michal-hudy** 2020-05-06 19:54 UTC
Labels: area/serverless, enhancement
