### ISSUE TITLE
Kyma Version not visible in Kyma console

### ISSUE THREAD

**Issue by tricky42** [kyma-project/kyma#6323] opened 2019-11-20 20:51 UTC
If you are working on a provided Kyma cluster and you find a bug, there is no "easy" way to find out which version of Kyma you are working on. 

The Console should display the concrete version of Kyma somewhere where it is easy to find it (e.g. footer). 

And yes, there are more complicated cases with custom versions of Kyma components and I am happy to provide my ideas. But this shouldn't prevent us from doing the first important step.

**Comment by akucharska** [comment] 2019-12-16 14:31
Duplicate of https://github.com/kyma-project/console/issues/754

**Closed by akucharska** 2019-12-16 14:31 UTC
Labels: area/console, enhancement
