### ISSUE TITLE
Investigate the CommerceMock test on 'kyma-integration-evaluation-gardener-azure'

### ISSUE THREAD

**Issue by rafalpotempa** [kyma-project/kyma#10775] opened 2021-03-02 11:19 UTC
**Description**

The `kyma-integration-evaluation-gardener-azure` fails for unknown reason yielding 
```log
  1) CommerceMock tests
       function should reach Commerce mock API through app gateway:
     Error: Function lastorder responded with error
500: Internal Server Error: "Internal Server Error"
```
- [full log](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1366676183290220544)

**Steps to reproduce**

**Troubleshooting**

**Comment by tobiscr** [comment] 2021-03-22 15:55
Same job fails quite often caused by a timeout ([fulll logs](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-evaluation-gardener-azure/1373833133064982528/build-log.txt)):

      1) CommerceMock tests
           CommerceMock test fixture should be ready:
         Error: Waiting for webservices service class timeout (300000 ms)
          at Timeout._onTimeout (utils/index.js:307:18)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7)

      2) CommerceMock tests
           function should reach Commerce mock API through app gateway:
         Error: Function lastorder responded with error
    500: Internal Server Error: "Internal Server Error"
          at convertAxiosError (utils/index.js:82:10)
          at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:148:28
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
          at async checkAppGatewayResponse (test/fixtures/commerce-mock/index.js:144:13)
          at async Context.<anonymous> (test/2-commerce-mock.js:30:5)

**Comment by janmedrek** [comment] 2021-07-12 09:29
Closing as it was not reproduced, feel free to reopen if it pops up.

**Closed by janmedrek** 2021-07-12 09:29 UTC
Labels: area/ci, test-failing
