### ISSUE TITLE
rafter-minio PVC is pending in installation on pre-master-kyma-integration job

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/kyma#7132] opened 2020-02-06 12:09 UTC
**Description**

From some time `pre-master-kyma-integration` job always fails. It is caused by pending PVC in installation of `rafter-minio` chart. See the logs from described pvc:

```
Events:
  Type       Reason                Age                  From                         Message
  ----       ------                ----                 ----                         -------
  Normal     ExternalProvisioning  116s (x83 over 22m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner “k8s.io/minikube-hostpath” or ma
nually created by system administrator
11:37
E0206 10:37:27.733242       1 leaderelection.go:331] error retrieving resource lock kube-system/k8s.io-minikube-hostpath: endpoints “k8s.io-minikube-hostpath” is forbidden: User “syste
m:serviceaccount:kube-system:storage-provisioner” cannot get resource “endpoints” in API group “” in the namespace “kube-system”
```

As we can see, `storage-provisioner` service account hasn't got appropriate rules for `endpoints` resources. We need investigate that and fix it, because already this issue blocks all PRs. 

**Steps to reproduce**

Create PR and you'll see failing `pre-master-kyma-integration` job.

**Comment by adamwalach** [comment] 2020-02-06 12:14
It is probably caused by https://github.com/kubernetes/minikube/issues/6523

**Comment by adamwalach** [comment] 2020-02-06 14:50
Minikube guys [fixed](https://github.com/kubernetes/minikube/issues/6523#issuecomment-582933041) their images, so this issue is solved. Lets wait few hours to before closing it, just to confirm our pipelines are back to normal - https://status.build.kyma-project.io/?job=pre-master-kyma-integration

**Comment by michal-hudy** [comment] 2020-02-06 21:50
Pipelines are working again, thanks @magicmatatjahu and @adamwalach !

**Closed by michal-hudy** 2020-02-06 21:50 UTC
Labels: bug, priority/critical
