### ISSUE TITLE
Run integration tests on GKE cluster with self signed certificates and kyma.local domain

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#870] opened 2018-09-21 14:25 UTC
**Description**
CI should test pull requests on real cluster (GKE). But we can't issue new certificate and create DNS entry for every new pull request. The idea is to test it with self signed certificates and local DNS (or entries in /etc/hosts).

**Comment by piotrmsc** [comment] 2018-11-29 08:29
Duplicate of https://github.com/kyma-project/test-infra/issues/20. Won't do

**Closed by piotrmsc** 2018-11-29 08:29 UTC
Labels: area/ci, enhancement
