### ISSUE TITLE
Unstable Connector Service test 

### ISSUE THREAD

**Issue by Disper** [kyma-project/kyma#2891] opened 2019-02-27 12:46 UTC
**Description**

Connector Service test randomly failed when run by Stability checker on nightly cluster.
So far this failing test has been spotted only once.

**Expected result**

Test is successful.

**Actual result**

Test failed.

**Steps to reproduce**

```
Testing 'connector-service-tests'
'connector-service-tests' has Failed status
Fetching logs from 'connector-service-tests' with options tailLimit=2000 and bytesLimit=500000
Run api tests
2019/02/27 05:14:14 Read configuration: {InternalAPIUrl:http://connector-service-internal-api.kyma-integration.svc.cluster.local:8080 ExternalAPIUrl:http://connector-service-external-api.kyma-integration.svc.cluster.local:8081 GatewayUrl:https://gateway.nightly.build.kyma-project.io SkipSslVerify:true Tenant: Group:}
2019/02/27 05:14:14 Read configuration: {InternalAPIUrl:http://connector-service-internal-api.kyma-integration.svc.cluster.local:8080 ExternalAPIUrl:http://connector-service-external-api.kyma-integration.svc.cluster.local:8081 GatewayUrl:https://gateway.nightly.build.kyma-project.io SkipSslVerify:true Tenant: Group:}
2019/02/27 05:14:32 Read configuration: {InternalAPIUrl:http://connector-service-internal-api.kyma-integration.svc.cluster.local:8080 ExternalAPIUrl:http://connector-service-external-api.kyma-integration.svc.cluster.local:8081 GatewayUrl:https://gateway.nightly.build.kyma-project.io SkipSslVerify:true Tenant: Group:}
--- FAIL: TestConnector (22.84s)
    --- FAIL: TestConnector/Connector_Service_flow_for_Application (21.06s)
        --- FAIL: TestConnector/Connector_Service_flow_for_Application/should_create_client_certificate (18.89s)
        	require.go:794:
        			Error Trace:	connectorclient.go:69
        			            				connector_test.go:523
        			            				connector_test.go:86
        			            				connector_test.go:86
        			Error:      	Received unexpected error:
        			            	Get https://connector-service.nightly.build.kyma-project.io/v1/applications/signingRequests/info?token=WCjqST7ljXp2DQBPX2cHFGZnThxiUZzetszJpLsCGXRVkvJ5azZ0wf6j7txQI6jRyRF5q7x5cT8AE0JMfxPGzw==: dial tcp 35.234.66.106:443: connect: no route to host
        			Test:       	TestConnector/Connector_Service_flow_for_Application/should_create_client_certificate
FAIL
End of testing 'connector-service-tests'
```

**Troubleshooting**
Calling the same endopoint was successful when ran manually.

**Comment by Disper** [comment] 2019-03-11 13:17
Happened again: https://status.build.kyma-project.io/log?job=pre-master-kyma-gke-central-connector&id=1105064778927181825

**Comment by franpog859** [comment] 2019-03-29 13:16
I found three errors used to appear in the failing tests:

- Error `connect: no route to host` is most likely caused by improper `kube-dns` setup. That issue is not related to Application Connector
- Error `read: connection reset by peer` is caused by `kube-proxy` bug. You can track the work progress [here](https://github.com/kubernetes/kubernetes/issues/74839)
- Error `Post https://.../v1/applications/certificates/renewals: EOF` is a bug and [this PR](https://github.com/kyma-project/kyma/pull/3427) should fix it

**Comment by franpog859** [comment] 2019-04-09 06:56
Issue is currently blocked. Error `read: connection reset by peer` is caused by `kube-proxy` bug. You can track the work progress [here - kubernetes/kubernetes/issues/74839](https://github.com/kubernetes/kubernetes/issues/74839)

**Comment by franpog859** [comment] 2019-05-17 08:55
Issue [for kubernetes fix](https://github.com/kubernetes/kubernetes/issues/74839) of the `read: connection reset by peer` problem has been closed and PRs with fixes have been merged. I suggest to close this issue and observe the CI logs. If the problem will occur once again I suggest to reopen this issue.

**Closed** 2019-05-21 06:39 UTC
Labels: area/application-connector, bug, test-failing
