### ISSUE TITLE
Application connector tests failing (post-master-kyma-integration)

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/kyma#3407] opened 2019-03-28 13:57 UTC
**Description**
Application connector tests failing on _post-master-kyma-integration_ job: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1111243665184919552. 
```
suite.go:166: --------------------------------------------End of logs from test-operator-app-test-qhm6-event-service-acceptance test--------------------------------------------
suite.go:123: operator-app-test-qhm6 tests failed
suite.go:124: Application tests failed
suite.go:76: Cleaning up...
FAIL
```

**Expected result**
Tests run successfully

**Actual result**
Tests are failing

**Comment by Szymongib** [comment] 2019-04-09 12:29
Duplicate of #3430

**Closed by Szymongib** 2019-04-09 12:29 UTC
Labels: area/application-connector, duplicate, test-failing
