### ISSUE TITLE
Facilitate UI API Layer development

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#3125] opened 2019-03-12 13:26 UTC
**Description**

Development of UI API Layer is tedious - to get to graphql playground you have to start https://console.kyma.local/, log into dex, get token from network tab, paste this into ModHeader and then finally you can start development. There could be some kind of flag to turn off all authorization, to just go to localhost:3000 and start development.

**Reasons**

Development would be easier and less tedious, developers have to make such steps to just get to Graphql playground

**Comment by pkosiec** [comment] 2019-03-13 08:12
This is a duplicate of #2750. I'm closing this.

**Closed by pkosiec** 2019-03-13 08:12 UTC
Labels: area/console, enhancement
