### ISSUE TITLE
Kyma Installation on AKS failes - Helm error: context deadline exceeded

### ISSUE THREAD

**Issue by mac8005** [kyma-project/kyma#3267] opened 2019-03-20 16:03 UTC
**Description**

Kyma Installtion on a fresh RBAC enabled AKS Cluster failes:

`2019/03/20 15:45:34 Error during install/update:  Details: Helm error: context deadline exceeded
E0320 15:45:34.239471       1 controller.go:286] Helm error: context deadline exceeded
2019/03/20 15:45:34 ######################################################################
2019/03/20 15:45:34 #### Retries does not seem to work. Manual action is recommended. ####
2019/03/20 15:45:34 ######################################################################
2019/03/20 15:45:34 Warning: Retry number 16 (sleeping for 60[s]).`

Tiller is installed and seams to work fine:

`Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}`

Performed all steps from the Docs [Installation](https://kyma-project.io/docs/root/kyma/#installation-install-kyma-on-an-aks-cluster)

Version: 0.8

**Comment by Tomasz-Smelcerz-SAP** [comment] 2019-04-10 07:58
Sadly, log entry attached here is useless. `context deadline exceeded` is a generic golang error that essentially means: "timeout occurred". There's no information about release and Installer step.
For the future, please put some effort in gathering all possible information.
Attach:
- Full Installer logs
- Installation CR status

If Full Installer logs are too big to attach, please parse them for the *first* few errors (e.g fist 10 errors) and attach those to the bug report. Otherwise we have no hope to help.
If you can somehow provide it, we'll try to help. Otherwise I have to close the issue as invalid/can't reproduce.

**Comment by piotrmsc** [comment] 2019-04-30 06:45
The same as #3590, we will use 3590 as working issue

**Closed** 2019-04-30 06:46 UTC
Labels: duplicate
