### ISSUE TITLE
UI API Acceptance tests are failing because connection to DEX has been refused

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#3173] opened 2019-03-14 10:31 UTC
**Description**

UI API Acceptance tests are failing because the connection to DEX has been refused.
```
PASS
--- FAIL: TestReplicaSet (0.00s)
    require.go:794: 
        	Error Trace:	replicaset_test.go:58
        	Error:      	Received unexpected error:
        	            	Post https://dex.gke-upgrade-commit-91e5ade2-k10huk40np.build.kyma-project.io/auth: dial tcp 35.234.69.49:443: connect: connection refused
        	Test:       	TestReplicaSet
FAIL
```
It looks like the DEX component is not stable.

https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1105833846147911681/build-log.txt

**Expected result**

Authentication during tests is stable.

**Actual result**

Authentication sometimes fails

**Steps to reproduce**

Execute test in cluster

**Troubleshooting**

**Comment by michal-hudy** [comment] 2019-03-15 20:16
Sometimes it also failing with such error:
```
--- FAIL: TestIDPPresetQueriesAndMutations (67.47s)
    require.go:794:
                Error Trace:    idppreset_test.go:22
                Error:          Received unexpected error:
                                Post https://dex.nightly.build.kyma-project.io/auth/local?req=hlshhvuzl77awckt7zn3q2zbn: dial tcp 35.246.131.58:443: connect: no route to host
                                while performing HTTP POST on login endpoint
                                github.com/kyma-project/kyma/tests/ui-api-layer-acceptance-tests/internal/graphql.(*dexIdTokenProvider).implicitFlow
                                        /go/src/github.com/kyma-project/kyma/tests/ui-api-layer-acceptance-tests/internal/graphql/idtokenprovider.go:86
                                github.com/kyma-project/kyma/tests/ui-api-layer-acceptance-tests/internal/graphql.(*dexIdTokenProvider).fetchIdToken
                                        /go/src/github.com/kyma-project/kyma/tests/ui-api-layer-acceptance-tests/internal/graphql/idtokenprovider.go:37
                                github.com/kyma-project/kyma/tests/ui-api-layer-acceptance-tests/internal/graphql.authenticate
                                        /go/src/github.com/kyma-project/kyma/tests/ui-api-layer-acceptance-tests/internal/graphql/client.go:153
                                github.com/kyma-project/kyma/tests/ui-api-layer-acceptance-tests/internal/graphql.New
                                        /go/src/github.com/kyma-project/kyma/tests/ui-api-layer-acceptance-tests/internal/graphql/client.go:34
                                github.com/kyma-project/kyma/tests/ui-api-layer-acceptance-tests/internal/domain/authentication.TestIDPPresetQueriesAndMutations
                                        /go/src/github.com/kyma-project/kyma/tests/ui-api-layer-acceptance-tests/internal/domain/authentication/idppreset_test.go:21
                                testing.tRunner
                                        /usr/local/go/src/testing/testing.go:827
                                runtime.goexit
                                        /usr/local/go/src/runtime/asm_amd64.s:1333
                Test:           TestIDPPresetQueriesAndMutations
FAIL
```

Happened today on `nightly` cluster

**Comment by sjanota** [comment] 2019-03-18 07:22
@michal-hudy On nightly, do you know if it was the only test in suite that failed for this reason?

**Comment by piotrmsc** [comment] 2019-04-30 06:32
@michal-hudy I will close this one as it is duplicate of https://github.com/kyma-project/kyma/issues/3622

**Closed** 2019-04-30 06:33 UTC
Labels: duplicate
