### ISSUE TITLE
Test Lambda from Console UI

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#1502] opened 2018-11-02 08:47 UTC
As a developer I would like to easily test a lambda function to speed up my development.

AC:
- I have a UI, where I can inject data, invoke the lambda and see the response

**Comment by joek** [comment] 2019-02-11 09:56
Due to the upcomming enablement of Mutual TLS the task is getting way more complicated. So we have to implement it at a later point in time.

**Comment by brendandobbs** [comment] 2019-03-05 12:19
The mocking framework ([Varkes](https://github.com/kyma-incubator/varkes)) could be useful for the event triggering.

**Comment by joek** [comment] 2019-03-05 12:53
@brendandobbs I don't think this is the right tool. The topic is to provide a UI based functionality for testing in lambda UI. The call will probably not go over the eventbus at all.

**Comment by brendandobbs** [comment] 2019-03-05 12:58
@joek , I agree it's probably not the right tool but my thoughts were that there could be something reusable for creating the sample events and sending them directly from the Lambda UI. Is there a reason to not use the event bus? Maybe it would be advantageous to test the subscription is working also?

**Comment by brendandobbs** [comment] 2019-05-07 12:58
Duplicate of https://github.com/kyma-project/console/issues/780

**Comment by brendandobbs** [comment] 2019-05-07 13:01
Closed as it is duplicated by https://github.com/kyma-project/console/issues/780

**Closed** 2019-05-07 13:01 UTC
Labels: area/serverless, quality/devx
