### ISSUE TITLE
Bundles - fixed attribute order in wizard

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#3925] opened 2019-05-03 14:27 UTC
**Description**
For a helm broker bundle you usually require a set of input params collected via the service instance wizard. Here, the order of the attribute appearing in the wizard might be relevant. think of name / description attributes where you first think about the naming and then the description. It will be awkward to fill it in the reverse order.
Unfortunately, I found no way to influence the order of the attributes, so either derive the order from the attribute order in the related json document or if not possible provide a different way of influencing the order.

AC:
- If I define two attributes, it is up to the bundle developer to decide on which attribute is listed above the other in the wizard.

**Reasons**
Currently it is a bad experience to fill out attributes in a order not intended by the bundle developer.

See also https://github.com/SAP/xf-addons/blob/master/bundles/marketing-connector-0.1.0/plans/default/create-instance-schema.json, here the basic_user and basic_password are appearing in wrong order.

**Comment by kwiatekus** [comment] 2019-11-29 10:23
Seems like a duplicate of https://github.com/kyma-project/kyma/issues/4513.
Closing in favor of https://github.com/kyma-project/kyma/issues/4513

**Closed by kwiatekus** 2019-11-29 10:23 UTC
Labels: duplicate
