### ISSUE TITLE
Event type has changed - integration test fails

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#10720] opened 2021-02-23 13:50 UTC
**Description**
I am running integration tests against the new eventing component. But it seems that the event type passed to the lambda has changed.
```
AssertionError: expected { Object (order, event) } to have nested property 'event.ce-type' of 'order.created', but got 'sap.kyma.custom.commerce.order.created.v1'
      + expected - actual

      -sap.kyma.custom.commerce.order.created.v1
      +order.created
```
Other difference is in the event source:
```
      AssertionError: expected { Object (order, event) } to have nested property 'event.ce-source' of 'commerce', but got 'kyma'
      + expected - actual

      -kyma
      +commerce
```

**Steps to reproduce**

Run fast-integration test on the cluster with the new eventing.

**Comment by k15r** [comment] 2021-03-04 13:25
This is actually not a bug, but more a necessity that needs to be documented. It is part of our backlog to address this in the documentation.

**Comment by berkanercan** [comment] 2021-03-18 14:54
Fixed within new eventing solution https://github.com/kyma-project/kyma/pull/10793

**Closed** 2021-03-18 14:54 UTC
Labels: area/eventing
