### ISSUE TITLE
Slow performance for python based serverless

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/kyma#10154] opened 2020-12-07 14:09 UTC
**Description**

Trying load testing the python hellow world produces very low results using the XL profile.
```
Python XL - profile 20 replicas using production profile
Running 2m test @ https://test-python.kyma.fun/
  12 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   137.74ms  140.89ms   1.20s    85.80%
    Req/Sec    25.44     15.21    90.00     61.41%
  Latency Distribution
     50%   81.74ms
     75%  158.68ms
     90%  350.39ms
     99%  659.27ms
  27131 requests in 1.67m, 4.74MB read
  Socket errors: connect 0, read 0, write 0, timeout 119
Requests/sec:    271.04
Transfer/sec:     48.52KB
```
compared with 

```
Node XL - profile 20 replicas using production profile
Running 2m test @ https://test-node.kyma.fun/
  12 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    47.30ms   42.70ms 959.29ms   90.77%
    Req/Sec   242.49     39.30   373.00     68.63%
  Latency Distribution
     50%   30.77ms
     75%   50.97ms
     90%   86.54ms
     99%  225.96ms
  289751 requests in 1.67m, 54.81MB read
Requests/sec:   2894.70
Transfer/sec:    560.71KB
```
**Expected result**

Python and nodejs should behave similar

**Actual result**

Python hello world is 10x to 100x slower than Nodejs
**Steps to reproduce**

- Create new python function, using ui.
- Create new nodejs function using ui
- compare requests per seconds from the 2. Nodejs is 10x to 100x faster than python

**Troubleshooting**

**Comment by dbadura** [comment] 2021-03-25 08:47
Tool used for benchmark:
https://github.com/wg/wrk

**Comment by dbadura** [comment] 2021-04-01 12:01
# Problem
Python function are very slow

# Testing mechanism
I used [Locust](locust.io) and wrote such test.
```python
from locust import HttpUser, task, constant

expected_string = "Hello World"

class Python38Test(HttpUser):
    wait_time = constant(1)

    @task
    def hello_word(self):
        with self.client.get("/", catch_response=True) as response:
            if expected_string not in response.text:
                response.failure("Got wrong response, expected {} ..., got: {}".format(expected_string,response.text))
```

Locust was used to test Nodejs12 and Python function.

# Available Resources
Minikube with 4 CPU on KVM. Machine with 32GB RAM and 8 cores.

# Benchmarking
Python was significantly slower than nodeJS, even if I applied following things:

- increase CPU and memory limits to: 0,5CPU and 256MB
- increase number of CHERRYPY_NUMTHREAD to 100
- use Pypy

Python has problem dealing with about 7 request per seconds. Response times are very often above 1s: ![python38-default](https://user-images.githubusercontent.com/45110612/113290883-85d4f880-92f2-11eb-8158-d55973cd2d50.png)

I decided to write custom runtime to check if problem lies in kubeless runtime.

# Results
I deployed following functions with profile M (limit: 100mcpu 128MiB memory):
- nodejs12
- custom python38 with 'CHERRYPY_NUMTHREAD' set to default value (10)
- custom python38 with 'CHERRYPY_NUMTHREAD' set to 50
- custom python38 with 'CHERRYPY_NUMTHREAD' set to 50 and python:alpine as the base image.

I spawned 40 users and here are the results:
- Nodejs 
![nodejs12-chart](https://user-images.githubusercontent.com/45110612/113290231-a2246580-92f1-11eb-9f2d-bb039a519f31.png) and 
![nodejs12-stats](https://user-images.githubusercontent.com/45110612/113290282-b5cfcc00-92f1-11eb-87cd-cd637af2fdfd.png)


- Custom Python38 10 Threads 
![python38-10-threads-chart](https://user-images.githubusercontent.com/45110612/113290356-d0a24080-92f1-11eb-9b50-ad3b9195107e.png) and 
![python38-10-threads-stats](https://user-images.githubusercontent.com/45110612/113290376-d5ff8b00-92f1-11eb-8ca8-85572ea092d1.png)

- Custom Python38 50 Threads 
![python38-custom-50-threads-chart](https://user-images.githubusercontent.com/45110612/113290444-f2032c80-92f1-11eb-8211-febd0d822b67.png)
and
![python38-custom-50-threads-stats](https://user-images.githubusercontent.com/45110612/113290450-f3345980-92f1-11eb-9c3b-925525ac8c6b.png)
 
- Custom Python38 5 Thread and alpine

![python38-custom-alpine-50-chart](https://user-images.githubusercontent.com/45110612/113290474-fd565800-92f1-11eb-9432-cd0e1db12e05.png) and
![python38-custom-alpine-50-stats](https://user-images.githubusercontent.com/45110612/113290477-fdeeee80-92f1-11eb-9507-0135dfccc206.png)


# Summary
The problem is in kubeless function runtime in queue mechanism, [here](https://github.com/kyma-project/kyma/blob/cf64762c23faf382c71abca5ccebb8375b8e8da7/components/function-runtimes/python38/kubeless/kubeless.py#L109-L120).

**Comment by rJankowski93** [comment] 2021-04-29 09:48
Different timeout implementation:
- timeout decorator -> https://github.com/rJankowski93/kyma/commit/c4cfd4f26f5837cf21a46155b0451cee0ce720a2
- pebble -> https://github.com/rJankowski93/kyma/commit/a5dab6526cbcd8bf1e298ecfbd3cbe7a66ff5756

**Comment by dbadura** [comment] 2021-05-10 12:29
Ok, I checked `threading` from this PR: https://github.com/kyma-project/kyma/pull/11204

The results are very promising:
I run stresst test starting from 25 users then increasing to 40 and finishied at 50.
The results is that new function runtime can handle 45 request per second for simple `hello world` function.

**Comment by kwiatekus** [comment] 2021-05-14 13:16
Fixed with https://github.com/kyma-project/kyma/pull/11040

**Comment by kwiatekus** [comment] 2022-02-08 08:30
https://github.com/kyma-project/kyma/pull/13309

**Comment by kwiatekus** [comment] 2022-02-10 08:01
Further improved by bumping of the limit of concurrent threads

**Closed by kwiatekus** 2022-02-10 08:01 UTC
Labels: area/serverless
