### ISSUE TITLE
Underscore in Cloud Event name

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/kyma#11862] opened 2021-08-09 13:25 UTC
**Description**

We have an event sent from SAP Cloud for Customer to Kyma.
Event type contains underscore.
For example: DocuSing_BO.Account_DocuSign.Updated
When we subscribe some function to such event, we can see in Eventing Controller (eventing-nats-controller) logs:

> {"level":"info","ts":1628511878.7641728,"logger":"reconciler.Subscription","msg":"clean event-type","before":"sap.kyma.custom.appname.DocuSing_BO.Account_DocuSign.Updated.v1","after":"sap.kyma.custom.appname.DocuSingBOAccountDocuSign.Updated.v1"}

And that there was an infrastructure created for it. We see it in NATS server logs (eventing-nats-1):

> [1] 2021/08/09 12:24:38.772063 [TRC] 10.28.11.25:59412 - cid:1 - <<- [SUB sap.kyma.custom.appname.DocuSingBOAccountDocuSign.Updated.v1  455]

All namings are according to https://kyma-project.io/docs/components/eventing/ when the event type has more than 2 segments. However, underscores are already removed.

Then when we publish an event of this type from the application, it is not delivered to the sink function.
The event gets sent from the application with DocuSing_BO.Account_DocuSign.Updated event type.

Next, we see it arrived in Event Publisher proxy as :

> time="2021-08-09T12:44:32Z" level=info msg="Event dispatched" duration="136.601µs" id=00163ea6-c771-1eeb-be93-0a7a97394ab7 responseBody= source=kyma statusCode=204 type=sap.kyma.custom.appname.DocuSing_BOAccount_DocuSign.Updated.v1

Notice the first and the second segments are combined already (periods removed) but underscore remained.

Then in NATS server logs we see:

> [1] 2021/08/09 12:44:32.927237 [TRC] 10.28.11.26:53972 - cid:2 - <<- [PUB sap.kyma.custom.appname.DocuSing_BOAccount_DocuSign.Updated.v1 665]
> [1] 2021/08/09 12:44:32.927290 [TRC] 10.28.11.26:53972 - cid:2 - <<- MSG_PAYLOAD: ...payload...

And that's all. There is no -->> [MSG ...] as with any other event type. Means it didn't find a subscriber.
Because event in NATS server is DocuSing_BOAccount_DocuSign.Updated.v1
And the subscription in NATS server is for DocuSingBOAccountDocuSign.Updated.v1

Kyma 1.23.0
**Expected result**

The event should be delivered according to the subscription. Even if the type contains underscores.

**Actual result**

The event with an underscore in the first or the second segments is not delivered to the subscription

**Steps to reproduce**

1. Subscribe a function to an event type that contains an underscore.
2. Send an event of this type to Kyma from the application
3. Observe that the event is not received by the function. But instead processed as described above.

**Comment by marcobebway** [comment] 2021-08-09 14:51
Could you please provide the subscription yaml descriptor and a sample publish payload that you use?

**Comment by VishnAndr** [comment] 2021-08-09 21:19
Here is the subscription and sample event.
[subscription.txt](https://github.com/kyma-project/kyma/files/6957505/subscription.txt)
[sampleEvent.txt](https://github.com/kyma-project/kyma/files/6957508/sampleEvent.txt)

**Comment by marcobebway** [comment] 2021-08-10 15:12
Can you please try the attached Event payload?

[event.txt](https://github.com/kyma-project/kyma/files/6962726/event.txt)

Basically I changed
- `"event-type": "DocuSing_BO.Account_DocuSign.Updated"` to
- `"event-type": "DocuSingBOAccountDocuSign.Updated"` to match the created underlying infra.

**Comment by VishnAndr** [comment] 2021-08-11 10:26
I'm not getting where you suggest to change it exactly. Is it in the sample event? The event is sent from SAP Cloud for Customer by SAP Cloud for Customer solution. Not by myself :)
All other events coming from this SAP solution works fine. Except this one which contains underscores.

**Comment by VishnAndr** [comment] 2021-08-11 21:33
And it's not clear what would be the reason to change the event when the two pieces of underlying infra do not much each other. The one removes underscores (btw the cloud events spec allows them), the other doesn't remove them.

**Comment by sayanh** [comment] 2021-08-17 12:45
We don't do the event type cleaning for cloud events flow. It is by design. The issue was the event type didn't conform to SAP Event Specification which was unusual. Underscores are not permitted by that specification. We need to understand the C4C CE event flow better to make changes.

@k15r: let's discuss offline what could be done here.

**Comment by mfaizanse** [comment] 2022-05-06 08:30
Since this [PR](https://github.com/kyma-project/kyma/pull/13608) is merged, check if this flow is working now?

**Comment by k15r** [comment] 2022-05-06 12:04
It could be working already, but further checks for cloudevents and legacy events are required.

**Comment by mfaizanse** [comment] 2022-06-14 13:01
```
cat << EOF | kubectl apply -f -
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: test-noapp
  namespace: tunas-testing
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.appname.DocuSing_BO.Account_DocuSign.Updated.v1
  protocol: ""
  protocolsettings: {}
  sink: http://test.tunas-testing.svc.cluster.local
EOF
```

**Closed** 2022-06-15 07:20 UTC
Labels: area/eventing
