### ISSUE TITLE
Service classes are not added to environment after binding operation.

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#1954] opened 2018-12-06 14:27 UTC
**Description**

The service classes with registered API are not added to the service catalog in the environment if the remote environment is already bound to that environment. 

**Expected result**

The changes in remote environment APIs and Event catalogs must be reflected in Service Catalog.

**Actual result**

Service classes are only added during the bind operation.

**Steps to reproduce**

- Create a remote environment with one API:
- Bind RE to `production` environment
- Add two additional APIs
- Service Catalog will display only one API

**Workaround**

- Unbind RE from Environment
- Bind RE to Environment again.

<img width="1648" alt="screen shot 2018-12-06 at 3 22 14 pm" src="https://user-images.githubusercontent.com/8614653/49590092-3e7d0e00-f96b-11e8-8f7a-61eee0a85aaa.png">
<img width="1654" alt="screen shot 2018-12-06 at 3 22 27 pm" src="https://user-images.githubusercontent.com/8614653/49590093-3e7d0e00-f96b-11e8-8bea-d496a77c8b8d.png">

Screenshots are taken after workaround had been applied.

**Comment by adamwalach** [comment] 2018-12-20 12:35
The issue is caused by wrong label assigned to ServiceBroker.
We have 2 places where labels are defined:
* label is taken from environment variables
* hardcoded in facade.go
Value taken from EV is used in Service selector and it is used to search for Brokers.
The hardcoded one is used to create a ServiceBroker.

Proposed fix changes the search function to use the hardcoded value.

**Closed** 2019-01-02 09:33 UTC
Labels: area/service-catalog, bug
