### ISSUE TITLE
Application connector upgrade recreates app-connector-certs and requires all the applications to reconnect

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#10759] opened 2021-03-01 07:52 UTC
**Description**

Helm upgrade on application-connector chart recreates the app-connector-certs secret in istio-system namespace. Helm creates empty cacert field and then post-upgrade job (application-connector-certs-setup-job) generates a new cacert.

**Expected result**

The secret is created only if doesn't exist.

**Actual result**

New cacert value makes all application connections rejected. The upgrade test fails:
https://terminalizer.com/view/f55226d14700

**Steps to reproduce**

- Install Kyma
- connect Varkes (Commerce Mock) and register some APIs
- check if connection works with curl https://<commerce-mock-url>/remote/apis
- execute upgrade on application-connector (can be the same version)
- check if connection works with curl https://<commerce-mock-url>/remote/apis

I created also a test for that, but it is not merged yet ([PR](https://github.com/kyma-project/kyma/pull/10698)). You can execute it from my branch:

```
git clone git@github.com:pbochynski/kyma.git
cd kyma
git checkout kyma-js
cd tests/fast-integration
npm install 
npm link 
kyma-js provision k3d 
npx mocha upgrade-test/upgrade-test.js -b
```

In the result you should get the test failure:
```
  6 passing (15m)
  1 failing

  1) Kyma end to end upgrade tests
       order.created.v1 event should trigger the lastorder function after upgrade:
     Error: Cannot send event, the response from event gateway
500: Internal Server Error: {"error":"Error: socket hang up"}
```
The test is installing Kyma 1.19.1 and upgrades it to the master with the new eventing, but the problem is observed on any upgrade of application-connector.

**Troubleshooting**

**Comment by pbochynski** [comment] 2021-03-03 10:20
I think the PR doesn't solve the issue.
You can test your PR with the following commands:
```
git checkout -b ralikio-bugfixes/cert-upgrade-removal master
git pull https://github.com/ralikio/kyma.git bugfixes/cert-upgrade-removal
cd tests/fast-integration
npm install
./kyma.js provision k3d
export DEBUG=true 
npx mocha -b upgrade-test/upgrade-test.js 
```

Developer mode version (quicker):
```
git checkout -b ralikio-bugfixes/cert-upgrade-removal master
git pull https://github.com/ralikio/kyma.git bugfixes/cert-upgrade-removal
cd tests/fast-integration
npm install
./kyma.js provision k3d
export DEBUG=true 
./kyma.js install --skip-components monitoring,logging,tracing,kiali,console,dex --new-eventing
```
Now modify `test/2-commerce-mock.js` file and skip cleanup step:
```
 it.skip("Test namespaces should be deleted", async function () {
    await cleanMockTestFixture("mocks", testNamespace, false);
  });
```
Execute the test:
```
npx mocha -b test/2-commerce-mock.js
```
It should pass. The commerce mock should still exist and the remote apis should be available:
```
curl https://commerce.local.kyma.dev/remote/apis
```
Now upgrade application-connector:
```
./kyma.js install --upgrade --components application-connector --new-eventing
```
Now check if commerce mock still can connect to Kyma:
```
curl https://commerce.local.kyma.dev/remote/apis
```
If you get `{"error":"Error: socket hang up"}` you need to fix it.
If you think you fixed it, execute the steps from commerce-mock test again.

**Comment by pbochynski** [comment] 2021-03-15 21:09
Any updates about that? @ralikio

**Comment by ralikio** [comment] 2021-03-18 10:06
@pbochynski Sorry for the delay. The issue is undergoing review.

**Comment by ralikio** [comment] 2021-03-19 12:45
@pbochynski The fix has ben merged to master branch.

**Closed** 2021-05-20 07:40 UTC
Labels: area/application-connector, bug, priority/critical
