### ISSUE TITLE
Istio does not block traffic between Service(destination) and Pod(source)

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#1453] opened 2018-10-29 08:11 UTC
**Description**
We execute the following test scenario:
1. Setup: create RemoteEnvironment, EnvironmentMapping, deployments (`fake-gateway`, `gateway-client`) and set-up Istio **Deniers and Rules**
2. Provision a ServiceClass
3. Perform binding
4. Add a BindingUsage
5. The `gateway-client` can call the `fake-gateway` (an environment variable with Gateway URL is injected, Istio allows the call)
6. Remove BindingUsage
5. The `gateway-client` cannot call the `fake-gateway` (there is no environment variable with Gateway URL, Istio blocks the call)

After some time (basically is after 4 test execution) Istio stops blocking traffic between Service (destination) and Pod (source) in case of 5th step. 

**Expected result**

When proper denier is configured then Istio blocks traffic between Service (destination) and Pod (source)

**Steps to reproduce**

This issue currently can be reproduced only on Cluster installation. 
To reproduced that you need to create your own cluster. Then install there [Stability Checker](https://github.com/kyma-project/kyma/tree/master/tools/stability-checker#installation) and after and after a few executions the `TestRemoteEnvironmentAPIAccess` test will continuously end with error on step 5. 

_EDIT: The easiest way to reproduce it is to follow the short guide from this repo:_ https://github.com/mszostok/re-e2e-tester

**Comment by piotrmsc** [comment] 2018-11-02 06:47
I can confirm, the issue is reproducible but in my case it was not after 4 executions but after an hour. Once tests start to fail restart of istio-policy helps. I have scaled policy to have 2 instances and it helped but only for a while, after 4 hours it happened again. We do not modify mixer configuration despite changing zipkin url to point to kyma. For me it looks like performance issue with istio policy. My proposal : Together with @mszostok we will isolate istio setup and create a test that is creating deniers and modify labels on sample pods in order to report an issue in istio. Created repo by Mateusz in the issue description requires kyma, but for reporting an issue I would not like to have any dependencies.

**Comment by piotrmsc** [comment] 2018-11-08 10:58
I have created the app https://github.com/piotrmsc/istio-denier-testing for reporting the issue to istio, however, with this application, I cannot reproduce reported here issue. I will close this issue and we will continue debugging together with @mszostok in the follow-up.

**Closed by piotrmsc** 2018-11-08 10:58 UTC
Labels: area/service-mesh, bug
