### ISSUE TITLE
Subscription not detected

### ISSUE THREAD

**Issue by pablo-abad** [kyma-project/kyma#1906] opened 2018-12-04 10:17 UTC
I created the following subscription:
```
apiVersion: eventing.kyma.cx/v1alpha1
kind: Subscription
metadata:
  name: santa-orders-subscription
  labels:
    app: "santa-orders-service"
spec:
  endpoint: http://santa-orders-service.santa:8080/orders
  push_request_timeout_ms: 2000
  max_inflight: 400
  include_subscription_name_header: true
  event_type: order.created
  event_type_version: v1
  source_id: ec-default
```
Deleted and recreated a couple of times, but it was not detected until I manually deleted the core-push pods, so they could be recreated.

To add more information to reproduce the problem, initially I had a syntax mistake in the resource definition (indentation of source_id):
```
apiVersion: eventing.kyma.cx/v1alpha1
kind: Subscription
metadata:
  name: santa-orders-subscription
  labels:
    app: "santa-orders-service"
spec:
  endpoint: http://santa-orders-service.santa:8080/orders
  push_request_timeout_ms: 2000
  max_inflight: 400
  include_subscription_name_header: true
  event_type: order.created
  event_type_version: v1
source_id: ec-default
```
This subscription seemed to be detected, but as it was erroneous it was of course rejected. After removing it, fixing the error and applying the definition again, it did not work.

>Note: Please sync with pablo-abad

 >Hint: could be some kind of caching, wrong logic in the push controller.

Steps followed by pablo-abad
* Created invalid subscription
* Identified the problem by seeing the subscription-validator logs
* Fixed the problem in subscription custom resource
* Recreated the subscription custom resource few times
* Still NATS subscription was not created
* Problem was only fixed by restarting push application

**AC**
* The NATS subscription gets created when a invalid subscription custom resource error has been fixed.

**Comment by radufa** [comment] 2018-12-07 07:50
Perhaps we can use a "validation" webhook here so that invalid subscriptions should not be accepted by the system and the "creator" of a subscription (possible an application) should receive a feedback ASAP.

**Comment by abbi-gaurav** [comment] 2018-12-10 12:03
I would propose to implement a validation webhook separately. In this task, we should first understand what is the problem and then address it.

At this point, we do not know for sure if using a validation webhook will fix the problem for sure.

**Comment by marcobebway** [comment] 2019-01-02 11:54
**I could not reproduce the bug on the cluster or locally.**

Here are the steps I followed:

1. create an event-activation resource

    ```yaml
    apiVersion: applicationconnector.kyma-project.io/v1alpha1
    kind: EventActivation
    metadata:
      name: santa-orders-event-activation
      labels:
        example: santa-orders-event-activation
    spec:
      sourceId: ec-default
    ```

2. create a **syntactically** invalid subscription resource:

    ```yaml
    apiVersion: eventing.kyma-project.io/v1alpha1
    kind: Subscription
    metadata:
      name: santa-orders-subscription
      labels:
        app: "santa-orders-service"
    spec:
      endpoint: http://event-email-service.test-namespace:3000/v1/events/register
      push_request_timeout_ms: 2000
      max_inflight: 400
      include_subscription_name_header: true
      event_type: order.created
      event_type_version: v1
    source_id: ec-default
    ```

3. publish an event:

    ```bash
    curl -i -H "Content-Type: application/json" -X POST http://core-publish.kyma-system:8080/v1/events -d '{"source-id": "ec-default", "event-type": "order.created", "event-type-version": "v1", "event-time": "2018-11-02T22:08:41+00:00", "data": {"event":{"customer":{"customerID": "1234", "uid": "rick.sanchez@mail.com"}}}}'
    ```

4. check the logs:

    **sub-validator app logs**

    ```bash
    2019/01/02 11:13:36 Event Activation custom resource created:
        &{{ } {santa-orders-event-activation  test-namespace /apis/applicationconnector.kyma-project.io/v1alpha1/namespaces/test-namespace/eventactivations/santa-orders-event-activation 7342b670-0e7f-11e9-844b-6ab0a82b5037 11520 1 2019-01-02 11:13:36 +0000 UTC <nil> <nil> map[example:santa-orders-event-activation] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"applicationconnector.kyma-project.io/v1alpha1","kind":"EventActivation","metadata":{"annotations":{},"labels":{"example":"santa-orders-event-activation"},"name":"santa-orders-event-activation","namespace":"test-namespace"},"spec":{"sourceId":"ec-default"}}
    ] [] nil [] } { ec-default}}

    2019/01/02 11:14:11 Subscription custom resource created:
        &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:santa-orders-subscription GenerateName: Namespace:test-namespace SelfLink:/apis/eventing.kyma-project.io/v1alpha1/namespaces/test-namespace/subscriptions/santa-orders-subscription UID:87abf105-0e7f-11e9-844b-6ab0a82b5037 ResourceVersion:11556 Generation:1 CreationTimestamp:2019-01-02 11:14:11 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[app:santa-orders-service] Annotations:map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"eventing.kyma-project.io/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"labels":{"app":"santa-orders-service"},"name":"santa-orders-subscription","namespace":"test-namespace"},"source_id":"ec-default","spec":{"endpoint":"http://event-email-service.test-namespace:3000/v1/events/register","event_type":"order.created","event_type_version":"v1","include_subscription_name_header":true,"max_inflight":400,"push_request_timeout_ms":2000}}
    ] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} SubscriptionSpec:{Endpoint:http://event-email-service.test-namespace:3000/v1/events/register IncludeSubscriptionNameHeader:true MaxInflight:400 PushRequestTimeoutMS:2000 EventType:order.created EventTypeVersion:v1 SourceID:} Status:{Conditions:[]}}
    2019/01/02 11:14:11 Error: Update Subscription call failed for subscription:
        &{{ } {santa-orders-subscription  test-namespace /apis/eventing.kyma-project.io/v1alpha1/namespaces/test-namespace/subscriptions/santa-orders-subscription 87abf105-0e7f-11e9-844b-6ab0a82b5037 11556 1 2019-01-02 11:14:11 +0000 UTC <nil> <nil> map[app:santa-orders-service] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"eventing.kyma-project.io/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"labels":{"app":"santa-orders-service"},"name":"santa-orders-subscription","namespace":"test-namespace"},"source_id":"ec-default","spec":{"endpoint":"http://event-email-service.test-namespace:3000/v1/events/register","event_type":"order.created","event_type_version":"v1","include_subscription_name_header":true,"max_inflight":400,"push_request_timeout_ms":2000}}
    ] [] nil [] } {http://event-email-service.test-namespace:3000/v1/events/register true 400 2000 order.created v1 } {[{events-activated False 2019-01-02 11:14:11.157005089 +0000 UTC m=+6987.904942777  }]}},
        Subscription.eventing.kyma-project.io "santa-orders-subscription" is invalid: []: Invalid value: map[string]interface {}{"kind":"Subscription", "apiVersion":"eventing.kyma-project.io/v1alpha1", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"eventing.kyma-project.io/v1alpha1\",\"kind\":\"Subscription\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"santa-orders-service\"},\"name\":\"santa-orders-subscription\",\"namespace\":\"test-namespace\"},\"source_id\":\"ec-default\",\"spec\":{\"endpoint\":\"http://event-email-service.test-namespace:3000/v1/events/register\",\"event_type\":\"order.created\",\"event_type_version\":\"v1\",\"include_subscription_name_header\":true,\"max_inflight\":400,\"push_request_timeout_ms\":2000}}\n"}, "namespace":"test-namespace", "resourceVersion":"11556", "creationTimestamp":"2019-01-02T11:14:11Z", "selfLink":"/apis/eventing.kyma-project.io/v1alpha1/namespaces/test-namespace/subscriptions/santa-orders-subscription", "generation":1, "name":"santa-orders-subscription", "uid":"87abf105-0e7f-11e9-844b-6ab0a82b5037", "labels":map[string]interface {}{"app":"santa-orders-service"}, "clusterName":""}, "spec":map[string]interface {}{"max_inflight":400, "push_request_timeout_ms":2000, "event_type":"order.created", "event_type_version":"v1", "source_id":"", "endpoint":"http://event-email-service.test-namespace:3000/v1/events/register", "include_subscription_name_header":true}, "status":map[string]interface {}{"conditions":[]interface {}{map[string]interface {}{"status":"False", "last_transition_time":"2019-01-02T11:14:11Z", "reason":"", "message":"", "type":"events-activated"}}}}: validation failure list:
    spec.source_id in body should be at least 1 chars long
    ```

    **publish app logs**

    ```bash
    2019/01/02 11:14:41 PublishHandler :: handlePublishRequest ::  Handling request.
    2019/01/02 11:14:41 PublishHandler :: handlePublishRequest :: Creating publish-to-internal-broker trace span
    2019/01/02 11:14:41 PublishHandler :: parseRequest :: Unmarsharlling request
    2019/01/02 11:14:41 PublishHandler :: handlePublishRequest :: Generating event id.
    2019/01/02 11:14:41 PublishHandler :: handlePublishRequest :: Constructing event body
    2019/01/02 11:14:41 PublishHandler :: handlePublishRequest :: Publishing event.
    2019/01/02 11:14:41 PublishHandler :: publishEvent :: Publish to Subject: ec-default.order\.created.v1
    2019/01/02 11:14:41 PublishHandler :: handlePublishRequest :: Event published, sending response.
    2019/01/02 11:14:41 PublishHandler :: handlePublishRequest :: OK.
    ```

    **push app has logs**

5. delete the invalid subscription resource

6. check the logs:

    **sub-validator app logs**

    ```bash
    2019/01/02 11:15:30 Subscription custom resource deleted:
        &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:santa-orders-subscription GenerateName: Namespace:test-namespace SelfLink:/apis/eventing.kyma-project.io/v1alpha1/namespaces/test-namespace/subscriptions/santa-orders-subscription UID:87abf105-0e7f-11e9-844b-6ab0a82b5037 ResourceVersion:11649 Generation:1 CreationTimestamp:2019-01-02 11:14:11 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[app:santa-orders-service] Annotations:map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"eventing.kyma-project.io/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"labels":{"app":"santa-orders-service"},"name":"santa-orders-subscription","namespace":"test-namespace"},"source_id":"ec-default","spec":{"endpoint":"http://event-email-service.test-namespace:3000/v1/events/register","event_type":"order.created","event_type_version":"v1","include_subscription_name_header":true,"max_inflight":400,"push_request_timeout_ms":2000}}
    ] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} SubscriptionSpec:{Endpoint:http://event-email-service.test-namespace:3000/v1/events/register IncludeSubscriptionNameHeader:true MaxInflight:400 PushRequestTimeoutMS:2000 EventType:order.created EventTypeVersion:v1 SourceID:} Status:{Conditions:[]}}
    ```

    **push app logs**

    ```bash
    2019/01/02 11:15:30 Deleted Subscription &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:santa-orders-subscription GenerateName: Namespace:test-namespace SelfLink:/apis/eventing.kyma-project.io/v1alpha1/namespaces/test-namespace/subscriptions/santa-orders-subscription UID:87abf105-0e7f-11e9-844b-6ab0a82b5037 ResourceVersion:11649 Generation:1 CreationTimestamp:2019-01-02 11:14:11 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[app:santa-orders-service] Annotations:map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"eventing.kyma-project.io/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"labels":{"app":"santa-orders-service"},"name":"santa-orders-subscription","namespace":"test-namespace"},"source_id":"ec-default","spec":{"endpoint":"http://event-email-service.test-namespace:3000/v1/events/register","event_type":"order.created","event_type_version":"v1","include_subscription_name_header":true,"max_inflight":400,"push_request_timeout_ms":2000}}
    ] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} SubscriptionSpec:{Endpoint:http://event-email-service.test-namespace:3000/v1/events/register IncludeSubscriptionNameHeader:true MaxInflight:400 PushRequestTimeoutMS:2000 EventType:order.created EventTypeVersion:v1 SourceID:} Status:{Conditions:[]}}
    2019/01/02 11:15:30 handling EventBus stop request for subscription test-namespace-santa-orders-subscription in namespace test-namespace
    2019/01/02 11:15:30 there was no subscription test-namespace-santa-orders-subscription in namespace test-namespace
    ```

7. create a valid subscription resource

    ```yaml
    apiVersion: eventing.kyma-project.io/v1alpha1
    kind: Subscription
    metadata:
      name: santa-orders-subscription
      labels:
        app: "santa-orders-service"
    spec:
      endpoint: http://event-email-service.test-namespace:3000/v1/events/register
      push_request_timeout_ms: 2000
      max_inflight: 400
      include_subscription_name_header: true
      event_type: order.created
      event_type_version: v1
      source_id: ec-default
    ```

8. publish another event:

    ```bash
    curl -i -H "Content-Type: application/json" -X POST http://core-publish.kyma-system:8080/v1/events -d '{"source-id": "ec-default", "event-type": "order.created", "event-type-version": "v1", "event-time": "2018-11-02T22:08:41+00:00", "data": {"event":{"customer":{"customerID": "1234", "uid": "rick.sanchez@mail.com"}}}}'
    ```

9. check the logs:

    **sub-validator app logs**

    ```bash
    2019/01/02 11:16:01 Subscription custom resource created:
        &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:santa-orders-subscription GenerateName: Namespace:test-namespace SelfLink:/apis/eventing.kyma-project.io/v1alpha1/namespaces/test-namespace/subscriptions/santa-orders-subscription UID:c96d39d7-0e7f-11e9-844b-6ab0a82b5037 ResourceVersion:11679 Generation:1 CreationTimestamp:2019-01-02 11:16:01 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[app:santa-orders-service] Annotations:map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"eventing.kyma-project.io/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"labels":{"app":"santa-orders-service"},"name":"santa-orders-subscription","namespace":"test-namespace"},"spec":{"endpoint":"http://event-email-service.test-namespace:3000/v1/events/register","event_type":"order.created","event_type_version":"v1","include_subscription_name_header":true,"max_inflight":400,"push_request_timeout_ms":2000,"source_id":"ec-default"}}
    ] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} SubscriptionSpec:{Endpoint:http://event-email-service.test-namespace:3000/v1/events/register IncludeSubscriptionNameHeader:true MaxInflight:400 PushRequestTimeoutMS:2000 EventType:order.created EventTypeVersion:v1 SourceID:ec-default} Status:{Conditions:[]}}
    2019/01/02 11:16:01 Subscription custom resource updated, old:
        &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:santa-orders-subscription GenerateName: Namespace:test-namespace SelfLink:/apis/eventing.kyma-project.io/v1alpha1/namespaces/test-namespace/subscriptions/santa-orders-subscription UID:c96d39d7-0e7f-11e9-844b-6ab0a82b5037 ResourceVersion:11679 Generation:1 CreationTimestamp:2019-01-02 11:16:01 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[app:santa-orders-service] Annotations:map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"eventing.kyma-project.io/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"labels":{"app":"santa-orders-service"},"name":"santa-orders-subscription","namespace":"test-namespace"},"spec":{"endpoint":"http://event-email-service.test-namespace:3000/v1/events/register","event_type":"order.created","event_type_version":"v1","include_subscription_name_header":true,"max_inflight":400,"push_request_timeout_ms":2000,"source_id":"ec-default"}}
    ] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} SubscriptionSpec:{Endpoint:http://event-email-service.test-namespace:3000/v1/events/register IncludeSubscriptionNameHeader:true MaxInflight:400 PushRequestTimeoutMS:2000 EventType:order.created EventTypeVersion:v1 SourceID:ec-default} Status:{Conditions:[{Type:events-activated Status:True LastTransitionTime:2019-01-02 11:16:01.468152021 +0000 UTC m=+7098.216087215 Reason: Message:}]}}
        new: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:santa-orders-subscription GenerateName: Namespace:test-namespace SelfLink:/apis/eventing.kyma-project.io/v1alpha1/namespaces/test-namespace/subscriptions/santa-orders-subscription UID:c96d39d7-0e7f-11e9-844b-6ab0a82b5037 ResourceVersion:11680 Generation:1 CreationTimestamp:2019-01-02 11:16:01 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[app:santa-orders-service] Annotations:map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"eventing.kyma-project.io/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"labels":{"app":"santa-orders-service"},"name":"santa-orders-subscription","namespace":"test-namespace"},"spec":{"endpoint":"http://event-email-service.test-namespace:3000/v1/events/register","event_type":"order.created","event_type_version":"v1","include_subscription_name_header":true,"max_inflight":400,"push_request_timeout_ms":2000,"source_id":"ec-default"}}
    ] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} SubscriptionSpec:{Endpoint:http://event-email-service.test-namespace:3000/v1/events/register IncludeSubscriptionNameHeader:true MaxInflight:400 PushRequestTimeoutMS:2000 EventType:order.created EventTypeVersion:v1 SourceID:ec-default} Status:{Conditions:[{Type:events-activated Status:True LastTransitionTime:2019-01-02 11:16:01 +0000 UTC Reason: Message:}]}}
    ```

    **publish app logs**

    ```bash
    2019/01/02 11:16:08 PublishHandler :: handlePublishRequest ::  Handling request.
    2019/01/02 11:16:08 PublishHandler :: handlePublishRequest :: Creating publish-to-internal-broker trace span
    2019/01/02 11:16:08 PublishHandler :: parseRequest :: Unmarsharlling request
    2019/01/02 11:16:08 PublishHandler :: handlePublishRequest :: Generating event id.
    2019/01/02 11:16:08 PublishHandler :: handlePublishRequest :: Constructing event body
    2019/01/02 11:16:08 PublishHandler :: handlePublishRequest :: Publishing event.
    2019/01/02 11:16:08 PublishHandler :: publishEvent :: Publish to Subject: ec-default.order\.created.v1
    2019/01/02 11:16:08 PublishHandler :: handlePublishRequest :: Event published, sending response.
    2019/01/02 11:16:08 PublishHandler :: handlePublishRequest :: OK.
    ```

    **push app logs**

    ```bash
    2019/01/02 11:16:01 Stop old NATS Subscription &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:santa-orders-subscription GenerateName: Namespace:test-namespace SelfLink:/apis/eventing.kyma-project.io/v1alpha1/namespaces/test-namespace/subscriptions/santa-orders-subscription UID:c96d39d7-0e7f-11e9-844b-6ab0a82b5037 ResourceVersion:11679 Generation:1 CreationTimestamp:2019-01-02 11:16:01 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[app:santa-orders-service] Annotations:map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"eventing.kyma-project.io/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"labels":{"app":"santa-orders-service"},"name":"santa-orders-subscription","namespace":"test-namespace"},"spec":{"endpoint":"http://event-email-service.test-namespace:3000/v1/events/register","event_type":"order.created","event_type_version":"v1","include_subscription_name_header":true,"max_inflight":400,"push_request_timeout_ms":2000,"source_id":"ec-default"}}
    ] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} SubscriptionSpec:{Endpoint:http://event-email-service.test-namespace:3000/v1/events/register IncludeSubscriptionNameHeader:true MaxInflight:400 PushRequestTimeoutMS:2000 EventType:order.created EventTypeVersion:v1 SourceID:ec-default} Status:{Conditions:[]}}
    2019/01/02 11:16:01 Start NATS Subscription &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:santa-orders-subscription GenerateName: Namespace:test-namespace SelfLink:/apis/eventing.kyma-project.io/v1alpha1/namespaces/test-namespace/subscriptions/santa-orders-subscription UID:c96d39d7-0e7f-11e9-844b-6ab0a82b5037 ResourceVersion:11680 Generation:1 CreationTimestamp:2019-01-02 11:16:01 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[app:santa-orders-service] Annotations:map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"eventing.kyma-project.io/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"labels":{"app":"santa-orders-service"},"name":"santa-orders-subscription","namespace":"test-namespace"},"spec":{"endpoint":"http://event-email-service.test-namespace:3000/v1/events/register","event_type":"order.created","event_type_version":"v1","include_subscription_name_header":true,"max_inflight":400,"push_request_timeout_ms":2000,"source_id":"ec-default"}}
    ] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} SubscriptionSpec:{Endpoint:http://event-email-service.test-namespace:3000/v1/events/register IncludeSubscriptionNameHeader:true MaxInflight:400 PushRequestTimeoutMS:2000 EventType:order.created EventTypeVersion:v1 SourceID:ec-default} Status:{Conditions:[{Type:events-activated Status:True LastTransitionTime:2019-01-02 11:16:01 +0000 UTC Reason: Message:}]}}
    2019/01/02 11:16:01 handling EventBus stop request for subscription test-namespace-santa-orders-subscription in namespace test-namespace
    2019/01/02 11:16:01 there was no subscription test-namespace-santa-orders-subscription in namespace test-namespace
    2019/01/02 11:16:01 handling EventBus Subscription start request
    2019/01/02 11:16:01 attempting establishing NATS Streaming subscription test-namespace-santa-orders-subscription in namespace test-namespace
    2019/01/02 11:16:01 established NATS Streaming subscription
    ```

10. check the tracing UI which has two traces. An incomplete trace for the invalid subscription, and another complete trace for the valid subscription.

<img width="1419" alt="trace" src="https://user-images.githubusercontent.com/24314423/50590653-232ef100-0e8c-11e9-8cb7-f2a19a020f4c.png">


**Conclusion**
After deleting the invalid subscription resource and creating a valid one, the push app starts delivering messages to subscribers, also the tracing UI confirms that.

**Comment by marcobebway** [comment] 2019-01-02 11:59
Closing this issue and mark as wontfix.

**Closed by marcobebway** 2019-01-02 11:59 UTC
Labels: area/eventing, bug, wontfix
