### ISSUE TITLE
Adminstration links direct to home page, list of environments

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#904] opened 2018-09-24 13:56 UTC
**Description**

Links in the administration area direct to the list of environments instead to the desired page

**Steps to reproduce**

1. Click on the administration area from the left navigation
2. Click on "Remote Environments", you will be directed to the list of Environments and not the Remote Environments page

**Troubleshooting**

Navigating directly to the page works e.g. copy and pasting the following URL: https://console.mycluster.cluster.kyma.cx/home/settings/remoteEnvs

**Comment by hardl** [comment] 2018-09-25 07:48
I could not reproduce this issue, could you provide more details please, e.g. which URL is tried to be opened after clicking on "Remote Environments", js console errors, etc.

**Comment by kwiatekus** [comment] 2018-09-25 14:35
It was fixed by those PRs :
https://github.com/kyma-project/kyma/pull/429/files 
https://github.com/kyma-project/console/pull/76

22 days ago

Fixed in console in version 0.1.28

**Closed by kwiatekus** 2018-09-25 14:35 UTC
Labels: area/console, priority/critical, question
