### ISSUE TITLE
Flaky controller tests

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#12058] opened 2021-09-08 11:48 UTC
**Description**

Turns out the eventing-controller tests are flaky. Here's an [instance](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/post-kyma-components-eventing-controller/1434884050375413760) of a post-submit job that failed.

**Expected result**

The tests should be deterministic.

**Actual result**

The tests are flaky.

**Steps to reproduce**

Run the tests more than once, 1 out of 3 runs will fail as an observation.

**Comment by pxsalehi** [comment] 2021-09-09 12:51
Related also to #11874

**Comment by thandayuthapani** [comment] 2021-12-02 12:27
Tests seems not be flaky.  By checking the job history of `post-kyma-components-eventing-controller` and `pre-kyma-components-eventing-controller` and running the tests in the local multiple times, it can be concluded that the tests are not flaky.  If found otherwise, we can reopen this issue.

**Comment by pxsalehi** [comment] 2021-12-03 09:47
I think `post-kyma-components-eventing-controller` should be the reference for detecting flakiness, as clearly it runs on code that is merged, and functionality-wise should be correct. IMO, it is flaky judging by the past runs:

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-kyma-components-eventing-controller?buildId=1466071949774950400
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-kyma-components-eventing-controller?buildId=1442765134983335936

And most of the failures come from our BEB subscription controller, with recurring issues about concurrent map modifications.

**Comment by pxsalehi** [comment] 2021-12-10 11:52
The flakiness is caused by subscription reconciler tests for BEB and NATS, which should be addressed by the following two PR:
https://github.com/kyma-project/kyma/pull/12826
https://github.com/kyma-project/kyma/pull/12781

As agreed in the team, we will keep the issue open until we see that the following post-submit job is not flaky:
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/post-kyma-components-eventing-controller

**Comment by mfaizanse** [comment] 2022-01-11 09:16
All the runs after the PRs: #12826 and #12781 are green. The `post-kyma-components-eventing-controller` job does not seems flaky anymore. Let's close it for now.

**Closed by mfaizanse** 2022-01-11 09:16 UTC
Labels: bug, area/eventing
