### ISSUE TITLE
New python serverless function from kyma dashboard

### ISSUE THREAD

**Issue by DBusAI** [kyma-project/kyma#13102] opened 2022-01-18 14:13 UTC
When I try to create a new python function from busola: 
The Source is :
```
module.exports = { 
  main: function (event, context) {
    return "Hello World!";
  }
}
```
And dependencies is:
```
{ 
  "name": "any-combination",
  "version": "1.0.0",
  "dependencies": {}
}
```
But for **python** it has to be smth like :
```
def main(event, context):
    return 'Hello World!'
```
Kyma CLI version: 2.0.0
Kyma cluster version: 2.0.1

**Comment by kwiatekus** [comment] 2022-02-04 08:33
@DBusAI Thank you for reporting.

First investigation shows that this can only be reproduced via UI
I follwoed the follwoing steps via CLI and the function was succesfully created

```
kyma init function -r python39
kyma apply function
```

@valentinvieriu please help resolving the issue

**Comment by kwiatekus** [comment] 2022-02-07 09:39
It seems like Kyma dashboard initialises python functions with wrong nodejs scaffold (handler and package.json)
Workaround:

Change the content of source into
```py
def main(event, context):
    return "hello world"
```
And cleanup the requirements

**Closed** 2022-02-09 07:31 UTC
Labels: kind/bug, area/console, area/serverless

**Comment by Lyczeq** [comment] 2022-02-09 07:52
Hi, the problem was fixed in the [PR](https://github.com/kyma-project/busola/pull/933). It should be on production soon.
