### ISSUE TITLE
Monitoring tests hang up

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#4119] opened 2019-05-16 12:05 UTC
**Description**

In some cases it is possible that the monitoring tests are running without end, causing tests to fail due to a timeout. This is because of https://github.com/kyma-project/kyma/blob/master/resources/monitoring/templates/tests/test-kube-prometheus.yaml#L55 not always killing the istio proxy process  

**Expected result**

The sidecar process is killed always

**Actual result**

In some cases the process is not killed resulting in a never ending test. This might be because of `SIGINT` in the command and not `SIGTERM` as in other tests. 

**Steps to reproduce**

**Troubleshooting**

```
kubectl describe pods -n kyma-system oct-tp-testsuite-all-2019-05-16-10-56-test-monitoring-0
Name:               oct-tp-testsuite-all-2019-05-16-10-56-test-monitoring-0
Namespace:          kyma-system
Priority:           0
PriorityClassName:  <none>
Node:               gke-qubu-default-pool-3ee91bfd-9gjw/10.132.0.29
Start Time:         Thu, 16 May 2019 10:57:03 +0200
Labels:             testing.kyma-project.io/created-by-octopus=true
                    testing.kyma-project.io/def-name=test-monitoring
                    testing.kyma-project.io/suite-name=testsuite-all-2019-05-16-10-56
Annotations:        sidecar.istio.io/inject=true
                    sidecar.istio.io/status={"version":"001657c4019471a4ff30af6387e69e87ff13504125c26e4151c64713d69d3c83","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs...
Status:             Running
IP:                 10.60.1.48
Controlled By:      ClusterTestSuite/testsuite-all-2019-05-16-10-56
Init Containers:
  istio-init:
    Container ID:  docker://520f92a1409f6e4ea1540a860a35ed50eaeb71bba9731d32e1431f67b469bc2e
    Image:         docker.io/istio/proxy_init:1.1.5
    Image ID:      docker-pullable://istio/proxy_init@sha256:17a746ca44a491e405bc88fc1923ade8afbcc95ecb572f43aec8ad4d9a43bb6b
    Port:          <none>
    Host Port:     <none>
    Args:
      -p
      15001
      -u
      1337
      -m
      REDIRECT
      -i
      10.0.0.1/8
      -x

      -b

      -d
      15020
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 16 May 2019 10:57:04 +0200
      Finished:     Thu, 16 May 2019 10:57:05 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:        10m
      memory:     10Mi
    Environment:  <none>
    Mounts:       <none>
Containers:
  test-monitoring:
    Container ID:  docker://3cf861cc241a0a696251b032d07f162e3f8cd8d7780b0a07c785830e3e9b2224
    Image:         eu.gcr.io/kyma-project/develop/tests/monitoring:06b8d357
    Image ID:      docker-pullable://eu.gcr.io/kyma-project/develop/tests/monitoring@sha256:e71b6f09d1a6337b9228d0a234be6fc42509c9fc8b7dc6f65825ad0b46f67a4e
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      sleep 10; /test-monitoring; exit_code=$?; pkill -INT pilot-agent; sleep 4; exit $exit_code;
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 16 May 2019 10:57:10 +0200
      Finished:     Thu, 16 May 2019 10:57:35 +0200
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  200Mi
    Requests:
      memory:     96Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from test-monitoring-token-vhqbt (ro)
  istio-proxy:
    Container ID:  docker://09dd92b34a112744e87b4f521124e2284769ade22efb5e4cc40a8c483c17612e
    Image:         docker.io/istio/proxyv2:1.1.5
    Image ID:      docker-pullable://istio/proxyv2@sha256:1f00a1bfd3f5b9cd8d3088fa254ec8cd95c72711d77999e4da656e4b36a78931
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --configPath
      /etc/istio/proxy
      --binaryPath
      /usr/local/bin/envoy
      --serviceCluster
      oct-tp-testsuite-all-2019-05-16-10-56-test-monitoring-0.kyma-system
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --discoveryAddress
      istio-pilot.istio-system:15010
      --zipkinAddress
      zipkin.kyma-system:9411
      --connectTimeout
      10s
      --proxyAdminPort
      15000
      --concurrency
      2
      --controlPlaneAuthPolicy
      NONE
      --statusPort
      15020
      --applicationPorts

    State:          Running
      Started:      Thu, 16 May 2019 10:57:10 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:      10m
      memory:   128Mi
    Readiness:  http-get http://:15020/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      POD_NAME:                      oct-tp-testsuite-all-2019-05-16-10-56-test-monitoring-0 (v1:metadata.name)
      POD_NAMESPACE:                 kyma-system (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      ISTIO_META_POD_NAME:           oct-tp-testsuite-all-2019-05-16-10-56-test-monitoring-0 (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:   kyma-system (v1:metadata.namespace)
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_METAJSON_ANNOTATIONS:    {"sidecar.istio.io/inject":"true"}

      ISTIO_METAJSON_LABELS:  {"testing.kyma-project.io/created-by-octopus":"true","testing.kyma-project.io/def-name":"test-monitoring","testing.kyma-project.io/suite-name":"testsuite-all-2019-05-16-10-56"}

      ISTIO_KUBE_APP_PROBERS:  {}
    Mounts:
      /etc/certs/ from istio-certs (ro)
      /etc/istio/proxy from istio-envoy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from test-monitoring-token-vhqbt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  test-monitoring-token-vhqbt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  test-monitoring-token-vhqbt
    Optional:    false
  istio-envoy:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  Memory
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.test-monitoring
    Optional:    true
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                                          Message
  ----    ------     ----  ----                                          -------
  Normal  Scheduled  49m   default-scheduler                             Successfully assigned kyma-system/oct-tp-testsuite-all-2019-05-16-10-56-test-monitoring-0 to gke-qubu-default-pool-3ee91bfd-9gjw
  Normal  Pulled     49m   kubelet, gke-qubu-default-pool-3ee91bfd-9gjw  Container image "docker.io/istio/proxy_init:1.1.5" already present on machine
  Normal  Created    49m   kubelet, gke-qubu-default-pool-3ee91bfd-9gjw  Created container
  Normal  Started    49m   kubelet, gke-qubu-default-pool-3ee91bfd-9gjw  Started container
  Normal  Pulling    49m   kubelet, gke-qubu-default-pool-3ee91bfd-9gjw  pulling image "eu.gcr.io/kyma-project/develop/tests/monitoring:06b8d357"
  Normal  Pulled     49m   kubelet, gke-qubu-default-pool-3ee91bfd-9gjw  Successfully pulled image "eu.gcr.io/kyma-project/develop/tests/monitoring:06b8d357"
  Normal  Created    49m   kubelet, gke-qubu-default-pool-3ee91bfd-9gjw  Created container
  Normal  Started    49m   kubelet, gke-qubu-default-pool-3ee91bfd-9gjw  Started container
  Normal  Pulled     49m   kubelet, gke-qubu-default-pool-3ee91bfd-9gjw  Container image "docker.io/istio/proxyv2:1.1.5" already present on machine
  Normal  Created    49m   kubelet, gke-qubu-default-pool-3ee91bfd-9gjw  Created container
  Normal  Started    49m   kubelet, gke-qubu-default-pool-3ee91bfd-9gjw  Started container
```

**Comment by Demonsthere** [comment] 2019-05-17 07:28
Update:
The test pod definition is missing a required option: `shareProcessNamespace: true`

**Comment by a-thaler** [comment] 2019-06-21 14:03
Closing the issue, please re-open if you think the problem is not solved

**Closed by a-thaler** 2019-06-21 14:03 UTC
Labels: area/monitoring, test-failing
