### ISSUE TITLE
Application Operator tests are unstable

### ISSUE THREAD

**Issue by aerfio** [kyma-project/kyma#7767] opened 2020-03-24 11:08 UTC
**Description**

Application Operator are failing recently on CI. Logs will be in comments

**Expected result**

They are stable

**Actual result**
They are not 😭

**Comment by aerfio** [comment] 2020-03-24 11:08
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1242041410140508161

**Comment by aerfio** [comment] 2020-03-24 12:17
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1242098536485490691

**Comment by aerfio** [comment] 2020-03-24 12:21
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-cli-integration-gke/1242239842377535488

**Comment by aerfio** [comment] 2020-03-25 08:53
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1242458408364281857

**Comment by nachtmaar** [comment] 2020-03-30 08:14
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1244510805404160002

**Comment by franpog859** [comment] 2020-04-07 11:21
The errors occur rarely, randomly, in different places and in different jobs. I cannot reproduce them and they could be just random errors

This is what I found:
- Call to `http://application-registry-external-api:8081/${APP}/v1/metadata/services/${SERVICE_ID}`
finished with status `500` and body `{“code":500,"error":"Internal error."}` four times, and with status `200` but there was no correct spec in it also four times
- Call to `${EVENTS_URL}/${APP}/v1/events ` finished with status `500` one time
- Call to `${EVENTS_URL}/${APP}/v1/events/subscribed` finished with status `200` but there was no correct event in it also one time

I enhanced Application Registry error responses in [this PR](https://github.com/kyma-project/test-infra/pull/2214) so next time if the error occurs it’ll be easier to debug
For now, I suggest closing this issue. You can reopen it if the error occurs again

**Closed** 2020-04-08 07:07 UTC
Labels: area/application-connector, test-failing
