### ISSUE TITLE
JetStream is disabled on all NATS cluster nodes when the storage is full

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#15220] opened 2022-08-22 16:19 UTC
**Description**

JetStream is disabled on all NATS cluster nodes when the storage is full.

**Steps to reproduce**

- Provision Kyma with evaluation or production profiles.
- Start a high pace load testing with more that 1.5K Events per second.
- Wait until the storage for NATS servers is full.

**Side effects**

- The Eventing publisher proxy failed to publish events:

  ```json
  {
      "caller":"nats/handler.go:195",
      "context":{
         "after":"sap.kyma.custom.commerce.order.updated.v095",
         "before":"sap.kyma.custom.commerce.order.updated.v095",
         "duration":5.001188431,
         "id":"3b213ed6-918f-4229-af71-1b7862e2419e",
         "responseBody":"context deadline exceeded",
         "source":"kyma",
         "statusCode":500
      },
      "logger":"nats-handler",
      "message":"Event dispatched",
      "timestamp":"2022-08-18T14:28:18Z"
   }
  ```

- The Eventing controller fails to reconciler Kyma subscriptions:

  ```json
  {
      "caller":"controller/controller.go:326",
      "context":{
         "controller":"jetstream-subscription-reconciler",
         "error":"context deadline exceeded",
         "name":"subscription-1",
         "namespace":"tunas",
         "object":{
            "name":"subscription-1",
            "namespace":"tunas"
         },
         "reconcileID":"13f1611a-dbf1-4bc7-8ce3-f21fe6d0bea9"
      },
      "message":"Reconciler error",
      "timestamp":"2022-08-18T19:09:12Z"
   }
  ```

- The Eventing dispatcher fails to deliver messages:

  ```json
  {
      "log":"nats: consumer not active on connection [10] for subscription on \"kyma.sap.kyma.custom.commerce.order.created.v100\"",
      "time":"2022-08-18T19:09:44.970147465Z"
  }
  ```

**Comment by nachtmaar** [comment] 2022-08-23 10:31
@marcobebway Do you have any script for `high pace load testing`? Just to make it as easy as possible to reproduce for the one who will be working on the ticket :)

**Comment by nachtmaar** [comment] 2022-09-30 11:44
I can confirm that using the load tester from @marcobebway we can reproduce this issue

**Comment by k15r** [comment] 2022-11-03 09:04
closing due to: #15998

**Closed by k15r** 2022-11-03 09:04 UTC
Labels: kind/bug, area/eventing
