### ISSUE TITLE
Many pipelines failing to provision Gardner cluster

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/kyma#16194] opened 2022-11-28 10:41 UTC
**Description**

The following pipelines:

- [kyma-upgrade-gardener-kyma2-minor-versions](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions)
- [kyma-upgrade-gardener-kyma2-to-main-reconciler-main](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main)

are consistently failing with a `#1: unable to provision gardener cluster: Provisioning timed out` error.

**Error logs**
```
X Provisioning Gardener(Azure) cluster
Error: All attempts fail:
#1: unable to provision gardener cluster: Provisioning timed out
2022-11-25 09:00:47 UTC [ERROR] PID:13 --- [/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/lib/gardener/azure.sh] gardener::cleanup:1 AN ERROR OCCURED! Take a look at preceding log entries.
Encountered an error
     at gardener::cleanup (/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/lib/gardener/azure.sh:31)
     at gardener::provision_cluster (/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/lib/gardener/azure.sh:1)
     at gardener::reprovision_cluster (/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/lib/gardener/gardener.sh:82)
     at gardener::provision_cluster (/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/lib/gardener/azure.sh:130)
     at main (/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/cluster-integration/kyma-upgrade-gardener-kyma2-minor-versions.sh:154)
```
**Expected result**

Gardner cluster provisioning should succeed.

**Comment by koala7659** [comment] 2022-11-29 10:13
Hello @khlifi411 The problem with failing provisioning gardener cluster seems to be with either `kyma cli` or `gardener api `. I looked at script that failed and I can see in that the failure is in a function where kyma cli is used to create (provision) new gardener cluster where Kyma is about to be installed for testing. 

It is hard to answer why this particular provisioning has failed. I think someone from @kyma-project/prow should look those errors and check if kyma-cli is used properly.

In the case everything is fine on script side, that would mean gardener API has a problem to create new cluster and I believe we should assign this ticket to **gardener team** for further investigation. 

The failing script can be found at location: 

`test-infra/prow/scripts/lib/gardener/gardener.sh`

Looking at the one failing function shows that kyma cli fails:
Line 64

```
gardener::provision_cluster() {
    log::info "Provision cluster: \"${CLUSTER_NAME}\""
    if [ "${#CLUSTER_NAME}" -gt 9 ]; then
        log::error "Provided cluster name is too long"
        return 1
    fi

    CLEANUP_CLUSTER="true"
    if [[ "$EXECUTION_PROFILE" == "evaluation" ]]; then
            # enable trap to catch kyma provision failures
            trap gardener::reprovision_cluster ERR
            # decreasing attempts to 2 because we will try to create new cluster from scratch on exit code other than 0
            kyma provision gardener az \
                --secret "${GARDENER_KYMA_PROW_PROVIDER_SECRET_NAME}" \
                --name "${CLUSTER_NAME}" \
                --project 
```

**Comment by Sawthis** [comment] 2022-12-06 09:30
[kyma-upgrade-gardener-kyma2-minor-versions](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions) was deleted in the PR: https://github.com/kyma-project/test-infra/pull/6454

**Comment by tobiscr** [comment] 2022-12-06 09:33
The last few runs were not failing caused by Gardener issues:
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main

This is a temporarily issue, probably some Gardener hiccups, and we should add some retry logic to the provisioning if it's fixable by retrying it. 

We have currently no capacity left in neighbors team and won't be able to pick that up.

**Comment by tobiscr** [comment] 2022-12-06 09:35
@k15r : can you please take over. We have a high number of failing pipelines caused by the serverless component. Seem its reconciliation isn't working anymore.

**Comment by kwiatekus** [comment] 2022-12-06 09:52
we hope [this](https://github.com/kyma-project/kyma/pull/16256) can fix it

**Comment by kwiatekus** [comment] 2022-12-06 13:32
https://github.com/kyma-project/kyma/pull/16266

**Comment by kwiatekus** [comment] 2022-12-07 07:55
Fixed with https://github.com/kyma-project/kyma/pull/16266

**Closed by kwiatekus** 2022-12-07 07:55 UTC
Labels: kind/bug, kind/failing-test
