### ISSUE TITLE
Many pipelines failing with serverless reconciliation timing out

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/kyma#16205] opened 2022-11-29 09:56 UTC
**Description**

The following pipelines:

- [nightly-main-reconciler-e2e](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e)
- [pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener)

are consistently failing with a `Error=serverless[3][error: context deadline exceeded]` error.

**Error logs**
```
{"level":"DEBUG","time":"2022-11-29T09:32:36.748Z","message":"Bookkeeper evaluated reconciliation (schedulingID:6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5--f70e4ef4-a353-4593-9b02-d120b6923b8c) for cluster '6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5' to cluster status 'error': Done=CRDs[1],istio[2],cluster-essentials[2],tracing[3],certificates[2],application-connector[3],ory[3],telemetry[3],api-gateway[3],kiali[3],cluster-users[3],logging[3],monitoring[3],eventing[3],istio-resources[3] / Error=serverless[3][error: context deadline exceeded] / New= / Running="}
```
**Expected result**

Serverless component reconciliation should succeed before reconciliation timeout.

**Comment by dbadura** [comment] 2022-11-30 13:23
I installed serverless by reconciler in k3d and it installed successfully.

Can you get the logs or more information to have a broader context of failed installation?
Can you give any tips how should I reproduce this behavior?

**Comment by dbadura** [comment] 2022-11-30 13:38
I noticed that the test pass everyday at 4 AM.

**Comment by mfaizanse** [comment] 2022-11-30 14:39
I am also facing the issue since yesterday. The serverless is failing after upgrading the cluster from 2.9.1 to PR/main.

- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/16197/pre-main-kyma-gardener-gcp-eventing-upgrade/1597946178694025216

**Comment by ruanxin** [comment] 2022-12-02 08:56
in the recent 4 runs of our kyma-upgrade-gardener-kyma2-to-main-reconciler-main pipeline, serverless can't be deployed.

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main

```
 2022-12-02T08:27:57.961Z	WARN	service/status.go:71	Error getting ConfigMap 'serverless-status': client rate limiter Wait returned an error: context deadline exceeded
2022-12-02T08:27:57.961Z	WARN	service/runner.go:148	Reconciler Metrics not initialized
2022-12-02T08:27:57.961Z	ERROR	service/runner.go:130	Runner: reconciliation of component 'serverless' for version 'main' terminated because context was closed
2022-12-02T08:27:57.961Z	WARN	worker/worker.go:69	Worker stops processing operation 'OperationEntity [SchedulingID=local--1abbffcf-c518-4dd2-8420-f0afd85a7c65,CorrelationID=local--756d3b35-1320-466d-88a8-180342af59f8,RuntimeID=local,ClusterConfig=1,Component=serverless,Prio=3,State=new,Type=reconcile]' because invoker returned consistently errors (1 retries): All attempts fail:
#1: context deadline exceeded
2022-12-02T08:27:57.961Z	WARN	worker/workerpool.go:137	Worker pool received an error from worker assigned to operation 'OperationEntity [SchedulingID=local--1abbffcf-c518-4dd2-8420-f0afd85a7c65,CorrelationID=local--756d3b35-1320-466d-88a8-180342af59f8,RuntimeID=local,ClusterConfig=1,Component=serverless,Prio=3,State=new,Type=reconcile]': All attempts fail:
#1: context deadline exceeded
2022-12-02T08:27:58.959Z	DEBUG	worker/workerpool.go:91	Worker pool is waiting for 1 workers to be finished
2022-12-02T08:27:59.959Z	DEBUG	worker/workerpool.go:80	Worker pool has no running workers
2022-12-02T08:27:59.959Z	DEBUG	worker/workerpool.go:142	Worker pool is checking for processable operations (max parallel ops per cluster: 25)
2022-12-02T08:27:59.959Z	DEBUG	worker/workerpool.go:152	Worker pool found 0 processable operations: 
2022-12-02T08:27:59.959Z	DEBUG	worker/workerpool.go:87	Worker pool invoked all processable operations
2022-12-02T08:27:59.959Z	INFO	worker/workerpool.go:62	Stopping worker pool
2022-12-02T08:27:59.959Z	INFO	service/run.go:128	Worker pool finished successfully
2022-12-02T08:27:59.959Z	INFO	step/log.go:62	Deploying Kyma
Deployed Components: 11/12
Could not deploy the following components:
- serverless

**Comment by janmedrek** [comment] 2022-12-02 13:55
@dbadura can you please put some priority into this? The pipelines are failing for the whole day with the Serverless not being deployed.

**Comment by kwiatekus** [comment] 2022-12-06 09:08
It is green on the first run during the day..
@moelsayed suggested this could be related to hibernation...
Hopefully this will help
https://github.com/kyma-project/kyma/pull/16256

**Comment by kwiatekus** [comment] 2022-12-07 07:56
Fixed with https://github.com/kyma-project/kyma/pull/16266

**Closed by kwiatekus** 2022-12-07 07:56 UTC
Labels: kind/bug, kind/failing-test
