### ISSUE TITLE
Define KPIs for Application Connector components

### ISSUE THREAD

**Issue by Disper** [kyma-project/kyma#5029] opened 2019-07-25 11:57 UTC
**Description**

Prepare default KPIs for minikube and cluster deployment for application-connector components. Document defined KPIs.

**Reasons**

Optimize Kyma resources usage

**Comment by janmedrek** [comment] 2019-12-04 08:33
Closing as it's duplicate of:
https://github.com/kyma-project/kyma/issues/5022

**Closed by janmedrek** 2019-12-04 08:33 UTC
Labels: area/application-connector, duplicate
