### ISSUE TITLE
Simplification of Application Gateway

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#10361] opened 2021-01-15 13:48 UTC
**Description**

Application Gateway should be deployed only once in the whole cluster, right now we are unnecessarily creating multiple deployments per application - this leads to multiple components being involved and way too many resources being used.

There is a simple solution to that problem. An all-rounder version of Application Gateway that serves the calls destined for different Applications' APIs. Destination Application and API could be passed in the URL itself: `https://application-gateway.kyma-integration/{APP-NAME}/{SERVICE-NAME}/{TARGET-PATH}`. This approach will allow us to separate from Service Catalog and the requirement for `GATEWAY_URL` to be injected in the workload's pods - Application Gateway URL will be very simple, known and the only information needed to achieve the goal is the Application Name and Service Name.

Such Application Gateway should be included in the Helm Chart of Application Connector, and as result, there will be no need to wait for it to be deployed when new Applications are created. This allows us to drop Gateway-related logic from Application Operator, with a bit more changes to the whole area (Connectivity Validator), even get rid of the whole component itself.

**Reasons**

There are multiple components and unnecessary configurations needed for enabling a very simple scenario. Their number can be reduced and as result - the flow from the user perspective and architecture point of view will be simplified.

**Acceptance Criteria**
- [ ] Application Gateway is deployed as a single instance in the cluster
- [ ] Compass Runtime Agent fetches default credentials
- [ ] Calling Application Gateway with specific URL invokes being proxied to one of the available systems' APIs
- [ ] Application Gateway URL is constructed from its in-cluster address, Application name, and Service name
- [ ] There is no need to know Access Services / ServiceInstance / other config names in order to call Application Gateway
- [ ] Application Operator, Service Catalog, and other components are not involved in the flow
- [ ] Changes made as a separate, experimental Application Connectivity version

**Comment by akgalwas** [comment] 2021-04-23 06:03
Since service name is used in path we need to consider the following :
- It must not contain characters that are forbidden in URLs
- It must be unique, however, the current implementation allows to create services with the same name. 

Application Registry could enforce service name uniqueness but we need to consider backward compatibility.

**Comment by akgalwas** [comment] 2021-04-23 06:12
In Compass mode Application is created by Compass Runtime Agent that maps  Director data model to Application CRD model. 
The mapping is as follows:
- Application->Application CRD
- APIBundle->Service in Application CRD
- APIDefinition->Service.Entry in Application CRD

One API Bundle may contain many API Definitions. So in order to access specific API that is a part of a bundle the URL should have the following form: https://application-gateway.kyma-integration/{APP-NAME}/{BUNDLE-NAME}/{API-NAME}/{TARGET-PATH}

**Comment by akgalwas** [comment] 2021-04-23 06:16
In the current implementation Service.Name stored in Application CRD is normalised to ensure it is unique in Service Catalog. We need to be careful to not change the value of this field to avoid potential regressions.

**Comment by franpog859** [comment] 2021-04-23 10:02
For testing purposes, we decided to create a separate prow job running a separate fast integration pipeline that deploys a central Application Gateway (and possibly other Application Connectivity 2.0 components) and test it against the open-source commerce-mock scenario. Here is what to do next:
- [here](https://github.com/kyma-project/kyma/pull/11152) is the Draft PR that consists of the fast integration pipeline for such a job. It should be cherry-picked to the main branch with the Application Gateway implementation and then verified. The idea is initially consulted with @crabtree . After the test verification, his (or other [owners'](https://github.com/kyma-project/kyma/blob/main/CODEOWNERS#L306)) code review may be needed
- [here](https://github.com/kyma-project/test-infra/pull/3581) is the PR that consists of the prow job running the new fast integration pipeline. It should be verified using the [test-infra tooling](https://github.com/kyma-project/test-infra/tree/main/prow#test-changes-in-scripts). I think this job could be merged after the merge of the main Application Gateway PR. If everything works smoothly, it can be changed to `required`

**Comment by akgalwas** [comment] 2021-04-26 07:11
We need to carefully consider the case with Compass and Compass Runtime Agent. In the [current implementation](https://github.com/kyma-project/kyma/blob/3cfaf33c2c0b8f45268762ba6fe2e5521e5863b3/components/compass-runtime-agent/internal/kyma/applications/converter.go#L70) service name is normalised. This is related to [this comment](https://github.com/kyma-project/kyma/issues/10361#issuecomment-825417063)

**Comment by franpog859** [comment] 2021-06-01 06:21
**#fast_integration_tests**
We created two additional pipelines with the commerce mock scenario. Both of them run the new Central Application Gateway and use Functions that utilize it. One pipeline tests the open-source scenario and the second one tests the Compass scenario. You can find them [in this PR](https://github.com/kyma-project/kyma/pull/11152)
We created also two optional Prow jobs. The first one runs the open-source pipeline and the second one the Compass one. You can find them [in this PR](https://github.com/kyma-project/test-infra/pull/3581)

Currently, we are struggling to make it work on Prow as the pipelines work fine while triggered manually on a Gardener cluster but there is a problem with Function response on Prow jobs. I and @rafalpotempa are investigating it

**Comment by franpog859** [comment] 2021-06-21 07:57
Fast integration pipelines are merged

**Closed** 2021-07-01 06:51 UTC
Labels: area/application-connector, enhancement
